'use client';
import {useState} from 'react';
import {bankPath,brazilDay,currency} from '@/lib/icom-bank/model';
import {adminMoneyInput,adminMoneyText,type AdminEntry} from '@/lib/icom-bank/administrative';
import {receivableKinds,receivableRemaining,receivableExisting,type Receivable,type Receipt,type ReceivablesData} from '@/lib/icom-bank/receivables';
import {payableMethods} from '@/lib/icom-bank/payables';
import {vehicleBanks} from '@/lib/icom-bank/vehicle-banks';
export const receiptMethodLabels:Record<string,string>={PIX:'Pix',DINHEIRO:'Dinheiro',CARTAO:'Cartão',TRANSFERENCIA:'Transferência',BOLETO:'Boleto'};
export default function BankReceivableForm({bill,source,data,action,receipt,onCancel,onSaved}:{bill?:Receivable;source?:AdminEntry;data:ReceivablesData;action:'save'|'receive'|'reverse';receipt?:Receipt;onCancel:()=>void;onSaved:(message:string)=>void}){
 const [id]=useState(()=>bill?.id||crypto.randomUUID()),[requestId]=useState(()=>crypto.randomUUID()),[title,setTitle]=useState(bill?.title||''),[payer,setPayer]=useState(bill?.payer||''),[kind,setKind]=useState(bill?.kind||'CLIENTE'),[bank,setBank]=useState(bill?.bank||''),[amount,setAmount]=useState(bill?adminMoneyText(action==='receive'?receivableRemaining(bill):Number(bill.amount_cents)):''),[date,setDate]=useState(action==='receive'?brazilDay():bill?(bill.due_date||''):brazilDay()),[notes,setNotes]=useState(bill?.notes||''),[method,setMethod]=useState('PIX'),[confirmed,setConfirmed]=useState(false),[mode,setMode]=useState('new'),[existing,setExisting]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const candidates=bill?receivableExisting(bill,source,data.entries,data.receipts):[],lockedAmount=!!bill&&(!!bill.source_entry_id||Number(bill.received_cents)>0);
 async function submit(values:FormData){setBusy(true);setError('');try{
  const cents=action==='reverse'?0:action==='save'&&lockedAmount?Number(bill!.amount_cents):adminMoneyInput(String(values.get('amount')||amount));
  if(action==='receive'&&cents>receivableRemaining(bill!))throw new Error('O valor recebido não pode superar o saldo desta conta.');
  const body=action==='save'?{action,id,expected_updated_at:bill?.updated_at||null,title,payer,kind,bank,notes,amount_cents:cents,due_date:String(values.get('due_date')||'')||null}:action==='receive'?{action,id,expected_updated_at:bill!.updated_at,request_id:requestId,amount_cents:cents,received_at:mode==='existing'?date:String(values.get('received_at')||date),method,confirmed,existing_id:mode==='existing'?existing:null}:{action,id,expected_updated_at:bill!.updated_at,receipt_id:receipt!.id,reason};
  const r=await fetch(bankPath('/api/receivables'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),result=await r.json() as {error?:string};if(!r.ok)throw new Error(result.error||'Não foi possível salvar.');
  onSaved(action==='save'?'Conta salva. Nenhuma entrada foi registrada no caixa.':action==='reverse'?'Recebimento desfeito. A entrada foi arquivada e o saldo da conta foi reaberto.':mode==='existing'?'Recebimento vinculado à entrada existente, sem duplicar o caixa.':'Recebimento confirmado. A entrada foi registrada uma única vez no caixa.');
 }catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.');}finally{setBusy(false);}}
 return <form data-bank-manual-view={action==='receive'?'receber_conta_form':'conta_receber_form'} className="bank-panel bank-receivable-form" onSubmit={e=>{e.preventDefault();void submit(new FormData(e.currentTarget));}}><div className="bank-panel-title"><div><p className="bank-eyebrow">{bill?bill.title:'ORGANIZAR RECEBIMENTOS DA LOJA'}</p><h2>{action==='save'?bill?'Editar conta a receber':'Cadastrar conta a receber':action==='receive'?'Confirmar recebimento':'Desfazer recebimento'}</h2></div>{action==='receive'&&bill&&<strong>Falta receber: {currency(receivableRemaining(bill))}</strong>}</div><fieldset disabled={busy}><div className="bank-form-grid">
 {action==='save'?<>
 <label>Nome / descrição<input required autoFocus minLength={2} maxLength={160} placeholder="Ex.: Repasse do financiamento ou valor de cliente" value={title} onChange={e=>setTitle(e.target.value)}/></label>
 <label>Quem paga?<select value={kind} onChange={e=>setKind(e.target.value as keyof typeof receivableKinds)}>{Object.entries(receivableKinds).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
 <label>Nome do cliente ou da operadora (opcional)<input maxLength={160} placeholder="Identifique quem fará o pagamento" value={payer} onChange={e=>setPayer(e.target.value)}/></label>
 {kind==='BANCO'&&<label>Banco<select value={vehicleBanks.some(b=>b.name===bank)?bank:bank?'OUTRO':''} onChange={e=>setBank(e.target.value==='OUTRO'?'Outro banco':e.target.value)}><option value="">Selecionar banco</option>{vehicleBanks.map(b=><option key={b.name} value={b.name}>{b.name}</option>)}<option value="OUTRO">Outro banco</option></select>{bank&&!vehicleBanks.some(b=>b.name===bank)&&<input aria-label="Nome do outro banco" maxLength={120} value={bank} onChange={e=>setBank(e.target.value)}/>}</label>}
 <label>Valor desta conta (R$)<input name="amount" inputMode="decimal" required value={amount} readOnly={lockedAmount} placeholder="0,00" onChange={e=>setAmount(e.target.value)} onBlur={()=>{try{setAmount(adminMoneyText(adminMoneyInput(amount)));}catch{}}}/>{lockedAmount&&<small>{bill?.source_entry_id?'Calculado pela venda, abatendo a troca líquida e o valor recebido inicialmente.':'Desfaça os recebimentos antes de alterar o valor desta conta.'}</small>}</label>
 <label>Vencimento<input name="due_date" type="date" min="2000-01-01" max="2100-12-31" required={!bill?.source_entry_id} defaultValue={date}/>{bill?.source_entry_id&&<small>Deixe vazio se a data ainda não estiver definida.</small>}</label>
 <label>Observações (opcional)<textarea maxLength={2000} rows={2} value={notes} onChange={e=>setNotes(e.target.value)}/></label></>:action==='reverse'?<><p>Recebimento de {currency(Number(receipt!.amount_cents))} em {receipt!.received_at.split('-').reverse().join('/')}.</p><label>Motivo da correção<textarea required minLength={3} maxLength={1000} rows={3} value={reason} onChange={e=>setReason(e.target.value)}/></label></>:<>
 <label>Como registrar no caixa<select value={mode} onChange={e=>{setMode(e.target.value);setExisting('');setConfirmed(false);}}><option value="new">Criar entrada para este recebimento</option><option value="existing" disabled={!candidates.length}>Vincular entrada já lançada</option></select></label>
 {mode==='existing'&&<label>Entrada já registrada<select required value={existing} onChange={e=>{setExisting(e.target.value);const entry=candidates.find(x=>x.id===e.target.value);if(entry){setAmount(adminMoneyText(Number(entry.amount_cents)));setDate(entry.entry_date);setMethod(entry.details.payment_method!);}}}><option value="">Selecione a entrada correspondente</option>{candidates.map(e=><option key={e.id} value={e.id}>{e.entry_date.split('-').reverse().join('/')} · {e.description} · {currency(Number(e.amount_cents))}</option>)}</select></label>}
 <label>Valor recebido agora (R$)<input name="amount" inputMode="decimal" required readOnly={mode==='existing'} value={amount} onChange={e=>setAmount(e.target.value)} onBlur={()=>{try{setAmount(adminMoneyText(adminMoneyInput(amount)));}catch{}}}/><small>Você pode confirmar uma parte. O restante continuará em aberto.</small></label>
 <label>Data do recebimento<input name="received_at" type="date" required disabled={mode==='existing'} min={source?.entry_date||'2000-01-01'} max={brazilDay()} key={mode+existing} defaultValue={date}/></label>
 <label>Forma do recebimento<select disabled={mode==='existing'} value={method} onChange={e=>setMethod(e.target.value)}>{payableMethods.map(m=><option key={m} value={m}>{receiptMethodLabels[m]}</option>)}</select></label>
 </>}
 </div>{action==='save'&&<p className="bank-note">Vendas com os dados completos entram automaticamente aqui. Cadastre manualmente outros recebimentos da loja. As parcelas de contratos do ICOM Bank continuam na área Parcelas.</p>}{action==='receive'&&<><p className="bank-note">Confirme somente o dinheiro que já entrou. Esta tela faz o registro interno, sem consultar ou movimentar a conta bancária. O valor recebido inicialmente na venda não será somado outra vez.</p><label className="bank-checkbox"><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Conferi que este valor já foi recebido.</label></>}{action==='reverse'&&<p className="bank-note">A entrada vinculada será arquivada e sairá do caixa realizado. O histórico e o motivo ficarão preservados.</p>}
 <div className="bank-actions"><button type="button" onClick={onCancel}>Cancelar</button><button className="bank-primary" disabled={busy||action==='receive'&&(!confirmed||mode==='existing'&&!existing)}>{busy?'Salvando…':action==='save'?'SALVAR CONTA':action==='receive'?'CONFIRMAR RECEBIMENTO':'CONFIRMAR CORREÇÃO'}</button></div></fieldset>{error&&<p className="bank-error" role="alert">{error}</p>}</form>;
}
