'use client';
import {useState,type FormEvent} from 'react';
import {bankPath,brazilDay,currency} from '@/lib/icom-bank/model';
import {investorInput,investorMatches,type BankInvestor} from '@/lib/icom-bank/investors';
import {saleCash,type CashEntry} from '@/lib/icom-bank/cash';
export default function BankInvestors({initial,entries}:{initial:BankInvestor[];entries:CashEntry[]}){
 const [rows,setRows]=useState(initial),[selected,setSelected]=useState(initial[0]?.id||''),[form,setForm]=useState<BankInvestor|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState('');
 const investor=rows.find(x=>x.id===selected),sales=investor?entries.filter(x=>x.active&&x.kind==='VENDA'&&x.details.sale_owner==='INVESTIDOR'&&investorMatches(investor,x.details)):[],trades=investor?entries.filter(x=>x.active&&x.kind==='VENDA'&&x.details.trade_in&&x.details.trade_destination==='INVESTIDOR'&&investorMatches(investor,x.details,true)):[];
 const open=(row?:BankInvestor)=>{setForm(row||{id:crypto.randomUUID(),name:'',email:'',phone:'',notes:'',active:true,created_at:'',updated_at:''});setError('');setNotice('');};
 async function save(e:FormEvent){e.preventDefault();if(!form||busy)return;setError('');setBusy(true);try{const payload=investorInput({...form,expected_updated_at:form.updated_at||null});const r=await fetch(bankPath('/api/investors'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),d=await r.json() as {row?:BankInvestor;error?:string};if(!r.ok||!d.row)throw new Error(d.error||'Não foi possível salvar.');setRows(old=>[d.row!,...old.filter(x=>x.id!==d.row!.id)].sort((a,b)=>a.name.localeCompare(b.name,'pt-BR')));setSelected(d.row.id);setForm(null);setNotice('Investidor salvo. Já pode ser selecionado na venda e no destino da troca.');}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.');}finally{setBusy(false);}}
 return <><div className="bank-heading"><div><p className="bank-eyebrow">ADMINISTRATIVO · PARCEIROS</p><h1>Investidores da loja</h1><p>Cadastre aos poucos. Os carros aparecem conforme você vincula as vendas e as trocas.</p></div><a className="bank-admin-export" href={bankPath('/administrativo')}>← Voltar ao Administrativo</a></div><div className="bank-actions"><button className="bank-primary" onClick={()=>open()}>+ CADASTRAR INVESTIDOR</button></div>{notice&&<p className="bank-note" role="status">{notice}</p>}{error&&<p className="bank-error" role="alert">{error}</p>}
 {form&&<section data-bank-manual-view="investidor_form" className="bank-panel"><h2>{form.updated_at?'Editar contatos':'Novo investidor'}</h2><form onSubmit={save}><div className="bank-form-grid"><label>Nome do investidor<input required minLength={2} maxLength={160} readOnly={!!form.updated_at} disabled={busy} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><small>O nome fica fixo após o cadastro para manter os vínculos e as reservas consistentes.</small></label><label>Telefone<input type="tel" maxLength={30} disabled={busy} value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>E-mail<input type="email" maxLength={254} disabled={busy} value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label></div><label>Observações<textarea maxLength={2000} disabled={busy} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><div className="bank-actions"><button type="button" disabled={busy} onClick={()=>setForm(null)}>Cancelar</button><button className="bank-primary" disabled={busy}>{busy?'Salvando…':'SALVAR INVESTIDOR'}</button></div></form></section>}
 <div className="bank-investors-layout"><section className="bank-panel"><h2>Investidores cadastrados</h2><input aria-label="Buscar investidor" placeholder="Buscar pelo nome…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="bank-investor-list">{rows.filter(x=>x.name.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR'))).map(x=><button className={selected===x.id?'bank-investor-current':''} aria-pressed={selected===x.id} key={x.id} onClick={()=>setSelected(x.id)}><strong>{x.name}</strong><small>{x.phone||x.email||'Sem contato informado'}</small></button>)}{!rows.length&&<p className="bank-note">Nenhum investidor cadastrado. Comece pelo botão acima.</p>}</div></section>
 <section className="bank-panel">{investor?<><div className="bank-heading"><div><h2>{investor.name}</h2><p>{[investor.phone,investor.email].filter(Boolean).join(' · ')||'Contatos ainda não informados'}</p></div><button onClick={()=>open(investor)}>Editar contatos</button></div>{investor.notes&&<p>{investor.notes}</p>}<div className="bank-stats"><article><span>Vendas vinculadas</span><strong>{sales.length}</strong></article><article><span>Carros recebidos pelo investidor</span><strong>{trades.length}</strong></article><article><span>Dinheiro recebido a devolver</span><strong>{currency(sales.reduce((n,s)=>n+saleCash(s,entries,brazilDay()).investor,0))}</strong></article></div>
 <h3>Carros vendidos · histórico</h3><div className="bank-table"><table><thead><tr><th>Carro / versão</th><th>Placa</th><th>Data da venda</th><th>Situação</th></tr></thead><tbody>{sales.map(s=><tr key={s.id}><td>{s.details.vehicle}</td><td>{s.details.plate||'—'}</td><td>{s.entry_date.split('-').reverse().join('/')}</td><td>{s.status==='REALIZADO'?'Venda realizada':'Venda prevista'}</td></tr>)}{!sales.length&&<tr><td colSpan={4}>Nenhuma venda vinculada a este investidor.</td></tr>}</tbody></table></div>
 <h3>Carros que ficaram com o investidor · trocas</h3><div className="bank-table"><table><thead><tr><th>Carro / versão</th><th>Placa</th><th>Ano</th><th>Valor acordado</th><th>Origem</th></tr></thead><tbody>{trades.map(s=><tr key={s.id}><td>{s.details.trade_vehicle}</td><td>{s.details.trade_plate}</td><td>{s.details.trade_year}</td><td>{currency(Number(s.details.trade_value_cents||0))}</td><td>Troca na venda de {s.details.plate||s.details.vehicle}{s.status==='PREVISTO'&&' · prevista'}</td></tr>)}{!trades.length&&<tr><td colSpan={5}>Nenhum carro destinado a este investidor.</td></tr>}</tbody></table></div><p className="bank-note">Para vincular um carro, selecione este investidor em Administrativo → Vendas. Registros antigos com o mesmo nome também aparecem. Carros previstos não representam dinheiro recebido.</p></>:<div className="bank-empty">Selecione um investidor para ver seus carros e seu histórico.</div>}</section></div></>;
}
