 'use client';
import {useState} from 'react';
import {bankPath,brazilDay,currency} from '@/lib/icom-bank/model';
import {accountSummary,accountBanks,type AccountData,type BankAccount} from '@/lib/icom-bank/accounts';
import {adminMoneyInput,adminMoneyText} from '@/lib/icom-bank/administrative';
export default function BankAccounts({initial}:{initial:AccountData}){
 const [data,setData]=useState(initial),[draft,setDraft]=useState<{id:string;name:string;bank:string;scope:string;active:boolean;initial:string;date:string;expected:string|null}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[assign,setAssign]=useState(''),[target,setTarget]=useState('');const summary=accountSummary(data);
 const open=(a?:BankAccount)=>{setError('');setDraft({id:a?.id||crypto.randomUUID(),name:a?.name||'',bank:a?.bank||'Santander',scope:a?.scope||'PESSOAL',active:a?.active??true,initial:'0,00',date:brazilDay(),expected:a?.updated_at||null});};
 const field=(k:string,v:string|boolean)=>setDraft(d=>d?{...d,[k]:v}:d);
 async function load(){const r=await fetch(bankPath('/api/accounts'),{cache:'no-store'}),d=await r.json() as AccountData&{error?:string};if(!r.ok)throw new Error(d.error||'Não foi possível atualizar.');setData(d);}
 async function post(body:unknown){setBusy(true);setError('');try{const r=await fetch(bankPath('/api/accounts'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error||'Não foi possível salvar.');setDraft(null);setAssign('');setTarget('');setNotice('Registro salvo.');await load();window.dispatchEvent(new Event('icom-bank-wealth-changed'));}catch(e){setError(e instanceof Error?e.message:'Confira os dados.');}finally{setBusy(false);}}
 const unlinked=data.entries.filter(e=>e.active&&e.status==='REALIZADO'&&e.entry_date<=brazilDay()&&!data.links.some(l=>l.ledger_entry_id===e.id));
 return <div data-bank-manual-view={draft?'conta_bancaria_form':'contas_bancarias'}><div className="bank-heading"><div><p className="bank-eyebrow">IA BANK · SEU DINHEIRO</p><h1>Contas bancárias</h1><p>Saiba em qual conta cada entrada e pagamento foi registrado.</p></div><a href={bankPath('/administrativo/pessoal?tab=patrimonio')}>← Patrimônio pessoal</a></div><div className="ia-money-links"><article><span>Saldo total registrado<strong>{currency(summary.gross)}</strong><small>Contas + movimentos sem conta</small></span></article><article><span>Saldo disponível total<strong>{currency(summary.available)}</strong><small>Já desconta as reservas dos investidores</small></span></article><article><span>Reservado aos investidores<strong>{currency(summary.reserved)}</strong><small>Não está disponível para despesas</small></span></article></div><div className="bank-admin-toolbar"><button className="bank-primary" disabled={busy} onClick={()=>open()}>+ Cadastrar conta</button><button disabled={busy} onClick={()=>void load().catch(e=>setError(e.message))}>Atualizar saldos</button></div>{error&&<p className="bank-error" role="alert">{error}</p>}{notice&&<p role="status" className="bank-note">{notice}</p>}
 {draft&&<form className="bank-panel" onSubmit={e=>{e.preventDefault();try{void post({...draft,initial_cents:adminMoneyInput(draft.initial.replace(/^-/,'')||'0')*(draft.initial.startsWith('-')?-1:1),initial_date:draft.date,expected_updated_at:draft.expected});}catch(e){setError(e instanceof Error?e.message:'Confira o saldo.');}}}><h2>{draft.expected?'Editar conta':'Nova conta'}</h2><fieldset disabled={busy}><div className="bank-form-grid"><label>Como você chama esta conta?<input required minLength={2} maxLength={100} placeholder="Ex.: Santander pessoal ou Santander loja" value={draft.name} onChange={e=>field('name',e.target.value)}/><small>Use esse nome ao pedir lançamentos por voz.</small></label><label>Qual é o banco?<input list="account-banks" required minLength={2} maxLength={100} value={draft.bank} onChange={e=>field('bank',e.target.value)}/><datalist id="account-banks">{accountBanks.map(b=><option key={b} value={b}/>)}</datalist></label><label>De quem é a conta?<select value={draft.scope} onChange={e=>field('scope',e.target.value)}><option value="PESSOAL">Pessoal</option><option value="LOJA">Loja</option></select></label>{!draft.expected&&<><label>Quanto já havia nesta conta antes dos lançamentos? (R$)<input inputMode="decimal" required value={draft.initial} onChange={e=>field('initial',e.target.value)} onBlur={()=>{try{field('initial',(draft.initial.startsWith('-')?'-':'')+adminMoneyText(adminMoneyInput(draft.initial.replace(/^-/,'')||'0')));}catch{}}}/><small>Informe zero se este dinheiro já estiver nos lançamentos antigos. Saldo inicial não é lucro.</small></label><label>Data desse saldo inicial<input required type="date" min="2000-01-01" max={brazilDay()} value={draft.date} onChange={e=>field('date',e.target.value)}/></label></>}<label className="bank-checkbox"><input type="checkbox" checked={draft.active} onChange={e=>field('active',e.target.checked)}/>Conta disponível para novos movimentos</label></div><div className="bank-actions"><button type="button" onClick={()=>setDraft(null)}>Cancelar</button><button className="bank-primary">Salvar conta</button></div></fieldset></form>}
 <section className="bank-panel"><h2>Saldos por conta</h2><div className="bank-table"><table><thead><tr><th>Conta</th><th>Banco</th><th>De quem</th><th>Saldo registrado</th><th>Movimentos</th><th>Ação</th></tr></thead><tbody>{summary.rows.map(a=><tr key={a.id}><td><strong>{a.name}</strong><small>{a.active?'Ativa':'Inativa · histórico preservado'}</small></td><td>{a.bank}</td><td>{a.scope==='LOJA'?'Loja':'Pessoal'}</td><td>{currency(a.balance)}</td><td>{a.movements}</td><td><button onClick={()=>open(a)}>Editar</button></td></tr>)}<tr><td>Sem conta identificada</td><td>Histórico anterior</td><td>—</td><td>{currency(summary.unassigned)}</td><td>{summary.unassignedCount}</td><td>Identifique abaixo</td></tr></tbody></table></div><p className="bank-note">Os saldos por conta mostram os movimentos registrados, antes das reservas. As reservas dos investidores são descontadas do saldo disponível total. Compare com seus extratos; esta tela não consulta bancos.</p></section>
 {!!unlinked.length&&<form className="bank-panel" onSubmit={e=>{e.preventDefault();void post({action:'assign',entry_id:assign,account_id:target});}}><h2>Identificar conta de um movimento antigo</h2><p>Escolha somente a conta em que o dinheiro entrou ou saiu. Isso não lança o valor novamente nem muda o saldo total.</p><div className="bank-form-grid"><label>Qual movimento?<select required value={assign} onChange={e=>setAssign(e.target.value)}><option value="">Selecionar lançamento</option>{unlinked.map(e=><option key={e.id} value={e.id}>{e.entry_date} · {e.description} · {currency(Number(e.amount_cents||0))}</option>)}</select></label><label>Em qual conta ocorreu?<select required value={target} onChange={e=>setTarget(e.target.value)}><option value="">Selecionar conta</option>{data.accounts.filter(a=>a.active).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label></div><button disabled={busy} className="bank-primary">Identificar conta</button></form>}
 </div>;
}
