'use client';
import {useEffect,useState,type FormEvent} from 'react';
import {expenseAudiences,expenseNatures,audienceLabel,natureLabel,expenseContext} from '@/lib/icom-bank/expense-context';
import {personalCategories,personalCategory} from '@/lib/icom-bank/personal-expenses';
import {bankPath,brazilDay,currency} from '@/lib/icom-bank/model';
import {adminInput,adminMoneyInput,adminMoneyText,adminSaleCalculation,adminSaleSettlement,adminSaleReceived,defaultSaleCommission,type AdminEntry,type AdminKind,type AdminScope,type AdminDetails,type AdminSeller,type SaleReceipt} from '@/lib/icom-bank/administrative';

import {saleCash,tradeDestinations} from '@/lib/icom-bank/cash';
import type {BankInvestor} from '@/lib/icom-bank/investors';
import BankVehiclePicker from './BankVehiclePicker';
import type {VehicleSpec} from '@/lib/icom-bank/vehicle-catalog';
import type {StockRow} from '@/lib/icom-bank/stock';
import {vehicleBanks} from '@/lib/icom-bank/vehicle-banks';

const kinds:{value:AdminKind;label:string}[]=[{value:'VENDA',label:'Venda de veículo'},{value:'ENTRADA',label:'Entrada de caixa'},{value:'CUSTO',label:'Custo / despesa da loja'},{value:'RETORNO',label:'Retorno bancário'},{value:'TROCA',label:'Troca de veículo'},{value:'MENSAL',label:'Conta mensal'},{value:'PESSOAL',label:'Despesa pessoal'}];
type Field={key:keyof AdminDetails;label:string;money?:boolean;number?:boolean;required?:boolean;help?:string};
const fields:Record<AdminKind,Field[]>={
 VENDA:[{key:'vehicle',label:'Carro / modelo',required:true},{key:'plate',label:'Placa'},{key:'seller',label:'Vendedor'},{key:'purchase_cents',label:'Valor de compra',money:true,required:true},{key:'vehicle_cost_cents',label:'Custos adicionais do veículo',money:true,help:'Só manutenção, polimento e outros gastos. Não repita o valor de compra.'},{key:'commission_cents',label:'Custo fixo do vendedor',money:true,help:'R$ 1.650,00 nas novas vendas. Registros anteriores mantêm seu custo original.'},{key:'sale_cents',label:'Valor da venda',money:true,required:true}],
 ENTRADA:[],PESSOAL:[],CUSTO:[{key:'vehicle',label:'Carro / referência (opcional)'},{key:'plate',label:'Placa (opcional)'}],
 RETORNO:[{key:'vehicle',label:'Carro / modelo',required:true},{key:'plate',label:'Placa'},{key:'seller',label:'Vendedor'},{key:'bank',label:'Banco'},{key:'return_level',label:'Retorno (1, 2 ou 3)',number:true},{key:'financed_cents',label:'Valor financiado',money:true},{key:'tax_cents',label:'Imposto',money:true},{key:'manager_cents',label:'Repasse Lazinho / gerente',money:true},{key:'seller_cents',label:'Repasse vendedor',money:true}],
 TROCA:[{key:'vehicle',label:'Carro de troca',required:true},{key:'plate',label:'Placa'},{key:'paid_cents',label:'Valor pago',money:true},{key:'debt_cents',label:'Débito da troca',money:true},{key:'document_cents',label:'Valor documentação vendida',money:true},{key:'cc_cents',label:'Valor pago CC',money:true},{key:'discount_cents',label:'Desconto débito / documento / caixa',money:true},{key:'division_cents',label:'Divisão para cada (manual)',money:true},{key:'profit_share_cents',label:'Lucro para cada (manual)',money:true}],
 MENSAL:[{key:'due_day',label:'Dia habitual do vencimento',number:true}],
};
function MoneyField({value,onChange,disabled,readOnly,required}:{value:string;onChange:(value:string)=>void;disabled?:boolean;readOnly?:boolean;required?:boolean}){
 return <input type="text" inputMode="decimal" placeholder="0,00" maxLength={20} required={required} disabled={disabled} readOnly={readOnly} value={value} onChange={e=>onChange(e.target.value)} onBlur={()=>{if(!value.trim())return;try{onChange(adminMoneyText(adminMoneyInput(value)));}catch{/* Keep invalid text visible for correction. */}}}/>;
}
export type AdminPreset={kind:AdminKind;date?:string;description?:string;scope?:AdminScope;due_day?:number;stock?:StockRow;details?:AdminDetails};
export default function BankAdminForm({entry,preset,sellers,entries=[],onSaved,onCancel}:{entries?:AdminEntry[];entry?:AdminEntry;preset:AdminPreset;sellers:AdminSeller[];onSaved:(entry:AdminEntry)=>void;onCancel:()=>void}){
 const [vehicle,setVehicle]=useState<VehicleSpec|undefined>(entry?.details.vehicle_spec||preset.stock?.vehicle||(entry?.details.vehicle?{brand:'',model:entry.details.vehicle,version:'',year:null}:undefined)),[tradeVehicle,setTradeVehicle]=useState<VehicleSpec|undefined>(entry?.details.trade_spec||(entry?.details.trade_vehicle?{brand:'',model:entry.details.trade_vehicle,version:'',year:entry.details.trade_year||null}:undefined)),[withVehicle,setWithVehicle]=useState(!!entry?.details.vehicle||!!preset.stock);
 const [investors,setInvestors]=useState<BankInvestor[]>([]),[investorError,setInvestorError]=useState(''),[investorRetry,setInvestorRetry]=useState(0);
 const initialKind=entry?.kind||preset.kind;
 const [kind,setKind]=useState(initialKind),[id]=useState(()=>entry?.id||crypto.randomUUID()),[date,setDate]=useState(entry?.entry_date||preset.date||brazilDay()),[description,setDescription]=useState(entry?.description||preset.description||''),[scope,setScope]=useState<AdminScope|''>(entry?.scope||preset.scope||(initialKind==='MENSAL'?'':initialKind==='PESSOAL'?'PESSOAL':'LOJA')),[category,setCategory]=useState(entry?.category||''),[status,setStatus]=useState(entry?.status||'PREVISTO'),[value,setValue]=useState(entry?.amount_cents===null?'':entry?.amount_cents!==undefined?adminMoneyText(entry.amount_cents):''),[receipt,setReceipt]=useState<SaleReceipt>(()=>entry?.kind==='VENDA'?(entry.amount_cents===adminSaleSettlement(Number(entry.details.sale_cents||0),entry.details).remaining?'INTEGRAL':entry.amount_cents===0?'PENDENTE':'PARCIAL'):'INTEGRAL'),[details,setDetails]=useState<Record<string,string>>(()=>{
  const obj:Record<string,string>={};for(const [key,v] of Object.entries(entry?.details||preset.details||{}))obj[key]=typeof v==='number'&&key.endsWith('_cents')?adminMoneyText(v):String(v);
  if(initialKind==='VENDA'){obj.trade_in=String(entry?.details.trade_in??!!entry?.details.trade_vehicle);obj.trade_has_debts=String(entry?.details.trade_has_debts??false);obj.trade_has_payoff=String(entry?.details.trade_has_payoff??false);obj.trade_ipva_cents ||= '0,00';obj.trade_fines_cents ||= '0,00';}
  if(initialKind==='VENDA'&&!entry){obj.commission_cents=adminMoneyText(obj.sale_mode==='REPASSE'?0:defaultSaleCommission);obj.vehicle_cost_cents ||= '0,00';}
  if(preset.stock){obj.stock_id=preset.stock.id;obj.vehicle=(preset.stock.vehicle.brand+' '+(preset.stock.vehicle.version||preset.stock.vehicle.model)).slice(0,160);obj.plate=preset.stock.plate;if(initialKind==='VENDA')obj.purchase_cents=adminMoneyText(preset.stock.purchase_cents);}
  if(preset.due_day)obj.due_day=String(preset.due_day);return obj;
 }),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{document.getElementById('admin-form')?.scrollIntoView({block:'start'});},[]);
 useEffect(()=>{if(kind!=='VENDA')return;let live=true;fetch(bankPath('/api/investors')).then(async r=>{const d=await r.json() as {rows?:BankInvestor[];error?:string};if(!r.ok||!Array.isArray(d.rows))throw new Error(d.error||'Não foi possível carregar os investidores.');return d.rows;}).then(list=>{if(live){setInvestors(list);setInvestorError('');}}).catch(e=>{if(live)setInvestorError(e.message);});return()=>{live=false;};},[kind,investorRetry]);
 const changeKind=(next:AdminKind)=>{setKind(next);setScope(next==='MENSAL'?'':next==='PESSOAL'?'PESSOAL':'LOJA');setDetails(next==='VENDA'?{commission_cents:adminMoneyText(defaultSaleCommission),vehicle_cost_cents:'0,00',trade_in:'false',trade_has_debts:'false',trade_has_payoff:'false',trade_ipva_cents:'0,00',trade_fines_cents:'0,00'}:{});setValue('');setReceipt('INTEGRAL');setError('');setVehicle(undefined);setTradeVehicle(undefined);setWithVehicle(false);};
 let calculation:ReturnType<typeof adminSaleCalculation>|null=null;let calculationError='';
 if(kind==='VENDA'){try{calculation=adminSaleCalculation(details);}catch(e){calculationError=e instanceof Error?e.message:'Confira os valores.';}}
 const tradePayload=():AdminDetails=>({trade_in:details.trade_in==='true',...(details.trade_in==='true'?{trade_vehicle:details.trade_vehicle||'',trade_plate:(details.trade_plate||'').replace(/[^a-z0-9]/gi,'').toUpperCase(),trade_year:Number(details.trade_year),trade_value_cents:adminMoneyInput(details.trade_value_cents||'0'),trade_has_debts:details.trade_has_debts==='true',...(details.trade_has_debts==='true'?{trade_ipva_cents:adminMoneyInput(details.trade_ipva_cents||'0'),trade_fines_cents:adminMoneyInput(details.trade_fines_cents||'0'),trade_has_payoff:details.trade_has_payoff==='true',...(details.trade_has_payoff==='true'?{trade_payoff_cents:adminMoneyInput(details.trade_payoff_cents||'0'),trade_payoff_bank:details.trade_payoff_bank||'',trade_payoff_bank_other:details.trade_payoff_bank_other||''}:{})}:{})}:{})});
 let settlement:ReturnType<typeof adminSaleSettlement>|null=null,settlementError='';
 if(calculation){try{settlement=adminSaleSettlement(calculation.sale,tradePayload());}catch(e){settlementError=e instanceof Error?e.message:'Confira os valores da troca.';}}
 const setDetail=(key:string,value:string)=>setDetails(d=>({...d,[key]:value}));
 const bankSelect=(key:'payment_bank'|'trade_payoff_bank',label:string)=><label>{label}<select required disabled={busy} value={details[key]||''} onChange={e=>setDetail(key,e.target.value)}><option value="">Selecione o banco</option>{vehicleBanks.map(b=><option key={b.name}>{b.name}</option>)}<option value="OUTRO">Outro banco / financeira</option></select>{details[key]==='OUTRO'&&<input aria-label={'Nome de outro banco: '+label} required maxLength={160} disabled={busy} value={details[key+'_other']||''} onChange={e=>setDetail(key+'_other',e.target.value)} placeholder="Nome do banco / financeira"/>}</label>;
 const investorSelect=(trade:boolean)=>{const key=trade?'trade_investor_id':'investor_id',nameKey=trade?'trade_investor_name':'investor_name',legacy=details[nameKey]&&!details[key];return <label>{trade?'Investidor que recebe a troca':'Investidor do carro vendido'}<select aria-label={trade?'Investidor que recebe a troca':'Investidor do carro vendido'} required disabled={busy} value={details[key]||(legacy?'LEGACY':'')} onChange={e=>{const i=investors.find(x=>x.id===e.target.value);setDetails(d=>({...d,[key]:i?.id||'',[nameKey]:i?.name||''}));}}><option value="">Selecione o investidor cadastrado</option>{legacy&&<option value="LEGACY">{details[nameKey]} · registro anterior</option>}{investors.filter(i=>i.active).map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select><small>Selecione o mesmo investidor nas duas partes quando ele também receber a troca.</small><a href={bankPath('/administrativo/investidores')} target="_blank" rel="noreferrer">Cadastrar investidor</a><button type="button" disabled={busy} onClick={()=>setInvestorRetry(x=>x+1)}>Atualizar investidores</button>{investorError&&<span className="bank-error" role="alert">{investorError}</span>}</label>;};
 const returnValue=()=>{try{return adminMoneyInput(value||'0')-adminMoneyInput(details.tax_cents||'0')-adminMoneyInput(details.manager_cents||'0')-adminMoneyInput(details.seller_cents||'0');}catch{return null;}};
 async function submit(e:FormEvent){e.preventDefault();if(busy)return;setError('');let input;
  try{const payload:Record<string,unknown>={notes:details.notes||'',payment_method:details.payment_method||'',...(scope==='PESSOAL'?{...expenseContext(description,personalCategory(category,description)),...(details.expense_audience?{expense_audience:details.expense_audience}:{}),...(details.expense_nature?{expense_nature:details.expense_nature}:{}),...(details.trip_name?{trip_name:details.trip_name}:{})}:{})};for(const f of fields[kind]){const v=details[f.key]||'';if(f.money)payload[f.key]=adminMoneyInput(v||'0');else if(f.number){if(v)payload[f.key]=Number(v);}else payload[f.key]=f.key==='plate'?v.replace(/[^a-z0-9]/gi,'').toUpperCase():v;}
   const sale=kind==='VENDA'?adminSaleCalculation(details):null;
   if(vehicle&&(kind!=='CUSTO'||withVehicle))payload.vehicle_spec=vehicle;
   if(details.stock_id)payload.stock_id=details.stock_id;
   if(kind==='CUSTO'&&details.sale_cost_id)Object.assign(payload,{sale_cost_id:details.sale_cost_id,settlement_part:details.settlement_part});
   if(sale){if(!details.sale_owner)throw new Error('Selecione se o carro vendido é da loja ou do investidor.');Object.assign(payload,{sale_owner:details.sale_owner,investor_name:details.investor_name||'',sale_mode:details.sale_mode||'NORMAL',...(details.trade_in==='true'?{trade_destination:details.trade_destination||'',trade_investor_name:details.trade_investor_name||''}:{})});}
   if(sale){if(details.sale_owner==='INVESTIDOR'&&details.investor_id)payload.investor_id=details.investor_id;if(details.trade_in==='true'&&details.trade_destination==='INVESTIDOR'&&details.trade_investor_id)payload.trade_investor_id=details.trade_investor_id;}
   if(sale)Object.assign(payload,tradePayload(),{...(details.trade_in==='true'&&tradeVehicle?{trade_spec:tradeVehicle}:{}),payment_bank:details.payment_bank||'',payment_bank_other:details.payment_bank_other||''});
   const remaining=sale?adminSaleSettlement(sale.sale,payload as AdminDetails).remaining:0;
   input=adminInput({id,kind,scope,entry_date:date,description:kind==='VENDA'?('Venda de veículo · '+(details.vehicle||'')).slice(0,160):description,category:kind==='VENDA'?'Venda de veículo':category,status,amount_cents:sale?adminSaleReceived(remaining,receipt,value):value.trim()?adminMoneyInput(value):null,details:payload,expected_updated_at:entry?.updated_at||null});
  }catch(e){setError(e instanceof Error?e.message:'Confira os campos.');return;}
  setBusy(true);try{const r=await fetch(bankPath('/api/administrative'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)}),data=await r.json() as {row?:AdminEntry;error?:string};if(!r.ok||!data.row)throw new Error(data.error||'Não foi possível salvar.');onSaved(data.row);}catch(e){setError(e instanceof Error?e.message:'Não foi possível confirmar o salvamento. Tente novamente nesta mesma tela.');}finally{setBusy(false);}
 }
 return <section data-bank-manual-view={kind==='VENDA'?'venda_form':kind==='PESSOAL'?'despesa_pessoal_form':kind==='CUSTO'?'despesa_loja_form':'lancamento_form'} className="bank-panel bank-admin-form" id="admin-form"><h2>{kind==='VENDA'?(details.sale_mode==='REPASSE'?'1. Repasse de veículo':'1. Venda de veículo'):entry?'Editar lançamento':'Novo lançamento'}</h2><form onSubmit={submit}>
  {details.stock_id&&<p className="bank-note">Veículo vinculado ao estoque · {details.plate}. {kind==='VENDA'?'Compra e preparação vêm do estoque e serão conferidas ao salvar.':''}</p>}
  {fields[kind].some(f=>f.key==='vehicle')&&<>
   {kind==='CUSTO'&&!details.stock_id&&<label className="bank-checkbox"><input type="checkbox" checked={withVehicle} disabled={busy} onChange={e=>{setWithVehicle(e.target.checked);if(!e.target.checked){setVehicle(undefined);setDetails(d=>({...d,vehicle:'',plate:''}));}}}/>Relacionar este custo a um veículo</label>}
   {(kind!=='CUSTO'||withVehicle)&&<BankVehiclePicker label={kind==='TROCA'?'Veículo da troca':'Marca, modelo e versão'} disabled={busy||!!details.stock_id} value={vehicle} onChange={v=>{setVehicle(v);setDetails(d=>({...d,vehicle:(v.brand+' '+(v.version||v.model)).trim().slice(0,160)}));}}/>}
  </>}
  {kind==='VENDA'&&<div className="bank-admin-sale-step"><h3>{details.sale_mode==='REPASSE'?'Repasse do carro recebido':'Quem é o dono do carro vendido?'}</h3><div className="bank-form-grid"><label>Dono do carro vendido<select required disabled={busy||!!details.stock_id} value={details.sale_owner||''} onChange={e=>setDetail('sale_owner',e.target.value)}><option value="">Selecione para liberar o saldo corretamente</option><option value="LOJA">Loja · ICOM Motors</option><option value="INVESTIDOR">Investidor · loja fica com o lucro</option></select></label>{details.sale_owner==='INVESTIDOR'&&investorSelect(false)}</div><p className="bank-note">O destino da troca é separado do dono deste carro. Dinheiro do investidor fica reservado e não aparece como saldo livre.</p></div>}
  {kind==='CUSTO'&&!details.stock_id&&<div className="bank-admin-sale-step"><h3>Esta saída pertence a uma venda?</h3><div className="bank-form-grid"><label>Venda vinculada<select disabled={busy} value={details.sale_cost_id||''} onChange={e=>{setDetail('sale_cost_id',e.target.value);setDetail('settlement_part',e.target.value?'CUSTOS':'');}}><option value="">Não · despesa geral da loja</option>{entries.filter(x=>x.active&&x.kind==='VENDA'&&x.status==='REALIZADO').map(x=><option key={x.id} value={x.id}>{x.details.plate||x.description} · {x.entry_date.split('-').reverse().join('/')}</option>)}</select></label>{details.sale_cost_id&&<label>Finalidade da saída<select required disabled={busy} value={details.settlement_part||''} onChange={e=>setDetail('settlement_part',e.target.value)}><option value="CUSTOS">Pagar custos / vendedor já incluídos no lucro</option>{entries.find(x=>x.id===details.sale_cost_id)?.details.sale_owner==='INVESTIDOR'&&<option value="INVESTIDOR">Pagar valor reservado ao investidor</option>}{entries.find(x=>x.id===details.sale_cost_id)?.details.sale_mode==='REPASSE'&&<option value="CAPITAL">Retirar capital reservado do repasse</option>}</select></label>}</div><p className="bank-note">Em venda de investidor, um custo pago pela loja em nome dele abate o valor a devolver, sem descontar novamente o lucro líquido. IPVA, multas e quitação devem ser baixados em Contas a pagar.</p></div>}
  <div className="bank-form-grid">
   <label>Área<select value={kind} disabled={busy||!!entry||!!preset.stock} onChange={e=>changeKind(e.target.value as AdminKind)}>{kinds.map(k=><option key={k.value} value={k.value}>{k.label}</option>)}</select></label>
   <label>{kind==='MENSAL'?'Vencimento / mês de referência':kind==='VENDA'?'Data da venda':'Data do lançamento'}<input required type="date" value={date} min="2000-01-01" max="2100-12-31" disabled={busy} onChange={e=>setDate(e.target.value)}/></label>
   {kind!=='VENDA'&&<><label>Descrição<input required minLength={2} maxLength={160} value={description} disabled={busy} onChange={e=>setDescription(e.target.value)} placeholder="Ex.: aluguel ou recebimento"/></label>
   <label>Categoria{scope==='PESSOAL'?<select required value={personalCategory(category,description)} disabled={busy} onChange={e=>setCategory(e.target.value)}><option value="">Selecione a categoria</option>{category&&!personalCategories.includes(personalCategory(category,description) as typeof personalCategories[number])&&<option>{category}</option>}{personalCategories.map(c=><option key={c}>{c}</option>)}</select>:kind==='CUSTO'?<select value={category} onChange={e=>setCategory(e.target.value)} disabled={busy}><option value="">Selecione</option>{['Custos loja','Custos variáveis','Pós-venda'].map(c=><option key={c}>{c}</option>)}</select>:<input value={category} maxLength={80} disabled={busy} onChange={e=>setCategory(e.target.value)} placeholder="Ex.: aluguel, cartão, manutenção"/>}</label></>}
   <label>Escopo<select required value={scope} disabled={busy||kind!=='MENSAL'} onChange={e=>setScope(e.target.value as AdminScope)}><option value="">Selecione Loja ou Pessoal</option><option value="LOJA">Loja</option><option value="PESSOAL">Pessoal</option></select></label>
   {scope==='PESSOAL'&&<><label>Contexto do gasto<select value={details.expense_audience||expenseContext(description,personalCategory(category,description)).expense_audience} disabled={busy} onChange={e=>setDetail('expense_audience',e.target.value)}>{expenseAudiences.map(a=><option key={a} value={a}>{audienceLabel(a)}</option>)}</select></label><label>Classificação do gasto<select value={details.expense_nature||expenseContext(description,personalCategory(category,description)).expense_nature} disabled={busy} onChange={e=>setDetail('expense_nature',e.target.value)}>{expenseNatures.map(a=><option key={a} value={a}>{natureLabel(a)}</option>)}</select><small>Ajustável. Restaurante e compras sem contexto não são considerados opcionais automaticamente.</small></label></>}
   {scope==='PESSOAL'&&<label>Viagem (opcional)<input list="personal-trip-names" maxLength={80} value={details.trip_name||''} disabled={busy} onChange={e=>setDetail('trip_name',e.target.value)} placeholder="Ex.: Disney 2026"/><datalist id="personal-trip-names">{[...new Set(entries.filter(e=>e.active&&e.scope==='PESSOAL').map(e=>e.details.trip_name).filter(Boolean))].map(n=><option key={n} value={n}/>)}</datalist><small>Use o mesmo nome em todos os gastos da viagem. A categoria continua separada.</small></label>}
   <label>Situação<select value={status} disabled={busy} onChange={e=>setStatus(e.target.value as 'PREVISTO'|'REALIZADO')}><option value="PREVISTO">Previsto / ainda não realizado</option><option value="REALIZADO">Realizado / pago ou recebido</option></select></label>
   {!['TROCA','VENDA'].includes(kind)&&<label>{kind==='RETORNO'?'Retorno bruto recebido (valor conta)':'Valor em reais'}<MoneyField value={value} disabled={busy} onChange={setValue}/><small>{kind==='MENSAL'?'Pode deixar sem valor quando a planilha indicar apenas “OK”. O total ficará sinalizado como incompleto.':'Digite o valor em reais. Ao sair do campo, ele aparece como 1.250,00.'}</small></label>}
   {fields[kind].filter(f=>f.key!=='vehicle').map(f=><label key={f.key}>{details.sale_mode==='REPASSE'&&f.key==='sale_cents'?'Valor pelo qual repassou':f.label}{f.money?<MoneyField required={f.required} disabled={busy} readOnly={kind==='VENDA'&&(f.key==='commission_cents'||!!details.stock_id&&['purchase_cents','vehicle_cost_cents'].includes(f.key))} value={details[f.key]||''} onChange={v=>setDetails(d=>({...d,[f.key]:v}))}/>:f.key==='seller'?<select value={details.seller||''} disabled={busy} onChange={e=>setDetails(d=>({...d,seller:e.target.value}))}><option value="">Selecione o vendedor</option>{details.seller&&!sellers.some(s=>s.name===details.seller)&&<option value={details.seller}>{details.seller} (registro anterior)</option>}{sellers.map(s=><option key={s.id} value={s.name}>{s.name}</option>)}</select>:<input required={f.required} disabled={busy} type={f.number?'number':'text'} min={f.number?1:undefined} max={f.key==='return_level'?3:f.key==='due_day'?31:undefined} maxLength={f.key==='plate'?9:160} value={details[f.key]||''} onChange={e=>setDetails(d=>({...d,[f.key]:e.target.value}))}/>}<small>{details.sale_mode==='REPASSE'&&f.key==='commission_cents'?'Repasse sem o custo fixo de R$ 1.650,00.':f.help|| (f.key==='seller'?'Mesmos vendedores cadastrados na Experiência ICOM.':'')}</small></label>)}
   {!['TROCA','RETORNO','VENDA'].includes(kind)&&<label>Forma de pagamento / recebimento<input maxLength={160} value={details.payment_method||''} disabled={busy} onChange={e=>setDetail('payment_method',e.target.value)}/></label>}
  </div>
  {kind==='VENDA'&&<>
   <div className="bank-admin-sale-step"><h3>2. Troca recebida</h3><label>Recebeu um carro na troca?<select disabled={busy||details.sale_mode==='REPASSE'} value={details.trade_in||'false'} onChange={e=>setDetail('trade_in',e.target.value)}><option value="false">Não</option><option value="true">Sim</option></select></label>
   {details.trade_in==='true'&&<div className="bank-form-grid bank-admin-trade-fields">
    <div className="bank-grid-wide"><BankVehiclePicker label="Carro recebido na troca" disabled={busy} value={tradeVehicle} onChange={v=>{setTradeVehicle(v);setDetails(d=>({...d,trade_vehicle:(v.brand+' '+(v.version||v.model)).trim().slice(0,160),trade_year:v.year===null?'':String(v.year)}));}}/></div>
    <label>Quem fica com o carro da troca?<select required disabled={busy} value={details.trade_destination||''} onChange={e=>setDetail('trade_destination',e.target.value)}><option value="">Selecione o destino</option>{Object.entries(tradeDestinations).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>{details.trade_destination==='INVESTIDOR'&&investorSelect(true)}{details.trade_destination==='REPASSE'&&<p className="bank-note bank-grid-wide">Depois de salvar, abra Veículos, marque a troca como Disponível e clique em Registrar repasse para informar por quanto ela saiu.</p>}
    <label>Placa do carro da troca<input required maxLength={9} disabled={busy} value={details.trade_plate||''} onChange={e=>setDetail('trade_plate',e.target.value)}/></label>
    <label>Valor acordado da troca antes dos débitos<MoneyField required disabled={busy} value={details.trade_value_cents||''} onChange={v=>setDetail('trade_value_cents',v)}/><small>Valor negociado pelo carro. Os débitos serão descontados abaixo.</small></label>
    <label>O carro da troca tem débitos?<select disabled={busy} value={details.trade_has_debts||'false'} onChange={e=>setDetail('trade_has_debts',e.target.value)}><option value="false">Não</option><option value="true">Sim</option></select></label>
    {details.trade_has_debts==='true'&&<>
     <label>IPVA em aberto<MoneyField required disabled={busy} value={details.trade_ipva_cents||''} onChange={v=>setDetail('trade_ipva_cents',v)}/></label>
     <label>Multas em aberto<MoneyField required disabled={busy} value={details.trade_fines_cents||''} onChange={v=>setDetail('trade_fines_cents',v)}/></label>
     <label>Tem financiamento para quitar?<select disabled={busy} value={details.trade_has_payoff||'false'} onChange={e=>setDetail('trade_has_payoff',e.target.value)}><option value="false">Não</option><option value="true">Sim</option></select></label>
     {details.trade_has_payoff==='true'&&<><label>Valor da quitação<MoneyField required disabled={busy} value={details.trade_payoff_cents||''} onChange={v=>setDetail('trade_payoff_cents',v)}/></label>{bankSelect('trade_payoff_bank','Banco da quitação')}</>}
    </>}
   </div>}</div>
   <div className="bank-admin-sale-step"><h3>3. Pagamento da diferença</h3>
    {settlement?<div className="bank-admin-settlement" aria-live="polite"><div><span>Valor da troca</span><strong>{currency(settlement.trade)}</strong></div><div><span>− Débitos (IPVA + multas + quitação)</span><strong>{currency(settlement.debt)}</strong></div><div><span>Troca líquida que abate a venda</span><strong>{currency(settlement.credit)}</strong></div><div className="bank-admin-difference"><span>Restante a pagar</span><strong>{currency(settlement.remaining)}</strong></div></div>:<p className="bank-error" role="alert">{settlementError||calculationError}</p>}
    <div className="bank-form-grid"><label>Forma de pagamento da diferença<select required disabled={busy} value={details.payment_method||''} onChange={e=>setDetail('payment_method',e.target.value)}><option value="">Selecione</option><option value="PIX">Pix / à vista</option><option value="DINHEIRO">Dinheiro / à vista</option><option value="CARTAO">Cartão</option><option value="FINANCIAMENTO">Financiamento</option>{settlement?.remaining===0&&<option value="SEM_DIFERENCA">Sem diferença a pagar</option>}{details.payment_method&&!['PIX','DINHEIRO','CARTAO','FINANCIAMENTO','SEM_DIFERENCA'].includes(details.payment_method)&&<option value={details.payment_method}>{details.payment_method} (anterior; selecione uma opção acima)</option>}</select></label>
    {details.payment_method==='FINANCIAMENTO'&&bankSelect('payment_bank','Banco do financiamento')}
    <label>Recebimento da diferença<select value={receipt} disabled={busy} onChange={e=>setReceipt(e.target.value as SaleReceipt)}><option value="INTEGRAL">Diferença toda recebida</option><option value="PARCIAL">Recebido só uma parte</option><option value="PENDENTE">Ainda não recebi</option></select><small>{receipt==='INTEGRAL'?'Registra só o restante a pagar como dinheiro recebido.':receipt==='PENDENTE'?'Registra R$ 0,00 recebido.':'Informe apenas o dinheiro que já entrou.'}</small></label>
    {receipt==='PARCIAL'&&<label>Valor já recebido<MoneyField required value={value} disabled={busy} onChange={setValue}/></label>}</div>
    <p className="bank-note">O carro da troca não é entrada de dinheiro. Marque recebido somente depois de confirmar o crédito do Pix, cartão ou banco. Os débitos ficam registrados; a baixa deles será feita quando você registrar o pagamento.</p>
   </div>
  </>}
  {kind==='VENDA'&&(calculation?<div className="bank-admin-sale-breakdown" aria-live="polite"><h3>Como chegamos ao lucro</h3><dl><div><dt>Compra do veículo</dt><dd>{currency(calculation.purchase)}</dd></div><div><dt>+ Custos adicionais</dt><dd>{currency(calculation.cost)}</dd></div><div><dt>+ Custo do vendedor</dt><dd>{currency(calculation.commission)}</dd></div><div className="bank-admin-total"><dt>Custo total</dt><dd>{currency(calculation.total)}</dd></div><div><dt>Valor da venda</dt><dd>{currency(calculation.sale)}</dd></div><div className={'bank-admin-total '+(calculation.profit<0?'bank-admin-negative':'bank-admin-positive')}><dt>Lucro da venda</dt><dd>{currency(calculation.profit)}</dd></div></dl><p>Lucro = venda − compra − custos adicionais − custo do vendedor. Preencha custos adicionais com os gastos separados da compra.</p><p>O recebimento controla o que entrou no caixa. Ele não altera o lucro desta venda. Lançamentos previstos ficam fora dos totais realizados.</p></div>:<p className="bank-error" role="alert">{calculationError} O cálculo será exibido quando os valores estiverem corretos.</p>)}
  {kind==='VENDA'&&calculation&&settlement&&details.sale_owner&&(()=>{const d={...tradePayload(),stock_id:details.stock_id,sale_owner:details.sale_owner,investor_id:details.investor_id,trade_investor_id:details.trade_investor_id,investor_name:details.investor_name,trade_destination:details.trade_destination,trade_investor_name:details.trade_investor_name,sale_mode:details.sale_mode,purchase_cents:calculation!.purchase,vehicle_cost_cents:calculation!.cost,commission_cents:calculation!.commission,sale_cents:calculation!.sale} as AdminDetails;let received=0;try{received=status==='REALIZADO'?adminSaleReceived(settlement!.remaining,receipt,value):0;}catch{return null;}const current={id,kind:'VENDA',scope:'LOJA',entry_date:date,description:'Prévia',category:'',status,amount_cents:received,details:d,active:true,created_at:'',updated_at:'',cash_stock_origin_id:preset.stock?.origin_entry_id||(entry as import('@/lib/icom-bank/cash').CashEntry|undefined)?.cash_stock_origin_id} as AdminEntry;const cash=saleCash(current,entries);return <div className="bank-admin-sale-step bank-cash-preview"><h3>Como este dinheiro fica separado</h3><div className="bank-stock-finance"><div><span>Dinheiro recebido nesta venda</span><strong>{currency(cash.received)}</strong></div><div><span>Valor a devolver ao investidor</span><strong>{currency(cash.investor)}</strong></div>{details.sale_mode==='REPASSE'&&<div><span>Capital reservado do repasse</span><strong>{currency(cash.capital)}</strong></div>}{cash.costs>0&&<div><span>Débitos / custos ainda reservados</span><strong>{currency(cash.costs)}</strong></div>}<div><span>{details.sale_owner==='INVESTIDOR'?'Lucro líquido disponível da loja':'Parte disponível da loja'}</span><strong>{currency(cash.available)}</strong></div></div><p className="bank-note">{details.sale_owner==='INVESTIDOR'?'O lucro acima já é líquido. O restante do dinheiro recebido fica reservado ao investidor; custos pagos pela loja em nome dele abatem essa devolução. Recebimentos parciais reservam primeiro o valor do investidor. ':''}Prévia da venda. O saldo geral também considera as outras entradas e saídas. Reserva é separação do dinheiro, não uma transferência bancária.</p></div>;})()}
  {kind==='RETORNO'&&<p className="bank-note">Loja após imposto e repasses informados: <strong>{returnValue()===null?'Confira os valores':currency(returnValue()!)}</strong>. Os repasses são manuais; a divisão da sua planilha ainda será confirmada.</p>}
  {kind==='TROCA'&&<p className="bank-note">A troca controla os valores do veículo. Divisão e lucro por pessoa são manuais. Para movimentar o caixa, registre a entrada ou o custo correspondente em sua área própria.</p>}
  {kind==='ENTRADA'&&<p className="bank-note">Registre aqui receitas que ainda não foram incluídas como recebido de uma venda ou retorno. Assim você evita contar a mesma entrada duas vezes.</p>}
  <label>Observações<textarea maxLength={2000} rows={3} disabled={busy} value={details.notes||''} onChange={e=>setDetails(d=>({...d,notes:e.target.value}))}/></label>
  {error&&<p className="bank-error" role="alert">{error}</p>}
  <div className="bank-actions"><button type="button" disabled={busy} onClick={onCancel}>Cancelar</button><button className="bank-primary" disabled={busy}>{busy?'Salvando…':'SALVAR LANÇAMENTO'}</button></div>
 </form></section>;
}
