'use client';
import BankCashPosition from './BankCashPosition';
import BankFinancialNavigation from './BankFinancialNavigation';
import {useEffect,useRef,useState} from 'react';
import BankReceivableForm,{receiptMethodLabels} from './BankReceivableForm';
import {bankPath,brazilDay,currency} from '@/lib/icom-bank/model';
import {adminStats} from '@/lib/icom-bank/administrative';
import {addPayableDays,type AgendaView} from '@/lib/icom-bank/payables';
import {receivableKinds,receivableRemaining,receivableState,receivableStats,receivableMatches,saleOutstanding,type Receivable,type ReceivableHistory,type ReceivablesData} from '@/lib/icom-bank/receivables';
const day=(d:string|null)=>d?d.split('-').reverse().join('/'):'A definir';
const labels:Record<AgendaView,string>={attention:'Prioridades · atrasadas e próximos 7 dias',overdue:'Em atraso',today:'Vencem hoje',week:'Próximos 7 dias',month:'Vencimentos do mês',day:'Uma data específica',all:'Todas as contas ativas',paid:'Recebimentos no mês',archived:'Arquivadas'};
export default function BankReceivables({initial}:{initial:ReceivablesData}){
 const today=brazilDay(),[data,setData]=useState(initial),[month,setMonth]=useState(today.slice(0,7)),[kind,setKind]=useState('all'),[view,setView]=useState<AgendaView>('attention'),[date,setDate]=useState(today),[search,setSearch]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[form,setForm]=useState<{id:string;action:'save'|'receive'|'reverse';receipt?:string}|null>(null),[archive,setArchive]=useState<Receivable|null>(null),[history,setHistory]=useState<{id:string;rows:ReceivableHistory[]}|null>(null);
 useEffect(()=>{const c=new AbortController();const reload=()=>{void fetch(bankPath('/api/receivables'),{cache:'no-store',signal:c.signal}).then(async r=>{const value=await r.json() as ReceivablesData&{error?:string};if(!r.ok)throw new Error(value.error||'Não foi possível atualizar a lista.');return value;}).then(setData).catch(e=>{if(!c.signal.aborted)setError(e.message);});};window.addEventListener('icom-bank-ledger-changed',reload);return()=>{c.abort();window.removeEventListener('icom-bank-ledger-changed',reload);};},[]);
 const anchor=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(form||archive||history)anchor.current?.scrollIntoView({behavior:'smooth',block:'start'});},[form,archive,history]);
 const sources=new Map(data.entries.map(e=>[e.id,e])),sourceOf=(r:Receivable)=>r.source_entry_id?sources.get(r.source_entry_id):undefined,scoped=data.rows.filter(r=>kind==='all'||r.kind===kind),stats=receivableStats(scoped,data.entries,data.receipts,month,today),cash=adminStats(data.entries,month),selected=form&&data.rows.find(r=>r.id===form.id),receipt=form?.receipt?data.receipts.find(p=>p.id===form.receipt):undefined;
 const legacy=data.entries.filter(e=>e.active&&e.kind==='VENDA'&&saleOutstanding(e)===null);
 const list=scoped.filter(r=>receivableMatches(r,sourceOf(r),view,month,date,today,data.receipts)&&(!search||`${r.title} ${r.payer} ${r.bank} ${r.notes} ${sourceOf(r)?.details.plate||''} ${sourceOf(r)?.details.vehicle||''}`.toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR')))).sort((a,b)=>(a.due_date||'9999').localeCompare(b.due_date||'9999')||a.title.localeCompare(b.title));
 function close(){setForm(null);setArchive(null);setHistory(null);}
 async function refresh(message=''){setBusy(true);setError('');try{const r=await fetch(bankPath('/api/receivables')),v=await r.json() as ReceivablesData&{error?:string};if(!r.ok||!Array.isArray(v.rows))throw new Error(v.error||'Não foi possível atualizar.');setData(v);close();if(message)setNotice(message);}catch(e){setError(e instanceof Error?e.message:'Não foi possível atualizar.');}finally{setBusy(false);}}
 async function showHistory(r:Receivable){setBusy(true);setError('');try{const response=await fetch(bankPath('/api/receivables?id='+r.id)),v=await response.json() as {history:ReceivableHistory[];error?:string};if(!response.ok)throw new Error(v.error||'Não foi possível abrir o histórico.');close();setHistory({id:r.id,rows:v.history});}catch(e){setError(e instanceof Error?e.message:'Não foi possível abrir.');}finally{setBusy(false);}}
 async function toggleArchive(r:Receivable){setBusy(true);setError('');try{const response=await fetch(bankPath('/api/receivables'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'archive',id:r.id,active:!r.active,expected_updated_at:r.updated_at})}),v=await response.json() as {error?:string};if(!response.ok)throw new Error(v.error||'Não foi possível atualizar.');await refresh(r.active?'Conta arquivada. Nenhum recebimento foi registrado.':'Conta restaurada.');}catch(e){setError(e instanceof Error?e.message:'Não foi possível atualizar.');}finally{setBusy(false);}}
 function open(id:string,action:'save'|'receive'|'reverse',receipt?:string){close();setForm({id,action,receipt});}
 const cards=[{key:'overdue' as const,label:'EM ATRASO',tone:'red',hint:'Vencimento anterior a hoje'},{key:'today' as const,label:'VENCEM HOJE',tone:'gold',hint:day(today)},{key:'week' as const,label:'PRÓXIMOS 7 DIAS',tone:'navy',hint:`Até ${day(addPayableDays(today,7))}`},{key:'month' as const,label:'A RECEBER NO MÊS',tone:'green',hint:month.split('-').reverse().join('/')}];
 return <><div className="bank-heading"><div><p className="bank-eyebrow">ADMINISTRATIVO · AGENDA DE RECEBIMENTOS</p><h1>Contas a receber</h1><p>Organize os valores de clientes, financiamentos e cartões. Confirme somente o que já entrou.</p></div><span className="bank-pill gold">Saldo pendente: {currency(stats.pending)}</span></div>
 <BankCashPosition entries={data.entries}/><BankFinancialNavigation active="receivables"/>
 <div className="bank-actions"><a href={bankPath('/administrativo')}>← Administrativo</a><button className="bank-primary" disabled={busy} onClick={()=>open('new','save')}>+ Cadastrar conta</button><button disabled={busy} onClick={()=>void refresh()}>Atualizar lista</button></div>
 <div className="bank-agenda-tabs" role="group" aria-label="Quem paga">{[['all','Todas'],['CLIENTE','Clientes'],['BANCO','Financiamentos'],['CARTAO','Cartões']].map(([value,label])=><button key={value} aria-pressed={kind===value} className={kind===value?'bank-agenda-selected':''} onClick={()=>setKind(value)}>{label}</button>)}</div>
 <div className="bank-kpis bank-payable-kpis">{cards.map(c=><button className={'bank-kpi bank-agenda-card '+c.tone} key={c.key} aria-pressed={view===c.key} onClick={()=>setView(c.key)}><span>{c.label}</span><strong>{currency(stats[c.key].amount)}</strong><small>{stats[c.key].count} conta(s) · {c.hint}</small></button>)}</div>
 {stats.overdue.count>0&&<div className="bank-payable-warning bank-agenda-alert" role="status"><strong>Atenção: {stats.overdue.count} conta(s) em atraso · {currency(stats.overdue.amount)}</strong><button onClick={()=>setView('overdue')}>Ver contas atrasadas</button></div>}
 <section className="bank-panel"><div className="bank-panel-title"><div><h2>Agenda dos próximos dias</h2><p>Clique em um dia para ver o saldo que falta receber.</p></div></div><div className="bank-agenda-days">{Array.from({length:8},(_,i)=>addPayableDays(today,i)).map((d,i)=>{const rows=scoped.filter(r=>receivableMatches(r,sourceOf(r),'day',month,d,today)&&receivableState(r,sourceOf(r),today)!=='Origem prevista');return <button key={d} className={view==='day'&&date===d?'bank-agenda-selected':''} onClick={()=>{setDate(d);setView('day');}}><small>{i===0?'HOJE':new Date(d+'T12:00:00Z').toLocaleDateString('pt-BR',{weekday:'short',timeZone:'America/Sao_Paulo'})}</small><strong>{day(d).slice(0,5)}</strong><span>{rows.length} conta(s)</span><b>{currency(rows.reduce((n,r)=>n+receivableRemaining(r),0))}</b></button>;})}</div></section>
 {stats.noDate>0&&<p className="bank-note">{stats.noDate} conta(s) sem vencimento definido. Abra “Editar / vencimento” para incluí-las na agenda.</p>}
 {legacy.length>0&&<details className="bank-panel bank-receivable-legacy"><summary>Vendas anteriores a conferir · {legacy.length}</summary><p>Estas vendas não têm todos os dados de troca e recebimento preenchidos. Confira a origem no Administrativo antes de gerar um saldo a receber.</p>{legacy.map(e=><p key={e.id}><strong>{e.details.plate||e.description}</strong> · {day(e.entry_date)}</p>)}<a href={bankPath('/administrativo')}>Conferir vendas no Administrativo</a></details>}
 {notice&&<p className="bank-note" role="status">{notice}</p>}{error&&<p className="bank-error" role="alert">{error}</p>}
 <div ref={anchor} className="bank-agenda-form-anchor">{form&&(selected||form.id==='new')&&<BankReceivableForm key={form.id+form.action+(selected?.updated_at||'')} bill={selected||undefined} source={selected?sourceOf(selected):undefined} data={data} action={form.action} receipt={receipt} onCancel={close} onSaved={m=>void refresh(m)}/>}
 {archive&&<section className="bank-panel"><h2>{archive.active?'Arquivar':'Restaurar'} · {archive.title}</h2><p>{archive.active?'A conta sairá da agenda ativa. O histórico permanecerá salvo.':'A conta voltará à agenda de recebimentos.'}</p><div className="bank-actions"><button onClick={close}>Cancelar</button><button className="bank-primary" disabled={busy} onClick={()=>void toggleArchive(archive)}>{archive.active?'CONFIRMAR ARQUIVAMENTO':'RESTAURAR CONTA'}</button></div></section>}
 {history&&<section className="bank-panel"><div className="bank-panel-title"><h2>Histórico · {data.rows.find(r=>r.id===history.id)?.title}</h2><button onClick={close}>Fechar histórico</button></div><h3>Recebimentos desta conta</h3>{data.receipts.filter(p=>p.receivable_id===history.id).map(p=><div className="bank-receipt-history-row" key={p.id}><p><strong>{currency(Number(p.amount_cents))}</strong> · {day(p.received_at)} · {receiptMethodLabels[p.method]}<small>{p.active?'Confirmado no caixa':`Desfeito · ${p.reason}`}</small></p>{p.active&&<button disabled={busy} onClick={()=>open(history.id,'reverse',p.id)}>Desfazer recebimento</button>}</div>)}{!data.receipts.some(p=>p.receivable_id===history.id)&&<p>Nenhum recebimento confirmado.</p>}<h3>Alterações da conta</h3><ol className="bank-payable-history">{history.rows.map(h=><li key={h.id}><strong>{h.next.action==='RECEBIMENTO_DESFEITO'?'Correção de recebimento':!h.previous?'Conta registrada':h.previous.active!==h.next.active?(h.next.active?'Conta restaurada':'Conta arquivada'):h.previous.received_cents!==h.next.received_cents?'Saldo recebido atualizado':'Dados / vencimento atualizados'}</strong><small>{new Date(h.created_at).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}</small>{h.next.reason&&<p>{h.next.reason}</p>}{h.next.amount_cents!==undefined&&<p>Valor desta conta: {currency(Number(h.next.amount_cents))} · Recebido: {currency(Number(h.next.received_cents||0))} · Vencimento: {day(h.next.due_date||null)}</p>}</li>)}</ol></section>}</div>
 <section className="bank-panel"><div className="bank-panel-title"><div><h2>{labels[view]}</h2><p>{list.length} conta(s) · por ordem de vencimento</p></div><label>Mês de referência<input type="month" min="2000-01" max="2100-12" value={month} onChange={e=>{if(e.target.value){setMonth(e.target.value);setView('month');}}}/></label></div><div className="bank-filters"><input aria-label="Buscar conta a receber" placeholder="Buscar cliente, banco, conta ou placa" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Mostrar contas a receber" value={view} onChange={e=>setView(e.target.value as AgendaView)}>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>{view==='day'&&<input aria-label="Dia da agenda" type="date" value={date} onChange={e=>setDate(e.target.value)}/>}</div>
 <div className="bank-table bank-admin-sheet"><table><thead><tr><th>Vencimento</th><th>Conta / quem paga</th><th>Valor desta conta</th><th>Recebido</th><th>Saldo pendente</th><th>Situação / ações</th></tr></thead><tbody>{list.map(r=>{const s=sourceOf(r),state=receivableState(r,s,today),canReceive=r.active&&receivableRemaining(r)>0&&(!r.source_entry_id||s?.active&&s.status==='REALIZADO');return <tr key={r.id} className={state==='Em atraso'?'bank-agenda-overdue':state==='Vence hoje'?'bank-agenda-today':''}><td><strong className="bank-agenda-date">{day(r.due_date)}</strong></td><td><strong>{r.title}</strong><small>{receivableKinds[r.kind]}{r.bank?' · '+r.bank:''}</small>{r.payer&&<small>{r.payer}</small>}{s&&<small>{s.details.plate} · Venda em {day(s.entry_date)}<br/>Recebido na venda: {currency(s.status==='REALIZADO'?Number(s.amount_cents):0)} (já abatido)</small>}{r.notes&&<small>{r.notes}</small>}</td><td>{currency(Number(r.amount_cents))}</td><td>{currency(Number(r.received_cents))}<small>Recebimentos posteriores</small></td><td><strong>{currency(receivableRemaining(r))}</strong></td><td><span className={'bank-pill '+(state==='Recebida'?'green':state==='Em atraso'?'red':'gold')}>{state}</span><div className="bank-admin-row-actions">{r.active&&receivableRemaining(r)>0&&<button disabled={busy} onClick={()=>open(r.id,'save')}>Editar / vencimento</button>}{canReceive&&<button className="bank-primary" disabled={busy} onClick={()=>open(r.id,'receive')}>Receber</button>}<button disabled={busy} onClick={()=>void showHistory(r)}>Histórico</button>{!r.source_entry_id&&Number(r.received_cents)===0&&<button disabled={busy} onClick={()=>{close();setArchive(r);}}>{r.active?'Arquivar':'Restaurar'}</button>}</div></td></tr>;})}{!list.length&&<tr><td colSpan={6}>Nenhuma conta neste filtro. Cadastre uma conta ou confira as vendas com saldo pendente.</td></tr>}</tbody></table></div></section>
 <section className="bank-panel bank-payable-cash"><div><span>Confirmado nesta tela · mês</span><strong>{currency(stats.receivedMonth)}</strong></div><div><span>Entradas realizadas da loja · mês</span><strong>{currency(cash.income)}</strong></div><p>Contas pendentes ficam fora do caixa. As entradas realizadas incluem o valor recebido na venda e cada recebimento posterior uma única vez. As parcelas dos contratos continuam na área Parcelas.</p></section>
 </>;
}
