'use client';
import {useEffect,useRef,useState} from 'react';
import {bankPath} from '@/lib/icom-bank/model';
import type {DeletionRequest} from '@/lib/icom-bank/deletion-client';
export function BankDeletionPasswordForm({onSaved}:{onSaved?:(password:string)=>void}){
 const [password,setPassword]=useState(''),[confirmation,setConfirmation]=useState(''),[login,setLogin]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 return <form className="bank-delete-settings" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setNotice('');try{const r=await fetch(bankPath('/api/deletion-security'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password,confirm_password:confirmation,login_password:login})}),d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error||'Não foi possível salvar.');setPassword('');setConfirmation('');setLogin('');setNotice('Senha de exclusão salva.');onSaved?.(password);}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.');}finally{setBusy(false);}}}><p>Esta senha confirma exclusões, cancelamentos e estornos. Para criá-la ou alterá-la, confirme também sua senha de acesso ao IA Bank.</p><label>Nova senha de exclusão<input type="password" autoComplete="new-password" required minLength={8} maxLength={64} disabled={busy} value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Repita a nova senha<input type="password" autoComplete="new-password" required minLength={8} maxLength={64} disabled={busy} value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label><label>Sua senha atual de acesso ao IA Bank<input type="password" autoComplete="current-password" required maxLength={128} disabled={busy} value={login} onChange={e=>setLogin(e.target.value)}/></label><button className="bank-primary" disabled={busy}>{busy?'Salvando…':'SALVAR SENHA DE EXCLUSÃO'}</button>{error&&<p className="bank-error" role="alert">{error}</p>}{notice&&<p className="bank-note" role="status">{notice}</p>}</form>;
}
export default function BankDeletionSecurity(){
 const pending=useRef<DeletionRequest|null>(null),dialog=useRef<HTMLDialogElement>(null),[open,setOpen]=useState(false),[password,setPassword]=useState(''),[status,setStatus]=useState<{configured:boolean;can_configure:boolean}|null>(null),[error,setError]=useState('');
 const finish=(value:string|null)=>{pending.current?.resolve(value);pending.current=null;setPassword('');setOpen(false);setStatus(null);dialog.current?.close();};
 useEffect(()=>{const ask=(event:Event)=>{const request=(event as CustomEvent<DeletionRequest>).detail;if(pending.current){request.resolve(null);return;}pending.current=request;setOpen(true);setPassword('');setError('');setStatus(null);void fetch(bankPath('/api/deletion-security'),{cache:'no-store'}).then(async r=>{const d=await r.json() as {configured:boolean;can_configure:boolean;error?:string};if(!r.ok)throw new Error(d.error||'Não foi possível verificar a proteção.');if(pending.current===request)setStatus(d);}).catch(e=>{if(pending.current===request)setError(e.message);});};window.addEventListener('ia-bank-confirm-deletion',ask);return()=>{window.removeEventListener('ia-bank-confirm-deletion',ask);pending.current?.resolve(null);pending.current=null;};},[]);
 useEffect(()=>{if(open&&!dialog.current?.open)dialog.current?.showModal();},[open]);
 return <dialog className="bank-delete-dialog" ref={dialog} aria-labelledby="bank-delete-title" onCancel={e=>{e.preventDefault();finish(null);}}><h2 id="bank-delete-title">Confirme com sua senha</h2><p>A ação só será concluída após sua confirmação. O histórico ficará preservado.</p>{error&&<p className="bank-error" role="alert">{error}</p>}{!status&&!error&&<p role="status">Verificando a proteção…</p>}{status?.configured&&<form onSubmit={e=>{e.preventDefault();finish(password);}}><label>Senha de exclusão<input type="password" autoComplete="off" autoFocus required minLength={8} maxLength={64} value={password} onChange={e=>setPassword(e.target.value)}/></label><div className="bank-actions"><button type="button" onClick={()=>finish(null)}>Voltar sem excluir</button><button className="bank-primary">CONFIRMAR AÇÃO</button></div></form>}{status&&!status.configured&&(status.can_configure?<><p className="bank-note">Primeiro, crie a senha de exclusão.</p><BankDeletionPasswordForm onSaved={finish}/></>:<p className="bank-note">Peça ao proprietário para cadastrar a senha de exclusão em Configurações.</p>)}{!status?.configured&&<button type="button" onClick={()=>finish(null)}>Voltar sem excluir</button>}</dialog>;
}
