'use client';
import {useState,type ReactNode} from 'react';
import {bankPath,brazilDay,currency} from '@/lib/icom-bank/model';
import {platformSummary,platformCsv,type PlatformData,type PlatformKind} from '@/lib/icom-bank/platform';

const labels:Record<string,string>={PROSPECTO:'Interessado',TESTE:'Em teste',ATIVO:'Ativo',ATRASADO:'Em atraso',CANCELADO:'Cancelado',PENDENTE:'Pendente',CONFIRMADO:'Pago, aguardando liberação',RECEBIDO:'Recebido',ESTORNADO:'Estornado',REVISAO:'Revisar no provedor',MANUAL:'Manual',ASAAS:'Asaas',STRIPE:'Stripe',MERCADO_PAGO:'Mercado Pago',NAO_CONFIGURADO:'Ainda não escolhido',PRODUCTION:'Produção',SANDBOX:'Teste',PREPARANDO:'Preparando loja',ISOLADO_VALIDADO:'Implantação isolada conferida',HOSPEDAGEM:'Hospedagem',WHATSAPP:'WhatsApp',MARKETING:'Marketing',SUPORTE:'Suporte',IMPOSTOS:'Impostos',OUTROS:'Outros',IA:'Inteligência artificial'};
const tabs=[['overview','Visão geral'],['subscribers','Assinantes'],['plans','Planos'],['charges','Cobranças'],['costs','Custos'],['settings','Integração']] as const;
const dateLabel=(v:string|null)=>v?new Date(v+'T12:00:00').toLocaleDateString('pt-BR'):'—';
function Tag({value}:{value:string}){return <span className={'platform-tag tag-'+value.toLowerCase()}>{labels[value]||value}</span>;}
function Field({label,children,hint}:{label:string;children:ReactNode;hint?:string}){return <label className="platform-field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>;}
export default function BankSubscribers({initial}:{initial:PlatformData}){
 const today=brazilDay();const [data,setData]=useState(initial),[tab,setTab]=useState<string>('overview'),[month,setMonth]=useState(today.slice(0,7)),[search,setSearch]=useState(''),[draft,setDraft]=useState<Record<string,unknown>|null>(null),[editing,setEditing]=useState(false),[kind,setKind]=useState<PlatformKind>('subscribers'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[failure,setFailure]=useState('');
 const m=platformSummary(data,month,today),names=new Map(data.subscribers.map(s=>[s.id,s.store_name]));const feeOnly=editing&&kind==='charges'&&['CONFIRMADO','RECEBIDO'].includes(String(draft?.status));
 async function refresh(){const r=await fetch(bankPath('/api/plataforma'),{cache:'no-store'});const body=await r.json() as PlatformData&{error?:string};if(!r.ok)throw new Error(body.error||'Entre novamente para atualizar.');setData(body);}
 async function reload(){setBusy(true);setFailure('');try{await refresh();setMessage('Lista atualizada.');}catch(e){setFailure(e instanceof Error?e.message:'Não foi possível atualizar.');}finally{setBusy(false);}}
 function open(k:PlatformKind,row?:object){setKind(k);setEditing(!!row);setMessage('');setFailure('');const defaults:Record<PlatformKind,Record<string,unknown>>={plans:{name:'',description:'',price_cents:0,cycle_months:1,trial_days:0,enabled:true},subscribers:{store_name:'',contact_name:'',email:'',phone:'',city:'',plan_id:null,price_cents:0,cycle_months:1,status:'PROSPECTO',started_at:today,canceled_at:null,provider:'MANUAL',external_subscription_id:null,deployment_status:'PENDENTE',notes:''},charges:{subscriber_id:'',description:'Assinatura IA Bank Automotive',amount_cents:0,fee_cents:null,due_date:today,status:'PENDENTE',paid_at:null,received_at:null},costs:{description:'',category:'HOSPEDAGEM',amount_cents:0,due_date:today,paid_at:null},settings:{...data.settings}};setDraft(row?{...row}:{...defaults[k],id:crypto.randomUUID()});}
 const put=(k:string,v:unknown)=>setDraft(d=>d?{...d,[k]:v}:d);
 const str=(k:string)=>String(draft?.[k]??'');
 function input(k:string,label:string,type='text',required=false){return <Field label={label}><input type={type} value={str(k)} required={required} maxLength={k==='email'?254:200} onChange={e=>put(k,e.target.value)} max={type==='date'&&['started_at','canceled_at','paid_at','received_at'].includes(k)?today:undefined}/></Field>;}
 function select(k:string,label:string,values:readonly string[]){return <Field label={label}><select value={str(k)} onChange={e=>{put(k,e.target.value);if(k==='status'&&kind==='subscribers')put('canceled_at',e.target.value==='CANCELADO'?today:null);if(k==='status'&&kind==='charges'){put('paid_at',['CONFIRMADO','RECEBIDO'].includes(e.target.value)?today:null);put('received_at',e.target.value==='RECEBIDO'?today:null);}}}>{values.map(v=><option key={v} value={v}>{labels[v]||v}</option>)}</select></Field>;}
 function money(k:string,label:string,nullable=false){return <Field label={label} hint={nullable?'Deixe vazio enquanto a taxa não for conhecida. Zero significa sem taxa.':undefined}><input type="number" inputMode="decimal" step="0.01" min="0" max="1000000" required={!nullable} value={draft?.[k]===null?'':Number(draft?.[k]||0)/100} onChange={e=>put(k,e.target.value===''&&nullable?null:Math.round(Number(e.target.value)*100))}/><small>{draft?.[k]===null?'Taxa ainda não informada':currency(Number(draft?.[k]||0))}</small></Field>;}
 async function submit(e:React.FormEvent){e.preventDefault();if(!draft||busy)return;setBusy(true);setFailure('');try{const r=await fetch(bankPath('/api/plataforma'),{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,id:String(draft.id),...(editing?{updated_at:draft.updated_at}:{}),payload:draft})});const b=await r.json() as {error?:string};if(!r.ok)throw new Error(b.error||'Confira os campos.');setDraft(null);setMessage('Registro salvo.');await refresh();}catch(e){setFailure(e instanceof Error?e.message:'Não foi possível salvar.');}finally{setBusy(false);}}
 function exportRows(rows:Record<string,unknown>[],name:string){if(!rows.length){setMessage('Ainda não há dados para exportar.');return;}const url=URL.createObjectURL(new Blob([platformCsv(rows)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const history=Array.from({length:6},(_,i)=>{const d=new Date(month+'-01T12:00:00Z');d.setUTCMonth(d.getUTCMonth()-i);const key=d.toISOString().slice(0,7);const s=platformSummary(data,key,today);return {Mês:key,Recebido:s.gross/100,Taxas:s.fees/100,Estornos:s.refund/100,Custos:s.cost/100,Resultado:s.result/100,'Taxas pendentes':s.unknownFees};});
 const filtered=data.subscribers.filter(s=>(s.store_name+' '+s.contact_name+' '+s.email).toLowerCase().includes(search.toLowerCase()));
 return <section className="platform-control">
  <div className="platform-hero"><div><span className="platform-eyebrow">IA BANK AUTOMOTIVE · CONTROLE PRIVADO</span><h1>Seu negócio de assinaturas</h1><p>Acompanhe as lojas, os recebimentos e o resultado da plataforma.</p></div><div className="platform-actions"><span className="platform-private">◈ Só você tem acesso</span><button type="button" disabled={busy} onClick={()=>void reload()}>Atualizar lista</button></div></div>
  <div className="platform-notice"><strong>Finanças separadas.</strong> Estes números são da venda do IA Bank. As vendas de carros e os saldos da Icom continuam na área administrativa.</div>
  <nav className="platform-tabs" aria-label="Controle de assinantes">{tabs.map(([id,label])=><button type="button" key={id} className={tab===id?'active':''} aria-current={tab===id?'page':undefined} onClick={()=>{setTab(id);setDraft(null);setFailure('');}}>{label}</button>)}</nav>
  {message&&<p className="platform-success" role="status">{message}</p>}{failure&&<p className="platform-error" role="alert">{failure}</p>}
  {draft&&<section className="bank-panel platform-editor" aria-label="Cadastro"><div className="platform-section-title"><h2>{editing?'Editar':'Cadastrar'} {kind==='subscribers'?'assinante':kind==='plans'?'plano':kind==='charges'?'cobrança':kind==='costs'?'custo':'integração'}</h2><button type="button" disabled={busy} onClick={()=>setDraft(null)}>Fechar</button></div>
   <form onSubmit={submit}><div className="platform-form-grid">
   {kind==='plans'&&<>{input('name','Nome do plano','text',true)}{money('price_cents','Preço por cobrança') }<Field label="Recorrência"><select value={str('cycle_months')} onChange={e=>put('cycle_months',Number(e.target.value))}><option value="1">Mensal</option><option value="12">Anual</option></select></Field><Field label="Dias de teste"><input type="number" min="0" max="90" required value={str('trial_days')} onChange={e=>put('trial_days',Number(e.target.value))}/></Field><Field label="Disponibilidade"><select value={draft.enabled?'true':'false'} onChange={e=>put('enabled',e.target.value==='true')}><option value="true">Disponível</option><option value="false">Pausado para novas vendas</option></select></Field></>}
   {kind==='subscribers'&&<>{input('store_name','Nome da loja','text',true)}{input('contact_name','Responsável','text',true)}{input('email','E-mail','email',true)}{input('phone','WhatsApp / telefone','tel')}{input('city','Cidade')}<Field label="Plano"><select value={str('plan_id')} onChange={e=>{const p=data.plans.find(p=>p.id===e.target.value);put('plan_id',p?.id||null);if(p){put('price_cents',p.price_cents);put('cycle_months',p.cycle_months);}}}><option value="">Definir depois</option>{data.plans.filter(p=>p.enabled||p.id===draft.plan_id).map(p=><option key={p.id} value={p.id}>{p.name} · {currency(p.price_cents)}</option>)}</select></Field>{money('price_cents','Valor combinado por cobrança')}<Field label="Recorrência"><select value={str('cycle_months')} onChange={e=>put('cycle_months',Number(e.target.value))}><option value="1">Mensal</option><option value="12">Anual</option></select></Field>{select('status','Situação do cadastro',['PROSPECTO','TESTE','ATIVO','ATRASADO','CANCELADO'])}{input('started_at','Data de início','date',true)}{draft.status==='CANCELADO'&&input('canceled_at','Data do cancelamento','date',true)}{select('provider','Provedor de cobrança',['MANUAL','ASAAS','STRIPE','MERCADO_PAGO'])}{input('external_subscription_id','Identificador da assinatura no provedor')}{select('deployment_status','Preparação da loja',['PENDENTE','PREPARANDO','ISOLADO_VALIDADO'])}</>}
   {kind==='charges'&&(feeOnly?<>{money('fee_cents','Taxa conciliada do provedor')}<p className="platform-notice">Altere apenas a taxa. Valor, assinante e datas do pagamento permanecem protegidos.</p></>:<><Field label="Assinante"><select required value={str('subscriber_id')} onChange={e=>{put('subscriber_id',e.target.value);const s=data.subscribers.find(s=>s.id===e.target.value);if(s)put('amount_cents',s.price_cents);}}><option value="">Selecione a loja</option>{data.subscribers.map(s=><option key={s.id} value={s.id}>{s.store_name}</option>)}</select></Field>{input('description','Descrição','text',true)}{money('amount_cents','Valor da cobrança')}{money('fee_cents','Taxa do cartão / provedor',true)}{input('due_date','Vencimento','date',true)}{select('status','Situação do pagamento',['PENDENTE','CONFIRMADO','RECEBIDO','CANCELADO'])}{['CONFIRMADO','RECEBIDO'].includes(str('status'))&&input('paid_at','Quando o cliente pagou?','date',true)}{draft.status==='RECEBIDO'&&input('received_at','Quando o dinheiro ficou disponível?','date',true)}</>)}
   {kind==='costs'&&<>{input('description','Qual foi o custo?','text',true)}{select('category','Categoria',['HOSPEDAGEM','IA','WHATSAPP','MARKETING','SUPORTE','IMPOSTOS','OUTROS'])}{money('amount_cents','Valor')}{input('due_date','Vencimento','date',true)}<Field label="Esse custo já foi pago?"><select value={draft.paid_at?'true':'false'} onChange={e=>put('paid_at',e.target.value==='true'?today:null)}><option value="false">Ainda não</option><option value="true">Sim</option></select></Field>{!!draft.paid_at&&input('paid_at','Data do pagamento','date',true)}</>}
   {kind==='settings'&&<>{select('provider','Provedor escolhido',['NAO_CONFIGURADO','ASAAS','STRIPE','MERCADO_PAGO'])}{select('environment','Ambiente',['SANDBOX','PRODUCTION'])}<Field label="Prazo de tolerância ao atraso (dias)" hint="Registro da sua regra comercial; bloqueio automático ainda não é ativado."><input type="number" min="0" max="30" required value={str('grace_days')} onChange={e=>put('grace_days',Number(e.target.value))}/></Field></>}
   {['plans','subscribers','settings'].includes(kind)&&<Field label={kind==='plans'?'O que está incluído?':'Observações'}><textarea maxLength={kind==='plans'?1000:2000} rows={3} value={str(kind==='plans'?'description':'notes')} onChange={e=>put(kind==='plans'?'description':'notes',e.target.value)}/></Field>}
   </div>{kind==='subscribers'&&<p className="platform-notice">Este cadastro não libera acesso aos dados da Icom. Cada loja precisa de uma implantação isolada. Alterar a situação aqui também não cancela a assinatura no provedor.</p>}{kind==='charges'&&<p className="platform-notice">Registro manual para conferência. Não cobra o cartão do cliente. Depois da confirmação, o registro fica protegido contra alterações.</p>}<button className="platform-primary" disabled={busy}>{busy?'Salvando...':'Salvar registro'}</button></form>
  </section>}
  {tab==='overview'&&<><div className="platform-section-title"><h2>Visão do seu negócio</h2><Field label="Mês do relatório"><input aria-label="Mês do relatório" type="month" min="2000-01" max="2100-12" value={month} onChange={e=>{if(/^\d{4}-\d{2}$/.test(e.target.value))setMonth(e.target.value);}}/></Field></div>
   <div className="platform-kpis">{[['Assinantes ativos',String(m.active),'Situação cadastrada hoje'],['Receita mensal prevista',currency(m.mrr),'MRR · anual dividido por 12'],['Recebido no mês',currency(m.gross),'Dinheiro efetivamente disponível'],[m.allUnknownFees?'Saldo apurado · parcial':'Saldo apurado',currency(m.cash),'Recebimentos menos taxas, estornos e custos']].map(([title,value,hint])=><article key={title}><small>{title}</small><strong>{value}</strong><p>{hint}</p></article>)}</div>
   {!!m.allUnknownFees&&<p className="platform-warning">Há {m.allUnknownFees} recebimento(s) sem taxa informada. O saldo e o resultado ficam parciais até a conciliação dessas taxas.</p>}
   <div className="platform-two"><section className="bank-panel"><h2>Resultado do mês {m.unknownFees>0?'· parcial':''}</h2><dl className="platform-ledger"><div><dt>Recebimentos disponíveis</dt><dd>{currency(m.gross)}</dd></div><div><dt>Taxas conhecidas</dt><dd>− {currency(m.fees)}</dd></div><div><dt>Estornos do mês</dt><dd>− {currency(m.refund)}</dd></div><div><dt>Custos pagos da plataforma</dt><dd>− {currency(m.cost)}</dd></div><div className="total"><dt>Resultado apurado</dt><dd>{currency(m.result)}</dd></div></dl><p className="platform-muted">Receita prevista não entra no caixa. Pagamentos confirmados entram somente após ficarem disponíveis.</p></section>
   <section className="bank-panel"><h2>O que merece atenção</h2><dl className="platform-ledger"><div><dt>Cobranças vencidas em aberto</dt><dd>{currency(m.overdue)}</dd></div><div><dt>Pagamentos aguardando liberação</dt><dd>{currency(m.confirmed)}</dd></div><div><dt>Em teste / interessados</dt><dd>{m.trials} / {m.prospects}</dd></div><div><dt>Cancelamentos da base no mês</dt><dd>{m.canceled}</dd></div><div><dt>Implantações pendentes</dt><dd>{m.setupPending}</dd></div></dl><p className="platform-muted">Valores de teste do provedor ficam identificados e não entram no saldo real.</p></section></div>
   <section className="bank-panel"><div className="platform-section-title"><h2>Histórico dos últimos seis meses</h2><button type="button" onClick={()=>exportRows(history,'ia-bank-assinaturas-'+month)}>Exportar relatório</button></div><div className="platform-table"><table><thead><tr><th>Mês</th><th>Recebido</th><th>Taxas</th><th>Estornos</th><th>Custos</th><th>Resultado</th></tr></thead><tbody>{history.map(h=><tr key={h.Mês}><td>{h.Mês}</td><td>{currency(h.Recebido*100)}</td><td>{currency(h.Taxas*100)}</td><td>{currency(h.Estornos*100)}</td><td>{currency(h.Custos*100)}</td><td>{currency(h.Resultado*100)}{h['Taxas pendentes']>0?' *':''}</td></tr>)}</tbody></table></div><small>* Resultado parcial quando há taxas pendentes.</small></section>
   <section className="bank-panel"><h2>Preparar sua primeira assinatura</h2><ol className="platform-checklist"><li>Cadastre o plano e o preço em <button onClick={()=>setTab('plans')}>Planos</button>.</li><li>Escolha o provedor e configure as credenciais em <button onClick={()=>setTab('settings')}>Integração</button>.</li><li>Valide cartão, atualização dos pagamentos e isolamento de cada loja antes de liberar a venda pela internet.</li></ol></section>
  </>}
  {tab==='subscribers'&&<section className="bank-panel"><div className="platform-section-title"><h2>Suas lojas assinantes <small>({data.subscribers.length})</small></h2><div className="platform-actions"><button type="button" onClick={()=>exportRows(data.subscribers.map(s=>({Loja:s.store_name,Responsável:s.contact_name,Email:s.email,Situação:labels[s.status],Valor:s.price_cents/100,Recorrência:s.cycle_months===12?'Anual':'Mensal',Início:s.started_at,Cancelamento:s.canceled_at||'',Implantação:labels[s.deployment_status]})),'ia-bank-assinantes')}>Exportar</button><button className="platform-primary" onClick={()=>open('subscribers')}>+ Cadastrar assinante</button></div></div><input className="platform-search" aria-label="Buscar assinante" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar loja, responsável ou e-mail"/>
   {!filtered.length?<p className="platform-empty">Nenhum assinante cadastrado nesta busca. Comece pelo plano e cadastre a primeira loja.</p>:<div className="platform-table"><table><thead><tr><th>Loja / responsável</th><th>Plano</th><th>Valor</th><th>Situação</th><th>Implantação</th><th>Ações</th></tr></thead><tbody>{filtered.map(s=><tr key={s.id}><td><strong>{s.store_name}</strong><small>{s.contact_name} · {s.email}</small></td><td>{data.plans.find(p=>p.id===s.plan_id)?.name||'A definir'}</td><td>{currency(s.price_cents)}<small>{s.cycle_months===12?'Anual':'Mensal'}</small></td><td><Tag value={s.status}/></td><td><Tag value={s.deployment_status}/></td><td><button onClick={()=>open('subscribers',s)}>Editar cadastro</button></td></tr>)}</tbody></table></div>}</section>}
  {tab==='plans'&&<section className="bank-panel"><div className="platform-section-title"><h2>Planos e preços</h2><button className="platform-primary" onClick={()=>open('plans')}>+ Criar plano</button></div><p className="platform-muted">Você define os preços. Editar um plano não altera o valor combinado com assinantes já cadastrados.</p>{!data.plans.length?<p className="platform-empty">Defina seu primeiro plano mensal ou anual. Nenhum preço foi presumido.</p>:<div className="platform-plan-grid">{data.plans.map(p=><article key={p.id}><Tag value={p.enabled?'ATIVO':'CANCELADO'}/><h3>{p.name}</h3><strong>{currency(p.price_cents)}<small> / {p.cycle_months===12?'ano':'mês'}</small></strong><p>{p.description||'Descrição ainda não definida.'}</p><p>{p.trial_days?`${p.trial_days} dias de teste`:'Sem período de teste'}</p><button onClick={()=>open('plans',p)}>Editar plano</button></article>)}</div>}</section>}
  {tab==='charges'&&<section className="bank-panel"><div className="platform-section-title"><h2>Cobranças e recebimentos</h2><button className="platform-primary" disabled={!data.subscribers.length} onClick={()=>open('charges')}>+ Registrar cobrança</button></div><p className="platform-muted">Cobrança manual registra a conferência. Cartões são cobrados no provedor escolhido.</p>{!data.charges.length?<p className="platform-empty">Ainda não há cobranças. Cadastre um assinante para iniciar os registros.</p>:<div className="platform-table"><table><thead><tr><th>Loja</th><th>Vencimento</th><th>Valor / taxa</th><th>Situação</th><th>Origem</th><th>Ações</th></tr></thead><tbody>{data.charges.map(c=><tr key={c.id}><td><strong>{names.get(c.subscriber_id)||'Loja'}</strong><small>{c.description}</small></td><td>{dateLabel(c.due_date)}{c.status==='PENDENTE'&&c.due_date<today&&<small className="platform-late">Vencido</small>}</td><td>{currency(c.amount_cents)}<small>Taxa: {c.fee_cents===null?'a conferir':currency(c.fee_cents)}</small></td><td><Tag value={c.status}/>{c.received_at&&<small>Disponível: {dateLabel(c.received_at)}</small>}</td><td><Tag value={c.source}/>{c.environment==='SANDBOX'&&<small>TESTE · fora do saldo</small>}</td><td>{c.source==='MANUAL'&&c.status!=='ESTORNADO'?<button onClick={()=>open('charges',c)}>{['CONFIRMADO','RECEBIDO'].includes(c.status)?'Conferir taxa':'Conferir / editar'}</button>:<small>Histórico protegido</small>}</td></tr>)}</tbody></table></div>}</section>}
  {tab==='costs'&&<section className="bank-panel"><div className="platform-section-title"><h2>Custos para manter o IA Bank</h2><button className="platform-primary" onClick={()=>open('costs')}>+ Registrar custo</button></div><p className="platform-muted">Hospedagem, IA, WhatsApp, suporte e divulgação. Custos da loja de carros continuam no Administrativo.</p>{!data.costs.length?<p className="platform-empty">Nenhum custo da plataforma cadastrado.</p>:<div className="platform-table"><table><thead><tr><th>Descrição</th><th>Categoria</th><th>Valor</th><th>Vencimento</th><th>Pagamento</th><th>Ações</th></tr></thead><tbody>{data.costs.map(c=><tr key={c.id}><td>{c.description}</td><td>{labels[c.category]}</td><td>{currency(c.amount_cents)}</td><td>{dateLabel(c.due_date)}</td><td>{c.paid_at?dateLabel(c.paid_at):'Ainda não pago'}</td><td><button onClick={()=>open('costs',c)}>Conferir / editar</button></td></tr>)}</tbody></table></div>}</section>}
  {tab==='settings'&&<><section className="bank-panel"><div className="platform-section-title"><h2>Recorrência no cartão</h2><button onClick={()=>open('settings',data.settings)}>Configurar preferência</button></div><div className="platform-integration-state"><div><small>Provedor</small><strong>{labels[data.settings.provider]}</strong></div><div><small>Ambiente</small><strong>{labels[data.settings.environment]}</strong></div><div><small>Credenciais Asaas no servidor</small><strong>{data.integration.asaas_ready?'Configuradas · teste pendente':'A configurar'}</strong></div></div>
   <p className="platform-notice">A cobrança automática e o checkout ainda dependem da conta do provedor e da validação de cada loja. Não há cobrança de cartão ativada nesta tela.</p><h3>Minha recomendação para começar: Asaas</h3><p>Boa opção para operação brasileira: assinaturas mensais ou anuais e eventos de pagamento para conciliar seu controle. Stripe e Mercado Pago também oferecem assinaturas.</p><div className="platform-provider-links"><a href="https://docs.asaas.com/docs/assinaturas" target="_blank" rel="noreferrer">Asaas · assinaturas ↗</a><a href="https://docs.stripe.com/billing/subscriptions/overview" target="_blank" rel="noreferrer">Stripe · recorrência ↗</a><a href="https://www.mercadopago.com.br/developers/pt/docs/subscription-plans/overview" target="_blank" rel="noreferrer">Mercado Pago · planos ↗</a></div>
   <details><summary>Como será a integração segura</summary><ol><li>O cliente informa o cartão no checkout seguro do provedor. O IA Bank não armazena número de cartão ou código de segurança.</li><li>O servidor recebe um aviso autenticado e consulta o pagamento no Asaas. Eventos repetidos não duplicam a cobrança.</li><li>“Pagamento confirmado” fica fora do saldo até o dinheiro estar disponível.</li><li>Configure no servidor IABANK_ASAAS_API_KEY e IABANK_ASAAS_WEBHOOK_TOKEN. O token do webhook é um segredo próprio, diferente da chave API.</li><li>Webhook preparado: <code>{bankPath('/api/plataforma/asaas/webhook')}</code></li><li>Cadastre o identificador da assinatura na loja e teste no ambiente de teste. Nenhum cadastro concede acesso ao banco da Icom.</li></ol></details></section>
   <section className="bank-panel"><h2>Últimos eventos de pagamento</h2>{data.events.length?<div className="platform-table"><table><thead><tr><th>Data</th><th>Evento</th><th>Ambiente</th><th>Resultado</th></tr></thead><tbody>{data.events.map(e=><tr key={e.id}><td>{new Date(e.processed_at).toLocaleString('pt-BR')}</td><td>{e.kind}</td><td>{labels[e.environment]}</td><td>{e.outcome==='PROCESSADO'?'Conferido':'Assinatura não vinculada'}</td></tr>)}</tbody></table></div>:<p className="platform-empty">Nenhum evento recebido.</p>}</section>
   <section className="bank-panel"><h2>Histórico de alterações</h2>{data.audit.length?<ul className="platform-audit">{data.audit.slice(0,20).map(a=><li key={a.id}>{new Date(a.created_at).toLocaleString('pt-BR')} · {a.entity.replace('ia_bank_saas_','')} · {a.action==='INSERT'?'Cadastro':'Atualização'}</li>)}</ul>:<p className="platform-empty">Nenhuma alteração registrada.</p>}</section></>}
 </section>;
}
