'use client';
import {useState} from 'react';
import {bankPath,currency,type BankData} from '@/lib/icom-bank/model';
import {stockCosts,stockLabels,type StockRow,type StockState} from '@/lib/icom-bank/stock';
import {saleProfit,type AdminEntry,type AdminSeller} from '@/lib/icom-bank/administrative';
import {brandLabel} from '@/lib/icom-bank/vehicle-catalog';
import BankAdminForm,{type AdminPreset} from './BankAdminForm';
import BankPortfolio from './BankPortfolio';
function StatusForm({row,onSaved}:{row:StockRow;onSaved:()=>void}){
 const [status,setStatus]=useState(row.status),[notes,setNotes]=useState(row.notes),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 return <form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch(bankPath('/api/stock'),{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:row.id,status,notes,expected_updated_at:row.updated_at})});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error||'Não foi possível atualizar.');onSaved();}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.');}finally{setBusy(false);}}}><div className="bank-form-grid"><label>Situação do veículo<select disabled={busy} value={status} onChange={e=>setStatus(e.target.value as StockState)}>{(['AGUARDANDO_QUITACAO','EM_PREPARACAO','DISPONIVEL'] as const).map(s=><option key={s} value={s}>{stockLabels[s]}</option>)}</select></label><label>Observações da preparação<textarea disabled={busy} maxLength={2000} rows={2} value={notes} onChange={e=>setNotes(e.target.value)}/></label></div><button disabled={busy} className="bank-primary">{busy?'Salvando…':'Salvar situação'}</button>{error&&<p role="alert" className="bank-error">{error}</p>}</form>;
}
export default function BankStock({initial,initialEntries,sellers,data}:{initial:StockRow[];initialEntries:AdminEntry[];sellers:AdminSeller[];data:BankData}){
 const [stock,setStock]=useState(initial),[entries,setEntries]=useState(initialEntries),[tab,setTab]=useState<'stock'|'contracts'>('stock'),[filter,setFilter]=useState(''),[search,setSearch]=useState(''),[archived,setArchived]=useState(false),[form,setForm]=useState<{preset:AdminPreset;entry?:AdminEntry}|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function refresh(){try{const r=await fetch(bankPath('/api/stock')),d=await r.json() as {stock:StockRow[];entries:AdminEntry[];error?:string};if(!r.ok)throw new Error(d.error||'Não foi possível atualizar.');setStock(d.stock);setEntries(d.entries);setError('');}catch(e){setError(e instanceof Error?e.message:'Não foi possível atualizar.');}}
 const list=stock.filter(s=>s.active!==archived&&(!filter||s.status===filter)&&(!search||(s.plate+' '+s.vehicle.brand+' '+s.vehicle.model+' '+s.vehicle.version).toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR'))));
 return <><div className="bank-heading"><div><p className="bank-eyebrow">DO RECEBIMENTO À PRÓXIMA VENDA</p><h1>Veículos</h1><p>Acompanhe os carros recebidos na troca, a preparação e o resultado da revenda.</p></div><button type="button" onClick={()=>void refresh()}>Atualizar</button></div>
 <div className="bank-admin-tabs"><button type="button" className={tab==='stock'?'active':''} onClick={()=>{setTab('stock');setForm(null);}}>Carros recebidos na troca</button><button type="button" className={tab==='contracts'?'active':''} onClick={()=>{setTab('contracts');setForm(null);}}>Veículos dos contratos</button></div>
 {tab==='contracts'?<BankPortfolio data={data} section="veiculos"/>:<>
 <section className="bank-panel"><div className="bank-form-grid"><label>Buscar carro / placa<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Marca, modelo ou placa"/></label><label>Filtrar situação<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Todas</option>{Object.entries(stockLabels).map(([s,l])=><option value={s} key={s}>{l}</option>)}</select></label></div><label className="bank-checkbox"><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/>Mostrar veículos com origem arquivada</label><p className="bank-note">Salvar uma venda com troca registra o carro aqui automaticamente. Uma venda prevista gera uma entrada prevista; o carro entra no estoque realizado quando a venda de origem for marcada como realizada.</p></section>
 {error&&<p className="bank-error" role="alert">{error}</p>}{notice&&<p className="bank-note" role="status">{notice}</p>}
 {form&&<BankAdminForm key={form.entry?.id||form.preset.stock?.id+'-'+form.preset.kind} entry={form.entry} preset={form.preset} sellers={sellers} onCancel={()=>setForm(null)} onSaved={()=>{setForm(null);setNotice('Registro salvo. Estoque e custos atualizados.');void refresh();}}/>}
 {!list.length&&<section className="bank-panel bank-empty">Nenhum carro neste filtro. Cadastre a troca ao registrar uma venda no Administrativo.</section>}
 {list.map(s=>{const costs=stockCosts(s,entries),sold=entries.find(e=>e.id===s.sold_entry_id),source=entries.find(e=>e.id===s.origin_entry_id),linked=entries.filter(e=>e.active&&e.details.stock_id===s.id&&e.kind==='CUSTO');return <article className="bank-stock-card" key={s.id}><header><div><h2>{brandLabel(s.vehicle.brand)||'Marca a completar'} {s.vehicle.model}</h2><p>{s.vehicle.version} · {s.vehicle.year||'Ano a completar'} · <strong>{s.plate}</strong></p><small>Recebido em {s.entry_date.split('-').reverse().join('/')} · {source?.description||'Venda de origem'}</small></div><span className={'bank-pill '+(s.status==='DISPONIVEL'?'green':s.status==='VENDIDO'?'':'gold')}>{stockLabels[s.status]}</span></header>
 <div className="bank-stock-finance"><div><span>Valor negociado antes dos débitos</span><strong>{currency(s.purchase_cents)}</strong></div><div><span>Débitos na entrada</span><strong>{currency(s.debt_cents)}</strong></div><div><span>Troca líquida na venda de origem</span><strong>{currency(s.purchase_cents-s.debt_cents)}</strong></div><div><span>Preparação realizada</span><strong>{currency(costs)}</strong></div><div><span>Custo total para revenda</span><strong>{currency(s.purchase_cents+costs)}</strong></div>{sold&&<div><span>Lucro da revenda · inclui custo vendedor</span><strong>{currency(saleProfit(sold))}</strong></div>}{s.vehicle.fipe&&<div><span>FIPE · {s.vehicle.fipe.reference}</span><strong>{currency(s.vehicle.fipe.price_cents)}</strong><small>Código {s.vehicle.fipe.code}</small></div>}</div>
 <p className="bank-note">O custo de aquisição considera o valor negociado antes dos débitos: o crédito líquido mais as obrigações assumidas. IPVA, multas e quitação da entrada já estão nesse custo; não os repita como preparação. A FIPE serve apenas de referência.</p>
 {s.debt_cents>0&&<p>IPVA: {currency(Number(s.source_details.trade_ipva_cents||0))} · Multas: {currency(Number(s.source_details.trade_fines_cents||0))} · Quitação: {currency(Number(s.source_details.trade_payoff_cents||0))} · Banco: {s.source_details.trade_payoff_bank==='OUTRO'?s.source_details.trade_payoff_bank_other:s.source_details.trade_payoff_bank||'—'}</p>}
 <div className="bank-actions">{source&&<button type="button" onClick={()=>setForm({entry:source,preset:{kind:'VENDA'}})}>Ver / editar venda de origem</button>}{s.active&&!['PREVISTO','VENDIDO'].includes(s.status)&&<button type="button" disabled={!s.vehicle.brand} onClick={()=>setForm({preset:{kind:'CUSTO',stock:s,description:'Preparação · '+s.plate,scope:'LOJA',details:{stock_id:s.id,vehicle:s.vehicle.model,plate:s.plate}}})}>+ Custo de preparação</button>}{s.active&&s.status==='DISPONIVEL'&&<button className="bank-primary" disabled={!s.vehicle.brand} type="button" onClick={()=>setForm({preset:{kind:'VENDA',stock:s,details:{stock_id:s.id,purchase_cents:s.purchase_cents,vehicle_cost_cents:costs}}})}>Registrar venda deste carro</button>}{sold&&<a href={bankPath('/administrativo')}>Ver venda no Administrativo</a>}</div>
 {s.active&&!['PREVISTO','VENDIDO'].includes(s.status)&&<StatusForm key={s.updated_at} row={s} onSaved={()=>{setNotice('Situação atualizada.');void refresh();}}/>}
 {!!linked.length&&<details><summary>Custos de preparação ({linked.length})</summary><div className="bank-table"><table><thead><tr><th>Data</th><th>Descrição</th><th>Valor</th><th>Situação</th><th>Ação</th></tr></thead><tbody>{linked.map(e=><tr key={e.id}><td>{e.entry_date.split('-').reverse().join('/')}</td><td>{e.description}</td><td>{currency(Number(e.amount_cents||0))}</td><td>{e.status==='REALIZADO'?'Realizado':'Previsto'}</td><td><button disabled={s.status==='VENDIDO'} type="button" onClick={()=>setForm({entry:e,preset:{kind:'CUSTO',stock:s}})}>Editar</button></td></tr>)}</tbody></table></div></details>}
 </article>;})}</>}
 </>;
}
