'use client';
import {useEffect,useState} from 'react';
import {ArrowUpRight,ArrowDownRight,UserRound,Wallet,Landmark,TrendingUp,Plus,House,Coins} from 'lucide-react';
import {bankPath,brazilDay,currency} from '@/lib/icom-bank/model';
import {financialOverview} from '@/lib/icom-bank/financial-overview';
import type {CashEntry} from '@/lib/icom-bank/cash';
import type {WealthRecord} from '@/lib/icom-bank/personal-wealth';
export default function BankOwnerOverview({initial,personal}:{initial:CashEntry[];personal:WealthRecord[]}){
 const [rows,setRows]=useState(initial),[wealth,setWealth]=useState(personal),[month,setMonth]=useState(brazilDay().slice(0,7)),[all,setAll]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const c=new AbortController();const refresh=()=>{void Promise.all([fetch(bankPath('/api/administrative?year='+brazilDay().slice(0,4)),{signal:c.signal,cache:'no-store'}),fetch(bankPath('/api/personal-wealth'),{signal:c.signal,cache:'no-store'})]).then(async([a,b])=>{const x=await a.json() as {rows?:CashEntry[]},y=await b.json() as {rows?:WealthRecord[]};if(!a.ok||!b.ok)throw new Error('Atualize a página para conferir os dados.');const fresh=x.rows;if(Array.isArray(fresh))setRows(old=>[...old.filter(r=>!r.entry_date.startsWith(brazilDay().slice(0,4))),...fresh]);if(Array.isArray(y.rows))setWealth(y.rows);setError('');}).catch(()=>{if(!c.signal.aborted)setError('Não foi possível atualizar os valores. Recarregue a página.');});};window.addEventListener('icom-bank-ledger-changed',refresh);window.addEventListener('icom-bank-wealth-changed',refresh);return()=>{c.abort();window.removeEventListener('icom-bank-ledger-changed',refresh);window.removeEventListener('icom-bank-wealth-changed',refresh);};},[]);
 const s=financialOverview(rows,wealth,all?'':month),period=all?'Todo o histórico':new Date(month+'-15T12:00:00Z').toLocaleDateString('pt-BR',{month:'long',year:'numeric',timeZone:'America/Sao_Paulo'});
 return <section className="ia-overview" aria-label="Resumo da empresa e vida pessoal"><div className="bank-heading"><div><p className="bank-eyebrow">IA BANK · SEU DINHEIRO EM PERSPECTIVA</p><h1>O que fica para você.</h1><p>Empresa e vida pessoal. Uma visão do resultado.</p></div><div className="ia-period"><label>Período<input type="month" min="2000-01" max={brazilDay().slice(0,7)} disabled={all} value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value);}}/></label><label className="ia-check"><input type="checkbox" checked={all} onChange={e=>setAll(e.target.checked)}/>Acumulado</label></div></div><p className="ia-period-caption"><span className="ia-status-dot"/> {period} · registros realizados</p>{error&&<p className="bank-error" role="alert">{error}</p>}
 <div className="ia-priority-grid">{[
  {label:'Entradas de lucro · empresa',value:s.earnings,note:'Lucro dos carros + retornos + outras entradas',tone:'income',icon:ArrowUpRight,path:'/administrativo'},
  {label:'Gastos da empresa',value:s.costs,note:'Despesas sem repetir os custos já no lucro',tone:'expense',icon:ArrowDownRight,path:'/administrativo'},
  {label:'Despesas pessoais',value:s.personal,note:'Sua vida e sua família, separadas da loja',tone:'personal',icon:UserRound,path:'/administrativo#pessoais'},
 ].map(c=><a key={c.label} className={'ia-money-card '+c.tone} href={bankPath(c.path)}><div className="ia-card-top"><span className="ia-icon"><c.icon size={24}/></span><ArrowUpRight size={17}/></div><span className="ia-label">{c.label}</span><strong>{currency(c.value)}</strong><small>{c.note}</small></a>)}</div>
 <div className="ia-results"><a className={'ia-result '+(s.company<0?'negative':'')} href={bankPath('/administrativo')}><TrendingUp/><div><span>Resultado líquido da empresa</span><strong>{currency(s.company)}</strong><small>Lucro − gastos da empresa</small></div></a><a className={'ia-result primary '+(s.real<0?'negative':'')} href={bankPath('/administrativo')}><Wallet/><div><span>Resultado líquido real</span><strong>{currency(s.real)}</strong><small>Após gastos da empresa e despesas pessoais</small></div></a></div>
 <div className="ia-personal-strip"><div><span>Outras rendas pessoais recebidas</span><strong>{currency(s.otherIncome)}</strong></div><span className="ia-equation">+</span><div><span>Resultado total, incluindo outras rendas</span><strong className={s.total<0?'ia-loss':''}>{currency(s.total)}</strong></div><a href={bankPath('/administrativo/pessoal')}>Ver rendas <ArrowUpRight size={17}/></a></div>
 <div className="ia-money-links"><a href={bankPath('/administrativo/pessoal?tab=patrimonio')}><House/><span>Patrimônio líquido<strong>{currency(s.wealth.net)}</strong><small>Bens e aplicações − dívidas informadas</small></span><ArrowUpRight/></a><a href={bankPath('/administrativo/pessoal?tab=investimentos')}><Landmark/><span>Capital investido cadastrado<strong>{currency(s.wealth.invested)}</strong><small>{currency(s.wealth.contributions)} em novos aportes no período</small></span><ArrowUpRight/></a><a href={bankPath('/administrativo/conferencia-diaria')}><Coins/><span>Caixa disponível da loja<strong>{currency(s.cash.available)}</strong><small>Acumulado até hoje, excluindo reservas</small></span><ArrowUpRight/></a></div>
 <div className="ia-overview-actions"><a className="bank-primary" href={bankPath('/administrativo')}><Plus size={18}/> Registrar movimentação</a><a href={bankPath('/administrativo/pessoal')}>Administrativo pessoal →</a><a href={bankPath('/administrativo/contas-a-pagar')}>Contas a pagar →</a><a href={bankPath('/administrativo/contas-a-receber')}>Contas a receber →</a></div>
 <details className="ia-explanation"><summary>Como ler esses valores</summary><p>O lucro de cada venda usa o cálculo já existente: venda menos compra, custos do carro e comissão. As baixas desses mesmos custos e devoluções ao investidor não são descontadas novamente do resultado. As outras despesas da loja e as despesas pessoais são abatidas nos cartões seguintes.</p><p>Resultado e saldo em caixa são medidas diferentes. Venda a prazo e estoque não são dinheiro disponível. O caixa continua seguindo as reservas dos investidores, capital de repasses e custos. Patrimônio é o valor atual informado, não uma entrada; aportes e resgates do principal não são renda.</p><p>Rendas externas pessoais não alimentam o caixa da empresa. Registre somente o rendimento efetivamente recebido em “Renda recebida”, sem lançar novamente no Administrativo da loja.</p></details>
 {(s.missing>0||s.cash.reviewCount>0||s.unlinked>0)&&<p className="bank-error">Há registros com valor ou vínculo a conferir. {s.missing} conta(s) sem valor; {s.cash.reviewCount} venda(s) com reserva em revisão. <a href={bankPath('/administrativo')}>Conferir no Administrativo</a></p>}
 </section>;
}
