'use client';
import {riskProfiles,riskLabel,type RiskProfile} from '@/lib/icom-bank/risk';
import {useState} from 'react';
import {bankPath,brazilDay,currency} from '@/lib/icom-bank/model';
import {contractInput,installmentPlan,moneyInput,dateLabel,type FinanceInput} from '@/lib/icom-bank/contracts';
type Values=Record<string,string>;
const initial:Values={brand:'',model:'',plate:'',version:'',manufacture_year:'',model_year:'',color:'',chassis:'',renavam:'',mileage:'',fuel:'',store:'',vehicle_notes:'',vehicle_value:'',down_payment:'0',count:'',installment_value:'',sale_date:brazilDay(),first_due:'',period:'MENSAL',interest:'0',fine:'0',late_interest:'0',notes:''};
export default function BankContractForm({customer}:{customer:{id:string;name:string;cpf:string;risk_profile?:RiskProfile|null}}){const [values,setValues]=useState<Values>({...initial,risk_profile:customer.risk_profile||''}),[step,setStep]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false);const [requestId]=useState(()=>crypto.randomUUID());
 const input=()=>contractInput({customer_id:customer.id,request_id:requestId,vehicle:{...values,manufacture_year:values.manufacture_year?Number(values.manufacture_year):null,model_year:values.model_year?Number(values.model_year):null,mileage:values.mileage?Number(values.mileage):null,notes:values.vehicle_notes},finance:{vehicle_cents:moneyInput(values.vehicle_value),down_payment_cents:moneyInput(values.down_payment),count:Number(values.count),installment_cents:moneyInput(values.installment_value),sale_date:values.sale_date,first_due:values.first_due,period:values.period,interest_bps:moneyInput(values.interest),fine_bps:moneyInput(values.fine),late_interest_bps:moneyInput(values.late_interest),risk_profile:values.risk_profile||null,notes:values.notes}});
 const field=(name:string,label:string,type='text',required=false)=> <label key={name}>{label}{required?' *':''}<input name={name} type={type} required={required} value={values[name]} disabled={busy} onChange={e=>{setValues({...values,[name]:e.target.value});setError('');}} maxLength={type==='text'?name.includes('notes')?2000:160:undefined} step={type==='number'?1:undefined} min={type==='number'?0:undefined}/></label>;
 let finance:FinanceInput|null=null;try{finance=input().finance;}catch{}
 return <><div className="bank-heading"><div><p className="bank-eyebrow">VENDA PARCELADA · NOVO CONTRATO</p><h1>{customer.name}</h1><p>{customer.cpf} · Cliente já cadastrado</p></div><a href={bankPath('/clientes/'+customer.id)}>Voltar à ficha</a></div><div className="bank-steps"><span>✓ Dados do cliente</span>{['Veículo','Condições financeiras','Revisão e contrato'].map((label,i)=><span className={step===i?'active':''} key={label}>{i+2}. {label}</span>)}</div>
 <form className="bank-panel bank-contract-form" onSubmit={async e=>{e.preventDefault();setError('');if(step===0){setStep(1);return;}if(step===1){try{input();setStep(2);}catch(err){setError(err instanceof Error?err.message:'Confira os dados.');}return;}setBusy(true);try{const response=await fetch(bankPath('/api/contracts'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input())});const result=await response.json() as {id:string;error?:string};if(!response.ok)throw new Error(result.error||'Não foi possível salvar.');location.assign(bankPath('/contratos/'+result.id));}catch(err){setError(err instanceof Error?err.message:'Não foi possível salvar.');setBusy(false);}}}>
 {step===0&&<><h2>Veículo da venda</h2><p>Informe os dados do veículo. Marca, modelo e placa são obrigatórios.</p><div className="bank-form-grid">{field('brand','Marca','text',true)}{field('model','Modelo','text',true)}{field('plate','Placa','text',true)}{field('version','Versão')}{field('manufacture_year','Ano de fabricação','number')}{field('model_year','Ano modelo','number')}{field('color','Cor')}{field('chassis','Chassi')}{field('renavam','RENAVAM')}{field('mileage','Quilometragem','number')}{field('fuel','Combustível')}{field('store','Loja')}{field('vehicle_notes','Observações do veículo')}</div></>}
 {step===1&&<><h2>Condições financeiras</h2><p>Valores em reais, sem ponto de milhar. Exemplo: 1250,50.</p><div className="bank-form-grid">{field('vehicle_value','Valor do veículo','text',true)}{field('down_payment','Valor da entrada','text',true)}{field('count','Quantidade de parcelas (até 120)','number',true)}{field('installment_value','Valor de cada parcela','text',true)}{field('sale_date','Data da venda','date',true)}{field('first_due','Primeiro vencimento','date',true)}<label>Periodicidade<select value={values.period} onChange={e=>setValues({...values,period:e.target.value})}><option value="MENSAL">Mensal</option><option value="QUINZENAL">A cada 15 dias</option><option value="SEMANAL">Semanal</option></select></label><label>Perfil nesta venda<select value={values.risk_profile} disabled={busy} onChange={e=>setValues({...values,risk_profile:e.target.value})}><option value="">Sem classificação</option>{riskProfiles.map(p=><option value={p} key={p}>Perfil {p}</option>)}</select></label>{field('interest','Juros mensais informados (%)')}{field('fine','Multa por atraso (%)')}{field('late_interest','Juros mensais por atraso (%)')}{field('notes','Observações das condições')}</div><p className="bank-note">O perfil inicial vem da ficha do cliente. Você pode escolher outro para esta venda; a ficha permanece como estava. O perfil não calcula juros nem aprova crédito. O valor da parcela é definido por você. As taxas são registradas para consulta; não calculam nem alteram os valores automaticamente nesta etapa. A entrada não é lançada como pagamento confirmado.</p>{finance&&<div className="bank-mini"><article><span>Valor financiado</span><strong>{currency(finance.vehicle_cents-finance.down_payment_cents)}</strong></article><article><span>Total das parcelas</span><strong>{currency(finance.count*finance.installment_cents)}</strong></article><article><span>Total da venda com entrada</span><strong>{currency(finance.count*finance.installment_cents+finance.down_payment_cents)}</strong></article></div>}</>}
 {step===2&&finance&&<><h2>Confira antes de salvar</h2><div className="bank-mini"><article><span>{values.brand} {values.model}</span><strong>{values.plate.toUpperCase()}</strong></article><article><span>Financiado</span><strong>{currency(finance.vehicle_cents-finance.down_payment_cents)}</strong></article><article><span>{finance.count} parcelas</span><strong>{currency(finance.installment_cents)}</strong></article></div><dl className="bank-detail"><div><dt>Data da venda</dt><dd>{dateLabel(finance.sale_date)}</dd></div><div><dt>Entrada informada</dt><dd>{currency(finance.down_payment_cents)}</dd></div><div><dt>Total das parcelas a receber</dt><dd>{currency(finance.count*finance.installment_cents)}</dd></div><div><dt>Perfil registrado nesta venda</dt><dd>{riskLabel(finance.risk_profile)}</dd></div><div><dt>Juros / multa / juros de atraso</dt><dd>{values.interest}% / {values.fine}% / {values.late_interest}%</dd></div></dl><p className="bank-note">Este cadastro registra as condições da venda no controle interno. Não substitui um contrato assinado. Ao salvar, veículo, contrato e parcelas serão registrados juntos.</p><div className="bank-table bank-plan"><table><thead><tr><th>Parcela</th><th>Vencimento</th><th>Valor</th></tr></thead><tbody>{installmentPlan(finance).map(row=><tr key={row.number}><td>{String(row.number).padStart(2,'0')}/{finance.count}</td><td>{dateLabel(row.due_date)}</td><td>{currency(row.original_cents)}</td></tr>)}</tbody></table></div></>}
 {error&&<p className="bank-error" role="alert">{error}</p>}<div className="bank-actions">{step>0&&<button type="button" disabled={busy} onClick={()=>{setError('');setStep(step-1);}}>Voltar</button>}<button className="bank-primary" disabled={busy}>{busy?'SALVANDO…':step===0?'CONTINUAR':step===1?'REVISAR PARCELAS':'SALVAR CONTRATO E PARCELAS'}</button></div></form></>;
}
