'use client';
import {useState,type FormEvent} from 'react';
import {Plus,House,Landmark,Coins} from 'lucide-react';
import {bankPath,brazilDay,currency} from '@/lib/icom-bank/model';
import {adminMoneyInput,adminMoneyText} from '@/lib/icom-bank/administrative';
import {wealthKinds,wealthCategories,wealthSummary,monthlyEstimate,type WealthRecord,type WealthKind} from '@/lib/icom-bank/personal-wealth';
type Draft={id:string;kind:WealthKind;name:string;category:string;date:string;amount:string;debt:string;invested:string;rate:string;rate_period:'MENSAL'|'ANUAL';source_id:string;notes:string;expected:string|null};
export default function BankPersonalWealth({initial,initialTab='rendas'}:{initial:WealthRecord[];initialTab?:string}){
 const [rows,setRows]=useState(initial),[tab,setTab]=useState(['rendas','patrimonio','investimentos'].includes(initialTab)?initialTab:'rendas'),[period,setPeriod]=useState(brazilDay().slice(0,7)),[draft,setDraft]=useState<Draft|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[archived,setArchived]=useState(false),[archive,setArchive]=useState<WealthRecord|null>(null);
 const stats=wealthSummary(rows,period),assets=rows.filter(r=>r.active&&r.kind==='ATIVO');
 const list=rows.filter(r=>r.active!==archived&&(tab==='patrimonio'?r.kind==='ATIVO':tab==='rendas'?r.kind==='RENDA'&&r.record_date.startsWith(period):r.kind==='APORTE'||r.kind==='RESGATE'||r.kind==='ATIVO')).sort((a,b)=>b.record_date.localeCompare(a.record_date)||a.name.localeCompare(b.name));
 function open(kind:WealthKind,record?:WealthRecord){setDraft({id:record?.id||crypto.randomUUID(),kind:record?.kind||kind,name:record?.name||'',category:record?.category||wealthCategories[0],date:record?.record_date||brazilDay(),amount:adminMoneyText(record?.amount_cents||0),debt:adminMoneyText(record?.debt_cents||0),invested:adminMoneyText(record?.invested_cents||0),rate:record?.rate_percent===null||record?.rate_percent===undefined?'':String(record.rate_percent).replace('.',','),rate_period:record?.rate_period||'MENSAL',source_id:record?.source_id||'',notes:record?.notes||'',expected:record?.updated_at||null});setError('');setNotice('');setArchive(null);}
 const field=(key:keyof Draft,value:string)=>setDraft(d=>d?{...d,[key]:value}:d);
 async function load(){setBusy(true);setError('');try{const r=await fetch(bankPath('/api/personal-wealth'),{cache:'no-store'}),data=await r.json() as {rows?:WealthRecord[];row?:WealthRecord;error?:string};if(!r.ok||!Array.isArray(data.rows))throw new Error(data.error||'Não foi possível atualizar.');setRows(data.rows);}catch(e){setError(e instanceof Error?e.message:'Não foi possível atualizar.');}finally{setBusy(false);}}
 async function store(payload:Record<string,unknown>){const r=await fetch(bankPath('/api/personal-wealth'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),data=await r.json() as {rows?:WealthRecord[];row?:WealthRecord;error?:string};if(!r.ok||!data.row)throw new Error(data.error||'Não foi possível salvar.');const row=data.row;setRows(old=>[row,...old.filter(x=>x.id!==row.id)]);window.dispatchEvent(new Event('icom-bank-wealth-changed'));return data.row as WealthRecord;}
 async function save(e:FormEvent){e.preventDefault();if(!draft||busy)return;setBusy(true);setError('');try{
  if(draft.rate&&!/^\d{1,3}(?:[,.]\d{1,4})?$/.test(draft.rate))throw new Error('Taxa em percentual, até quatro casas decimais. Exemplo: 1,25.');
  await store({id:draft.id,kind:draft.kind,name:draft.name,category:draft.category,record_date:draft.date,amount_cents:adminMoneyInput(draft.amount),debt_cents:draft.kind==='ATIVO'?adminMoneyInput(draft.debt):0,invested_cents:draft.kind==='ATIVO'?adminMoneyInput(draft.invested):0,rate_percent:draft.kind==='ATIVO'&&draft.rate?Number(draft.rate.replace(',','.')):null,rate_period:draft.rate_period,source_id:draft.source_id||null,notes:draft.notes,active:true,expected_updated_at:draft.expected});
  setNotice('Registro salvo. Os resumos pessoais foram atualizados.');setTab(draft.kind==='ATIVO'?'patrimonio':draft.kind==='RENDA'?'rendas':'investimentos');setDraft(null);
 }catch(e){setError(e instanceof Error?e.message:'Confira os campos.');}finally{setBusy(false);}}
 async function archiveRecord(){if(!archive||busy)return;setBusy(true);setError('');try{await store({...archive,active:!archive.active,expected_updated_at:archive.updated_at});setNotice(archive.active?'Registro arquivado; o histórico permanece disponível.':'Registro restaurado.');setArchive(null);}catch(e){setError(e instanceof Error?e.message:'Não foi possível concluir.');}finally{setBusy(false);}}
 const moneyField=(key:'amount'|'debt'|'invested',label:string)=><label>{label}<input inputMode="decimal" required value={draft?.[key]||''} onChange={e=>field(key,e.target.value)} onBlur={()=>{try{field(key,adminMoneyText(adminMoneyInput(draft?.[key]||'0')));}catch{}}}/></label>;
 return <><div className="bank-heading"><div><p className="bank-eyebrow">IA BANK · VIDA PESSOAL</p><h1>Seu patrimônio. Suas rendas.</h1><p>Outras fontes de renda, bens e investimentos, separados da loja.</p></div><a href={bankPath('/dashboard')}>← Visão geral</a></div><div className="ia-money-links"><article><House/><span>Patrimônio líquido<strong>{currency(stats.net)}</strong><small>{currency(stats.gross)} em bens − {currency(stats.debt)} em dívidas</small></span></article><article><Landmark/><span>Capital investido cadastrado<strong>{currency(stats.invested)}</strong><small>Valores informados no patrimônio atual</small></span></article><article><Coins/><span>Outras rendas recebidas<strong>{currency(stats.income)}</strong><small>No período selecionado</small></span></article></div>
 <div className="bank-admin-toolbar"><label>Período<input type="month" min="2000-01" max={brazilDay().slice(0,7)} value={period} onChange={e=>{if(e.target.value)setPeriod(e.target.value);}}/></label><button disabled={busy} onClick={()=>void load()}>Atualizar lista</button><button className="bank-primary" disabled={busy} onClick={()=>open('ATIVO')}><Plus size={17}/> Cadastrar patrimônio</button><button className="bank-primary" disabled={busy} onClick={()=>open('RENDA')}><Plus size={17}/> Registrar renda recebida</button><button disabled={busy} onClick={()=>open('APORTE')}>Registrar aporte</button><button disabled={busy} onClick={()=>open('RESGATE')}>Registrar resgate</button></div>
 <nav className="ia-personal-tabs" aria-label="Administrativo pessoal">{[['rendas','Rendas recebidas'],['patrimonio','Patrimônio'],['investimentos','Investimentos e aportes']].map(([key,label])=><button key={key} aria-pressed={tab===key} onClick={()=>{setTab(key);setDraft(null);setArchive(null);}}>{label}</button>)}</nav>
 {notice&&<p className="bank-note" role="status">{notice}</p>}{error&&<p className="bank-error" role="alert">{error}</p>}
 {draft&&<form onSubmit={save} className="bank-panel bank-wealth-form" data-bank-help-view="patrimonio_form"><div className="bank-panel-title"><h2>{draft.expected?'Editar':'Novo registro'} · {wealthKinds[draft.kind]}</h2><button type="button" disabled={busy} onClick={()=>setDraft(null)}>Fechar</button></div><div className="bank-form-grid"><label>Nome / descrição<input required minLength={2} maxLength={160} value={draft.name} onChange={e=>field('name',e.target.value)} placeholder={draft.kind==='ATIVO'?'Ex.: Apartamento alugado, CDB, poupança':'Ex.: Aluguel recebido de outubro'}/></label><label>Categoria<select value={draft.category} onChange={e=>field('category',e.target.value)}>{wealthCategories.map(c=><option key={c}>{c}</option>)}</select></label><label>{draft.kind==='ATIVO'?'Data de referência do valor':'Data do recebimento / movimentação'}<input type="date" min="2000-01-01" max={brazilDay()} required value={draft.date} onChange={e=>field('date',e.target.value)}/></label>{moneyField('amount',draft.kind==='ATIVO'?'Valor atual do bem / saldo da aplicação (R$)':draft.kind==='RENDA'?'Rendimento líquido efetivamente recebido (R$)':'Valor do principal movimentado (R$)')}
 {draft.kind==='ATIVO'?<>{moneyField('debt','Dívida ainda vinculada a este bem (R$)')}{moneyField('invested','Capital investido / valor de aquisição (R$)')}<label>Taxa de juros informada (%) · opcional<input inputMode="decimal" value={draft.rate} onChange={e=>field('rate',e.target.value)} placeholder="Ex.: 1,25"/><small>Apenas referência para rendimento estimado.</small></label><label>Taxa por período<select value={draft.rate_period} onChange={e=>field('rate_period',e.target.value)}><option value="MENSAL">Ao mês</option><option value="ANUAL">Ao ano</option></select></label></>:<label>Bem / investimento relacionado · opcional<select value={draft.source_id} onChange={e=>{field('source_id',e.target.value);const a=assets.find(a=>a.id===e.target.value);if(a)field('category',a.category);}}><option value="">Renda independente</option>{assets.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}{draft.source_id&&!assets.some(a=>a.id===draft.source_id)&&<option value={draft.source_id}>Bem arquivado · mantenha o vínculo</option>}</select></label>}
 </div><label>Observações · instituição, imóvel, pagador ou condições<textarea maxLength={2000} rows={3} value={draft.notes} onChange={e=>field('notes',e.target.value)}/></label><p className="bank-note">{draft.kind==='ATIVO'?'O cadastro registra o valor atual informado. Juros estimados não viram receita automaticamente. Atualize o saldo do patrimônio quando mudar.':draft.kind==='RENDA'?'Registre somente o rendimento recebido, depois de taxas e impostos conhecidos. Devolução do dinheiro aplicado é Resgate do capital, não renda. Não repita um recebimento já cadastrado.':'Aportes e resgates registram o principal: não são receita ou despesa de consumo. Atualize também o saldo do patrimônio relacionado; estes registros não movimentam uma conta bancária.'}</p><div className="bank-actions"><button type="button" disabled={busy} onClick={()=>setDraft(null)}>Cancelar</button><button className="bank-primary" disabled={busy}>{busy?'Salvando…':'Salvar registro'}</button></div></form>}
 {archive&&<section className="bank-panel"><h2>{archive.active?'Arquivar':'Restaurar'} registro</h2><p>{archive.name} · {currency(archive.amount_cents)}. {archive.active?'Sairá dos totais sem apagar o histórico.':'Voltará aos totais.'}</p><div className="bank-actions"><button disabled={busy} onClick={()=>setArchive(null)}>Cancelar</button><button className="bank-primary" disabled={busy} onClick={()=>void archiveRecord()}>Confirmar {archive.active?'arquivamento':'restauração'}</button></div></section>}
 <section className="bank-panel"><div className="bank-panel-title"><h2>{tab==='rendas'?'Rendas pessoais recebidas':tab==='patrimonio'?'Seus bens e aplicações':'Capital e movimentações'}</h2><label className="ia-check"><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/>Arquivados</label></div><p>{tab==='rendas'?'Recebimentos do período. Sem estimativas ou devolução do principal.':'O patrimônio mostra o cadastro atual, independentemente do mês de recebimentos escolhido.'}</p><div className="bank-table"><table><thead><tr>{['Referência','Nome','Categoria','Tipo','Valor','Dívida / capital investido','Taxa / estimativa','Ações'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{list.map(r=><tr key={r.id}><td>{r.record_date.split('-').reverse().join('/')}</td><td><strong>{r.name}</strong>{r.source_id&&<small>Vinculado: {rows.find(a=>a.id===r.source_id)?.name||'Bem cadastrado'}</small>}{r.notes&&<small>{r.notes}</small>}</td><td>{r.category}</td><td>{wealthKinds[r.kind]}</td><td>{currency(r.amount_cents)}</td><td>{r.kind==='ATIVO'?<>{currency(r.debt_cents)} em dívida<small>{currency(r.invested_cents)} investidos</small></>:'—'}</td><td>{r.rate_percent!==null?<>{r.rate_percent.toLocaleString('pt-BR')}% {r.rate_period==='MENSAL'?'a.m.':'a.a.'}<small>Referência mensal: {currency(monthlyEstimate(r)||0)}</small></>:'—'}</td><td><div className="bank-admin-row-actions">{r.active&&<button disabled={busy} onClick={()=>open(r.kind,r)}>Editar</button>}<button disabled={busy} onClick={()=>{setArchive(r);setDraft(null);}}>{r.active?'Arquivar':'Restaurar'}</button>{r.kind==='ATIVO'&&r.active&&<button disabled={busy} onClick={()=>{open('RENDA');setDraft(d=>d?{...d,source_id:r.id,category:r.category,name:'Rendimento · '+r.name}:d);}}>Registrar rendimento</button>}</div></td></tr>)}{!list.length&&<tr><td colSpan={8}><div className="bank-empty">Nenhum registro neste filtro. Comece pelo cadastro de patrimônio ou por uma renda recebida.</div></td></tr>}</tbody></table></div></section>
 <p className="bank-note">Patrimônio líquido = valor atual informado − dívidas vinculadas. A taxa cadastrada gera apenas uma referência simples, sem garantir rentabilidade ou consultar saldos bancários. A previsão anual é dividida por 12; não representa uma simulação de juros compostos. A área é exclusiva do proprietário e não altera os cálculos nem os registros da loja.</p><a href={bankPath('/administrativo')}>← Voltar ao Administrativo da empresa</a>
 </>;
}
