'use client';
import {expenseContext,expenseAudiences,expenseNatures,audienceLabel,natureLabel,type ExpenseAudience,type ExpenseNature} from '@/lib/icom-bank/expense-context';
import {personalCategories,personalCategory,personalSummary,expenseFold} from '@/lib/icom-bank/personal-expenses';
import BankCashPosition from './BankCashPosition';
import BankFinancialNavigation from './BankFinancialNavigation';
import {useState,useEffect,type ReactNode} from 'react';
import {bankPath,brazilDay,currency} from '@/lib/icom-bank/model';
import {adminStats,adminSaleSettlement,saleCost,saleProfit,returnNet,returnStore,type AdminEntry,type AdminKind,type AdminReference,type AdminSeller} from '@/lib/icom-bank/administrative';
import BankAdminForm,{type AdminPreset} from './BankAdminForm';

const sections=[{id:'resumo',label:'Fechamento',kind:'ENTRADA'},{id:'vendas',label:'Vendas',kind:'VENDA'},{id:'entradas',label:'Entradas',kind:'ENTRADA'},{id:'custos',label:'Custos da loja',kind:'CUSTO'},{id:'retornos',label:'Retornos',kind:'RETORNO'},{id:'trocas',label:'Trocas',kind:'TROCA'},{id:'mensais',label:'Contas mensais',kind:'MENSAL'},{id:'pessoais',label:'Despesas pessoais',kind:'PESSOAL'}] as const;
type Section=(typeof sections)[number]['id'];
const monthNames=['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];
const money=(n:number|undefined|null)=>n===undefined||n===null?'Não informado':currency(n);
const dateLabel=(date:string)=>date.split('-').reverse().join('/');
const titles:Record<AdminKind,string>={VENDA:'Venda',ENTRADA:'Entrada',CUSTO:'Custo da loja',RETORNO:'Retorno',TROCA:'Troca',MENSAL:'Conta mensal',PESSOAL:'Despesa pessoal'};

export default function BankAdministrative({initial,reference,initialYear,sellers:initialSellers}:{initial:AdminEntry[];reference:AdminReference|null;initialYear:number;sellers:AdminSeller[]}){
 const [sellers,setSellers]=useState(initialSellers);
 const [audienceFilter,setAudienceFilter]=useState<ExpenseAudience|''>(''),[natureFilter,setNatureFilter]=useState<ExpenseNature|''>('');
 const [personalFilter,setPersonalFilter]=useState(''),[tripFilter,setTripFilter]=useState('');
 const [rows,setRows]=useState(initial),[year,setYear]=useState(initialYear),[yearInput,setYearInput]=useState(String(initialYear)),[month,setMonth]=useState(brazilDay().slice(5,7)),[selected,setSelected]=useState<Section>('resumo'),[search,setSearch]=useState(''),[archived,setArchived]=useState(false),[costGroup,setCostGroup]=useState(''),[scopeFilter,setScopeFilter]=useState(''),[form,setForm]=useState<{entry?:AdminEntry;preset:AdminPreset}|null>(null),[notice,setNotice]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[archiveReview,setArchiveReview]=useState<AdminEntry|null>(null);
 useEffect(()=>{if(location.hash==='#pessoais')setSelected('pessoais');},[]);
 useEffect(()=>{const controller=new AbortController();const refresh=()=>{void fetch(bankPath('/api/administrative?year='+year),{signal:controller.signal,cache:'no-store'}).then(async response=>{const data=await response.json() as {rows?:AdminEntry[]};if(response.ok&&Array.isArray(data.rows))setRows(data.rows);}).catch(()=>{});};window.addEventListener('icom-bank-ledger-changed',refresh);return()=>{controller.abort();window.removeEventListener('icom-bank-ledger-changed',refresh);};},[year]);
 const period=month==='all'?String(year):`${year}-${month}`,stats=adminStats(rows,period),section=sections.find(s=>s.id===selected)!;
 const changeSection=(next:Section)=>{setSelected(next);setPersonalFilter('');setTripFilter('');setAudienceFilter('');setNatureFilter('');setForm(null);setArchiveReview(null);setSearch('');setCostGroup('');setScopeFilter('');setError('');};
 const context=(e:AdminEntry)=>({...expenseContext(e.description,personalCategory(e.category,e.description)),...(e.details.expense_audience?{expense_audience:e.details.expense_audience}:{}),...(e.details.expense_nature?{expense_nature:e.details.expense_nature}:{})});
 const matches=(e:AdminEntry)=>e.active!==archived&&e.entry_date.startsWith(period)&&(!search||`${e.description} ${e.category} ${e.details.vehicle||''} ${e.details.plate||''} ${e.details.seller||''} ${e.details.trip_name||''}`.toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR')));
 const list=rows.filter(e=>matches(e)&&(selected==='resumo'||selected==='pessoais'?selected==='resumo'||e.scope==='PESSOAL':selected==='mensais'?e.kind==='MENSAL':e.kind===section.kind)&&(!costGroup||e.category===costGroup)&&(!scopeFilter||e.scope===scopeFilter)&&(selected!=='pessoais'||(!audienceFilter||context(e).expense_audience===audienceFilter)&&(!natureFilter||context(e).expense_nature===natureFilter)&&(!personalFilter||personalCategory(e.category,e.description)===personalFilter)&&(!tripFilter||expenseFold(e.details.trip_name||'')===expenseFold(tripFilter)))).sort((a,b)=>b.entry_date.localeCompare(a.entry_date)||a.description.localeCompare(b.description));
 const personalPeriod=rows.filter(e=>e.entry_date.startsWith(period)),personal=personalSummary(personalPeriod,personalFilter,tripFilter,undefined,undefined,audienceFilter||undefined,natureFilter||undefined),personalAll=personalSummary(personalPeriod);
 const tripNames=[...new Set(rows.filter(e=>e.active&&e.scope==='PESSOAL').map(e=>e.details.trip_name).filter((n):n is string=>!!n))].sort();
 const newDate=()=>`${year}-${month==='all'?brazilDay().slice(5,7):month}-${year===initialYear&&month===brazilDay().slice(5,7)?brazilDay().slice(8):'01'}`;
 const open=(entry?:AdminEntry,preset?:AdminPreset)=>{setForm({entry,preset:preset||{kind:section.kind,date:newDate()}});setNotice('');setError('');};
 const replace=(entry:AdminEntry)=>setRows(old=>[entry,...old.filter(e=>e.id!==entry.id)]);
 async function load(nextYear:number){setError('');setBusy(true);try{const r=await fetch(bankPath(`/api/administrative?year=${nextYear}`)),data=await r.json() as {rows?:AdminEntry[];sellers?:AdminSeller[];error?:string};if(!r.ok||!Array.isArray(data.rows))throw new Error(data.error||'Não foi possível carregar.');setRows(data.rows);if(data.sellers)setSellers(data.sellers);setYear(nextYear);setYearInput(String(nextYear));setForm(null);setArchiveReview(null);}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar.');}finally{setBusy(false);}}
 async function archive(entry:AdminEntry){setBusy(true);setError('');try{const r=await fetch(bankPath('/api/administrative'),{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:entry.id,active:!entry.active,expected_updated_at:entry.updated_at})}),data=await r.json() as {row?:AdminEntry;error?:string};if(!r.ok||!data.row)throw new Error(data.error||'Não foi possível concluir.');replace(data.row);void load(year);setArchiveReview(null);setNotice(entry.active?'Lançamento arquivado. Você pode restaurá-lo em “Arquivados”.':'Lançamento restaurado.');}catch(e){setError(e instanceof Error?e.message:'Não foi possível confirmar a alteração.');}finally{setBusy(false);}}
 const actions=(entry:AdminEntry)=><div className="bank-admin-row-actions">{entry.active&&<button type="button" disabled={busy} onClick={()=>open(entry)}>Editar</button>}<button type="button" disabled={busy} onClick={()=>setArchiveReview(entry)}>{entry.active?'Arquivar':'Restaurar'}</button></div>;
 const status=(entry:AdminEntry)=><span className={`bank-pill ${entry.status==='REALIZADO'?'green':'gold'}`}>{entry.status==='REALIZADO'?'Realizado':'Previsto'}</span>;
 const sheet=(headers:string[],cells:(e:AdminEntry)=>ReactNode[])=><div className="bank-table bank-admin-sheet"><table><thead><tr>{headers.map(h=><th scope="col" key={h}>{h}</th>)}<th scope="col">Situação</th><th scope="col">Ações</th></tr></thead><tbody>{list.map(e=><tr key={e.id}>{cells(e).map((cell,i)=><td key={i}>{cell}</td>)}<td>{status(e)}</td><td>{actions(e)}</td></tr>)}{!list.length&&<tr><td colSpan={headers.length+2}><div className="bank-empty">Nenhum lançamento neste filtro. Use “Novo lançamento” para começar.</div></td></tr>}</tbody></table></div>;
 const basicSheet=()=>sheet(['Data','Descrição','Área / escopo','Categoria','Viagem','Contexto','Classificação','Carro / placa','Valor','Forma de pagamento'],e=>[dateLabel(e.entry_date),<span key="description">{e.description}{e.details.notes&&<small>{e.details.notes}</small>}</span>,`${titles[e.kind]} · ${e.scope==='LOJA'?'Loja':'Pessoal'}`,e.scope==='PESSOAL'?personalCategory(e.category,e.description):e.category||'—',e.details.trip_name||'—',e.scope==='PESSOAL'?audienceLabel(context(e).expense_audience):'—',e.scope==='PESSOAL'?natureLabel(context(e).expense_nature):'—',`${e.details.vehicle||'—'} ${e.details.plate||''}`,money(e.amount_cents),e.details.payment_method||'—']);
 const monthlyRows=()=>{
  const existing=rows.filter(e=>e.kind==='MENSAL'&&e.active!==archived&&(!scopeFilter||e.scope===scopeFilter));
  const names=[...new Set([...(!archived&&!scopeFilter?(reference?.monthly||[]).map(x=>x.label):[]),...existing.map(e=>e.description)])].filter(name=>!search||name.toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR')));
  return <><p className="bank-note">Visão anual de {year}. Clique no mês para cadastrar ou editar uma conta. “OK” sem valor fica sinalizado; não vira um pagamento de R$ 0. As linhas do PDF servem como modelo e ainda não são despesas cadastradas.</p><div className="bank-table bank-admin-sheet bank-admin-monthly"><table><thead><tr><th scope="col">Conta / descrição</th><th scope="col">Dia</th>{monthNames.map((m,i)=><th scope="col" key={m}>{m.slice(0,3)}<small>{String(i+1).padStart(2,'0')}</small></th>)}</tr></thead><tbody>{names.map(name=>{
   const due=existing.find(e=>e.description===name)?.details.due_day||reference?.monthly.find(e=>e.label===name)?.due_day||1;
   return <tr key={name}><th scope="row">{name}</th><td>{due}</td>{monthNames.map((m,i)=>{const date=`${year}-${String(i+1).padStart(2,'0')}`,entries=existing.filter(e=>e.description===name&&e.entry_date.startsWith(date)),last=new Date(Date.UTC(year,i+1,0)).getUTCDate();return <td key={m}>{entries.length?entries.map(e=><button className={`bank-admin-cell ${e.status==='REALIZADO'?'paid':'planned'}`} key={e.id} title={`${e.scope} · ${e.description}`} disabled={archived} onClick={()=>open(e)}>{money(e.amount_cents)}<small>{e.status==='REALIZADO'?(e.amount_cents===null?'OK · sem valor':'Pago'):'Previsto'} · {e.scope==='LOJA'?'Loja':'Pessoal'}</small></button>):<button className="bank-admin-cell empty" disabled={archived} onClick={()=>open(undefined,{kind:'MENSAL',date:`${date}-${String(Math.min(due,last)).padStart(2,'0')}`,description:name,due_day:due,scope:scopeFilter==='PESSOAL'?'PESSOAL':scopeFilter==='LOJA'?'LOJA':undefined})} aria-label={`Cadastrar ${name} em ${m}`}>+<small>Sem lançamento</small></button>}</td>;})}</tr>;
  })}{!names.length&&<tr><td colSpan={14}><div className="bank-empty">Nenhuma conta neste filtro.</div></td></tr>}</tbody></table></div><h2 className="bank-admin-list-title">Lançamentos do período selecionado</h2>{basicSheet()}</>;
 };
 return <>
  <div className="bank-heading"><div><p className="bank-eyebrow">ORGANIZAÇÃO FINANCEIRA</p><h1>Administrativo</h1><p>Loja e vida pessoal, com cada valor no seu lugar.</p></div><span className="bank-pill gold">Acesso do proprietário</span></div>
  <BankFinancialNavigation/><a className="ia-personal-access bank-panel" href={bankPath('/administrativo/pessoal')}><strong>Administrativo pessoal</strong><span> Outras rendas, investimentos e patrimônio →</span></a><div className="bank-actions"><a className="bank-admin-export bank-investor-access" href={bankPath('/administrativo/investidores')}>Investidores da loja · cadastrar e ver carros →</a></div>
  <div className="bank-admin-toolbar"><form onSubmit={e=>{e.preventDefault();void load(Number(yearInput));}}><label>Ano<input type="number" min={2000} max={2100} required value={yearInput} disabled={busy} onChange={e=>setYearInput(e.target.value)}/></label><button disabled={busy}>Aplicar ano</button></form><label>Mês<select value={month} disabled={busy} onChange={e=>{setMonth(e.target.value);setForm(null);}}><option value="all">Ano inteiro</option>{monthNames.map((m,i)=><option key={m} value={String(i+1).padStart(2,'0')}>{m}</option>)}</select></label><button type="button" disabled={busy} onClick={()=>void load(year)}>Atualizar lista</button><a className="bank-admin-export" href={bankPath(`/api/administrative?year=${year}&month=${month}&format=csv`)}>Exportar para Excel</a><button type="button" disabled={busy} className="bank-primary" onClick={()=>open()}>+ NOVO LANÇAMENTO</button></div>
  {notice&&<p className="bank-note" role="status">{notice}</p>}{error&&<p className="bank-error" role="alert">{error}</p>}
  <nav className="bank-admin-areas" aria-label="Áreas administrativas">{sections.map(s=><button key={s.id} type="button" aria-pressed={selected===s.id} onClick={()=>changeSection(s.id)}><small>{s.id==='pessoais'?'PESSOAL':'GESTÃO'}</small><strong>{s.label}</strong></button>)}</nav>
  {form&&<BankAdminForm key={form.entry?.id||JSON.stringify(form.preset)} entry={form.entry} preset={form.preset} sellers={sellers} entries={rows} onCancel={()=>setForm(null)} onSaved={entry=>{replace(entry);void load(year);setForm(null);setNotice('Lançamento salvo. Os totais foram atualizados.');}}/>}
  {archiveReview&&<section className="bank-panel bank-admin-review"><h2>{archiveReview.active?'Arquivar lançamento':'Restaurar lançamento'}</h2><p><strong>{archiveReview.description}</strong> · {dateLabel(archiveReview.entry_date)} · {money(archiveReview.amount_cents)}</p><p>{archiveReview.active?'Ele sairá dos totais, preservando o histórico. Você poderá restaurá-lo depois.':'Ele voltará aos totais conforme sua data e situação.'}</p><div className="bank-actions"><button disabled={busy} onClick={()=>setArchiveReview(null)}>Cancelar</button><button className="bank-primary" disabled={busy} onClick={()=>void archive(archiveReview)}>{busy?'Salvando…':archiveReview.active?'CONFIRMAR ARQUIVAMENTO':'CONFIRMAR RESTAURAÇÃO'}</button></div></section>}
  {selected==='pessoais'&&<section className="bank-panel bank-personal-overview"><p className="bank-eyebrow">BRUNO E GISELA · DESPESAS PESSOAIS</p><h2>Quanto foi gasto, e em quê</h2><div className="bank-kpis"><article className="bank-kpi gold"><span>GASTO REALIZADO · FILTRO ATUAL</span><strong>{currency(personal.amount_cents)}</strong><small>{personal.count} pagamento(s) · previstos e arquivados ficam fora</small></article><article className="bank-kpi navy"><span>VIAGEM SELECIONADA</span><strong>{tripFilter||'Todas as viagens'}</strong><small>O total segue o ano, mês e categoria escolhidos</small></article></div><h3>Família e gastos opcionais</h3><div className="bank-personal-groups">{personalAll.audiences.map(g=><button key={'audience-'+g.name} aria-pressed={audienceFilter===g.name} onClick={()=>setAudienceFilter(v=>v===g.name?'':g.name as ExpenseAudience)}><span>{audienceLabel(g.name)}</span><strong>{currency(g.amount_cents)}</strong></button>)}{personalAll.natures.map(g=><button key={'nature-'+g.name} aria-pressed={natureFilter===g.name} onClick={()=>setNatureFilter(v=>v===g.name?'':g.name as ExpenseNature)}><span>{natureLabel(g.name)}</span><strong>{currency(g.amount_cents)}</strong></button>)}</div><p className="bank-note">São perspectivas do mesmo gasto. Opcionais incluem lazer, viagens e assinaturas, ou sua classificação explícita. Valores não classificados ficam separados e podem ser ajustados em Editar.</p><h3>Categorias · total pago no período</h3><div className="bank-personal-groups">{[...personalCategories,...personalAll.categories.map(c=>c.name).filter(c=>!personalCategories.includes(c as typeof personalCategories[number]))].map(c=><button key={c} aria-pressed={personalFilter===c} onClick={()=>setPersonalFilter(v=>v===c?'':c)}><span>{c}</span><strong>{currency(personalAll.categories.find(g=>g.name===c)?.amount_cents||0)}</strong></button>)}</div><h3>Viagens · total pago no período</h3>{personalAll.trips.length?<div className="bank-personal-groups">{personalAll.trips.map(t=><button key={t.name} aria-pressed={tripFilter===t.name} onClick={()=>setTripFilter(v=>v===t.name?'':t.name)}><span>{t.name}</span><strong>{currency(t.amount_cents)}</strong><small>{t.count} lançamento(s)</small></button>)}</div>:<p className="bank-note">No novo lançamento, preencha Viagem, por exemplo Disney 2026. No WhatsApp diga: “Paguei 230 reais no restaurante, na viagem Disney 2026”. Depois pergunte à IA: “Quanto gastei na viagem Disney 2026?”.</p>}<p className="bank-note">Restaurante em uma viagem conta na categoria Restaurante e também naquela viagem. Esses dois resumos mostram o mesmo gasto por perspectivas diferentes: não some os dois totais.</p></section>}
  {selected==='resumo'&&<>
   <BankCashPosition entries={rows}/>
   <div className="bank-kpis"><article className="bank-kpi green"><span>ENTRADAS REALIZADAS · LOJA</span><strong>{currency(stats.income)}</strong><small>Recebido, incluindo retornos brutos</small></article><article className="bank-kpi red"><span>SAÍDAS REALIZADAS · LOJA</span><strong>{currency(stats.expenses)}</strong><small>Custos, contas e repasses de retornos</small></article><article className="bank-kpi navy"><span>MOVIMENTO BRUTO DO PERÍODO</span><strong>{currency(stats.balance)}</strong><small>Entradas menos saídas do período</small></article><article className="bank-kpi gold"><span>DESPESAS PESSOAIS REALIZADAS</span><strong>{currency(stats.personal)}</strong><small>Separadas da operação da loja</small></article></div>
   <div className="bank-mini"><article><span>Vendas realizadas</span><strong>{stats.sales}</strong></article><article><span>Lucro dos veículos</span><strong>{currency(stats.profit)}</strong></article><article><span>Retorno líquido para a loja</span><strong>{currency(stats.returns)}</strong></article></div>
   <section className="bank-panel"><h2>Fechamento do período</h2><div className="bank-detail"><div><span>Movimento bruto da loja · período</span><strong>{currency(stats.balance)}</strong></div><div><span>Despesas pessoais</span><strong>{currency(stats.personal)}</strong></div><div><span>Saldo após despesas pessoais</span><strong>{currency(stats.combined)}</strong></div></div><p className="bank-note">Este fechamento mostra o movimento bruto do período. Para pagar contas, use o saldo disponível acumulado acima, que exclui reservas e dinheiro de terceiros. Vendas contam no caixa apenas pelo dinheiro efetivamente recebido. Custos do veículo e comissão calculam o lucro; registre seus pagamentos em Custos da loja. Previsto e arquivado não entram nos totais realizados.</p>{stats.missing>0&&<p className="bank-error">Total parcial: {stats.missing} conta(s) marcada(s) como realizada(s) sem valor informado.</p>}</section>
  </>}
  <section className="bank-panel"><div className="bank-panel-title"><div><h2>{selected==='resumo'?'Lançamentos do período':section.label}</h2><p>{selected==='mensais'?`Planilha anual · ${year}`:`${month==='all'?'Ano inteiro':monthNames[Number(month)-1]} de ${year} · ${list.length} lançamento(s)`}</p></div><label className="bank-admin-archive-filter"><input type="checkbox" checked={archived} onChange={e=>{setArchived(e.target.checked);setArchiveReview(null);}}/> Arquivados</label></div>
   <div className="bank-filters">{selected==='pessoais'&&<><select aria-label="Filtrar contexto" value={audienceFilter} onChange={e=>setAudienceFilter(e.target.value as ExpenseAudience| '')}><option value="">Todos os contextos</option>{expenseAudiences.map(a=><option key={a} value={a}>{audienceLabel(a)}</option>)}</select><select aria-label="Filtrar classificação" value={natureFilter} onChange={e=>setNatureFilter(e.target.value as ExpenseNature| '')}><option value="">Todas as classificações</option>{expenseNatures.map(a=><option key={a} value={a}>{natureLabel(a)}</option>)}</select><select aria-label="Filtrar categoria pessoal" value={personalFilter} onChange={e=>setPersonalFilter(e.target.value)}><option value="">Todas as categorias pessoais</option>{[...personalCategories,...personalAll.categories.map(c=>c.name).filter(c=>!personalCategories.includes(c as typeof personalCategories[number]))].map(c=><option key={c}>{c}</option>)}</select><select aria-label="Filtrar viagem" value={tripFilter} onChange={e=>setTripFilter(e.target.value)}><option value="">Todas as viagens / sem viagem</option>{tripNames.map(n=><option key={n}>{n}</option>)}</select></>}<input aria-label="Buscar lançamento" placeholder="Buscar descrição, carro, placa..." value={search} onChange={e=>setSearch(e.target.value)}/>{selected==='custos'&&<select aria-label="Filtrar tipo de custo" value={costGroup} onChange={e=>setCostGroup(e.target.value)}><option value="">Todos os custos</option>{['Custos loja','Custos variáveis','Pós-venda'].map(c=><option key={c}>{c}</option>)}</select>}{selected==='mensais'&&<select aria-label="Filtrar escopo das contas" value={scopeFilter} onChange={e=>setScopeFilter(e.target.value)}><option value="">Loja e pessoal</option><option value="LOJA">Loja</option><option value="PESSOAL">Pessoal</option></select>}</div>
   {selected==='mensais'?monthlyRows():selected==='vendas'?sheet(['Data','Carro','Placa','Vendedor','Dono / destino','Compra','Custo','Custo vendedor','Custo total','Venda','Lucro real','Recebido','Troca','Placa troca','Valor troca','Débitos troca','Troca líquida','Restante a pagar','Pagamento','Banco financiamento','Banco quitação'],e=>[dateLabel(e.entry_date),e.details.vehicle,e.details.plate||'—',e.details.seller||'—',<span key="owner">{e.details.sale_owner==='LOJA'?'Loja':e.details.sale_owner==='INVESTIDOR'?e.details.investor_name:'A conferir'}{e.details.trade_in&&<small>Troca: {e.details.trade_destination||'A conferir'} {e.details.trade_investor_name||''}</small>}{e.details.sale_mode==='REPASSE'&&<small>Repasse com resultado</small>}</span>,money(e.details.purchase_cents),money(e.details.vehicle_cost_cents),money(e.details.commission_cents),currency(saleCost(e)),money(e.details.sale_cents),<strong key="profit" className={saleProfit(e)<0?'bank-admin-negative':'bank-admin-positive'}>{currency(saleProfit(e))}</strong>,money(e.amount_cents),e.details.trade_vehicle||'—',e.details.trade_plate||'—',money(e.details.trade_value_cents),e.details.trade_in?currency(adminSaleSettlement(Number(e.details.sale_cents),e.details).debt):'—',e.details.trade_in?currency(adminSaleSettlement(Number(e.details.sale_cents),e.details).credit):'—',currency(adminSaleSettlement(Number(e.details.sale_cents),e.details).remaining),({PIX:'Pix',DINHEIRO:'Dinheiro',CARTAO:'Cartão',FINANCIAMENTO:'Financiamento',SEM_DIFERENCA:'Sem diferença'} as Record<string,string>)[e.details.payment_method||'']||e.details.payment_method||'—',e.details.payment_bank==='OUTRO'?e.details.payment_bank_other:e.details.payment_bank||'—',e.details.trade_payoff_bank==='OUTRO'?e.details.trade_payoff_bank_other:e.details.trade_payoff_bank||'—']):selected==='retornos'?sheet(['Data','Vendedor','Carro','Placa','Financiado','Retorno','Banco','Valor conta','Imposto','Valor final','Divide por 2¹','Lazinho / gerente','Vendedor repasse','Loja'],e=>[dateLabel(e.entry_date),e.details.seller||'—',e.details.vehicle,e.details.plate||'—',money(e.details.financed_cents),e.details.return_level||'—',e.details.bank||'—',money(e.amount_cents),money(e.details.tax_cents),currency(returnNet(e)),currency(Math.round(returnNet(e)/2)),money(e.details.manager_cents),money(e.details.seller_cents),currency(returnStore(e))]):selected==='trocas'?sheet(['Data','Troca','Placa','Valor pago','Débito troca','Doc. vendida','Pago CC','Desconto déb./doc./caixa','Divisão para cada²','Lucro para cada²'],e=>[dateLabel(e.entry_date),e.details.vehicle,e.details.plate||'—',money(e.details.paid_cents),money(e.details.debt_cents),money(e.details.document_cents),money(e.details.cc_cents),money(e.details.discount_cents),money(e.details.division_cents),money(e.details.profit_share_cents)]):basicSheet()}
   {selected==='retornos'&&<p className="bank-note">¹ “Divide por 2” é uma referência matemática do valor final. Os repasses são manuais. As regras de 70% e 90% do PDF aguardam confirmação e ainda não alteram nenhum valor.</p>}{selected==='trocas'&&<p className="bank-note">² Divisão e lucro por pessoa seguem os valores que você informar. A troca não movimenta o caixa automaticamente.</p>}
  </section>
  {reference&&<details className="bank-panel bank-admin-reference"><summary>Conferir modelos e fechamento original dos PDFs</summary><p>Referências de leitura, sem somar valores históricos ao caixa atual.</p><div className="bank-detail"><div><span>Entrada original</span><strong>{currency(reference.closing.income_cents)}</strong></div><div><span>Saída original</span><strong>{currency(reference.closing.expense_cents)}</strong></div><div><span>Subtotal informado no PDF</span><strong>{currency(reference.closing.subtotal_cents)}</strong></div><div><span>Subtotal calculado (entrada − saída)</span><strong>{currency(reference.closing.income_cents-reference.closing.expense_cents)}</strong></div><div><span>Retornos loja (referência)</span><strong>{currency(reference.closing.returns_cents)}</strong></div><div><span>Valor pessoal indicado no PDF</span><strong>{currency(reference.closing.personal_cents)}</strong></div></div><p className="bank-error">Diferença a conferir: {currency(Math.abs(reference.closing.subtotal_cents-(reference.closing.income_cents-reference.closing.expense_cents)))}. {reference.closing.period?`Período indicado: ${reference.closing.period}.`:'O mês do fechamento ainda não foi informado.'}</p>{reference.sources.map(s=><p key={s.file}><strong>{s.file}</strong> · {s.purpose}</p>)}</details>}
 </>;
}
