'use client';
import {useState,type ReactNode} from 'react';
import {brazilDay,currency} from '@/lib/icom-bank/model';
import type {AdminEntry,AdminReference} from '@/lib/icom-bank/administrative';
import type {AdminPreset} from './BankAdminForm';
import BankEntryOrigin from './BankEntryOrigin';
export default function BankMonthlyAgenda({rows,year,month,templates,archived,scope,search,onOpen,actions}:{rows:AdminEntry[];year:number;month:string;templates:AdminReference['monthly'];archived:boolean;scope:string;search:string;onOpen:(entry?:AdminEntry,preset?:AdminPreset)=>void;actions:(entry:AdminEntry)=>ReactNode}){
 const [day,setDay]=useState<number|null>(null),prefix=`${year}-${month}`,today=brazilDay();
 const numberMonth=Number(month),days=new Date(Date.UTC(year,numberMonth,0)).getUTCDate(),offset=new Date(Date.UTC(year,numberMonth-1,1)).getUTCDay();
 const ordered=[...rows].sort((a,b)=>a.entry_date.localeCompare(b.entry_date)||a.description.localeCompare(b.description,'pt-BR'));
 const availableTemplates=templates.filter(t=>!rows.some(r=>r.description===t.label));
 const visible=ordered.filter(e=>day===null||Number(e.entry_date.slice(8))===day);
 const dateFor=(n:number)=>`${prefix}-${String(n).padStart(2,'0')}`;
 return <div className="bank-month-agenda"><div className="bank-month-heading"><div><p className="bank-eyebrow">AGENDA DO MÊS</p><h3>{new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(Date.UTC(year,numberMonth-1,1)))}</h3><p>Clique em um dia para ver as contas. O contorno dourado indica hoje.</p></div><button type="button" aria-pressed={day===null} onClick={()=>setDay(null)}>Ver o mês todo</button></div><div className="bank-month-calendar" aria-label="Calendário das contas mensais">{['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'].map(d=><span className="bank-month-weekday" key={d}>{d}</span>)}{Array.from({length:offset},(_,i)=><span aria-hidden="true" key={'empty-'+i}/>)}{Array.from({length:days},(_,i)=>{
  const n=i+1,date=dateFor(n),items=ordered.filter(e=>e.entry_date===date),pending=items.some(e=>e.status==='PREVISTO'),incomplete=items.some(e=>e.amount_cents===null);
  return <button type="button" key={n} aria-pressed={day===n} aria-current={date===today?'date':undefined} aria-label={`Dia ${n}: ${items.length} conta(s)${pending?', com contas previstas':''}`} className={`bank-month-day ${date===today?'today':''} ${pending?'pending':''}`} onClick={()=>setDay(v=>v===n?null:n)}><strong>{String(n).padStart(2,'0')}</strong><span>{items.length?`${items.length} conta${items.length===1?'':'s'}`:'—'}</span>{items.length>0&&<small>{incomplete?'Valor a conferir':currency(items.reduce((sum,e)=>sum+(e.amount_cents||0),0))}</small>}</button>;
 })}</div><div className="bank-month-list-heading"><h3>{day===null?'Contas deste mês':`Contas do dia ${String(day).padStart(2,'0')}`}</h3><span>{visible.length} lançamento(s)</span></div><div className="bank-table"><table><thead><tr>{['Dia','Conta','Área','Valor','Situação','Ações'].map(t=><th scope="col" key={t}>{t}</th>)}</tr></thead><tbody>{visible.map(e=><tr key={e.id}><td><span className="bank-month-due">{e.entry_date.slice(8)}</span></td><td><strong>{e.description}</strong><BankEntryOrigin entry={e}/></td><td>{e.scope==='LOJA'?'Loja':'Pessoal'}</td><td>{e.amount_cents===null?'Não informado':currency(e.amount_cents)}</td><td><span className={`bank-pill ${e.status==='REALIZADO'?'green':'gold'}`}>{e.status==='REALIZADO'?'Realizado':'Previsto'}</span></td><td>{actions(e)}</td></tr>)}{!visible.length&&<tr><td colSpan={6}><div className="bank-empty">Nenhuma conta {day===null?'neste mês':`no dia ${day}`}. Use Novo lançamento para cadastrar.</div></td></tr>}</tbody></table></div>{!archived&&availableTemplates.length>0&&<details className="bank-month-templates"><summary>Usar uma conta do modelo original</summary><p>São sugestões, ainda sem valor registrado neste mês.</p><div className="bank-actions">{availableTemplates.filter(t=>!search||t.label.toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR'))).map(t=><button type="button" key={t.label} onClick={()=>onOpen(undefined,{kind:'MENSAL',date:dateFor(Math.min(t.due_day,days)),description:t.label,due_day:t.due_day,scope:scope==='PESSOAL'?'PESSOAL':scope==='LOJA'?'LOJA':undefined})}>Dia {String(t.due_day).padStart(2,'0')} · {t.label}</button>)}</div></details>}</div>;
}
