'use client';
import {useState} from 'react';
import {bankPath} from '@/lib/icom-bank/model';
import {bankSafeFetch} from '@/lib/icom-bank/deletion-client';
export default function BankContractActions({id,status,updatedAt,canEdit,canCancel,initialCancel=false}:{id:string;status:string;updatedAt:string;canEdit:boolean;canCancel:boolean;initialCancel?:boolean}){
 const [open,setOpen]=useState(initialCancel),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 if(status!=='ATIVO')return <p className="bank-note">{status==='CANCELADO'?'Venda cancelada: mantida apenas no histórico.':'Venda encerrada. Revise os recebimentos antes de editar ou cancelar.'}</p>;
 return <section className="bank-panel bank-sale-actions"><div className="bank-actions">{canEdit&&<a className="bank-primary" href={bankPath('/contratos/'+id+'/editar')}>Editar pedido</a>}{canCancel&&<button className="bank-danger-action" disabled={busy} type="button" onClick={()=>setOpen(true)}>Cancelar venda</button>}</div>{open&&canCancel&&<form className="bank-cancel-order" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await bankSafeFetch(bankPath('/api/contracts'),{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'cancel',id,expected_updated_at:updatedAt,reason})}),d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error||'Não foi possível cancelar.');location.reload();}catch(e){setError(e instanceof Error?e.message:'Não foi possível cancelar.');}finally{setBusy(false);}}}><h2>Cancelar esta venda?</h2><p>Ela sairá da carteira ativa e suas parcelas em aberto serão canceladas. O pedido e o histórico ficarão preservados. A confirmação exige a senha de exclusão.</p><label>Motivo<textarea required minLength={3} maxLength={1000} disabled={busy} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Ex.: pedido de teste"/></label><div className="bank-actions"><button type="button" disabled={busy} onClick={()=>setOpen(false)}>Voltar sem cancelar</button><button className="bank-danger-action" disabled={busy}>{busy?'Verificando…':'CONFIRMAR CANCELAMENTO'}</button></div></form>}{error&&<p className="bank-error" role="alert">{error}</p>}</section>;
}
