'use client';
import {useEffect,useRef,useState} from 'react';
import BankExpenseForm from './BankExpenseForm';
import {bankPath,brazilDay,currency} from '@/lib/icom-bank/model';
import {adminStats} from '@/lib/icom-bank/administrative';
import {payableExisting,payableLabels,payableMethods,payableState,payableStats,agendaStats,agendaMatches,addPayableDays,payablePeople,type AgendaView,type Payable,type PayablesData,type PayableFile,type PayableHistory} from '@/lib/icom-bank/payables';
import type {StockRow} from '@/lib/icom-bank/stock';
const day=(value:string|null)=>value?value.split('-').reverse().join('/'):'Não definido';
const methods:Record<string,string>={PIX:'Pix',DINHEIRO:'Dinheiro',CARTAO:'Cartão',TRANSFERENCIA:'Transferência',BOLETO:'Boleto'};
const name=(s:StockRow|undefined)=>s?[s.vehicle.brand,s.vehicle.model,s.vehicle.version,s.vehicle.year].filter(Boolean).join(' '):'Veículo';
function PayableForm({p,s,data,action,onCancel,onSaved}:{p:Payable;s?:StockRow;data:PayablesData;action:'schedule'|'pay'|'reverse';onCancel:()=>void;onSaved:(message:string)=>void}){
 const [due,setDue]=useState(p.due_date||''),[notes,setNotes]=useState(p.notes),[date,setDate]=useState(brazilDay()),[method,setMethod]=useState('PIX'),[confirmed,setConfirmed]=useState(false),[reason,setReason]=useState(''),[existing,setExisting]=useState(''),[mode,setMode]=useState('new'),[file,setFile]=useState<File|null>(null),[receipt,setReceipt]=useState<string|null>(null),[fileId,setFileId]=useState(''),[requestId]=useState(()=>crypto.randomUUID()),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const candidates=payableExisting(p,s,data.entries,data.rows);
 async function submit(values:FormData){setBusy(true);setError('');try{
  let receiptId=receipt;
  if(action==='pay'&&file&&!receiptId){const form=new FormData();form.set('id',fileId);form.set('bill',p.id);form.set('file',file);const r=await fetch(bankPath('/api/payables/files'),{method:'POST',body:form}),result=await r.json() as {id?:string;error?:string};if(!r.ok||!result.id)throw new Error(result.error||'Não foi possível anexar o comprovante.');receiptId=result.id;setReceipt(receiptId);}
  const body={id:p.id,expected_updated_at:p.updated_at,action,due_date:String(values.get('due_date')||'')||null,notes,paid_at:mode==='existing'?date:String(values.get('paid_at')||date),method,confirmed,reason,receipt_id:receiptId,request_id:requestId,existing_id:mode==='existing'?existing:null};
  const r=await fetch(bankPath('/api/payables'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),result=await r.json() as {error?:string};if(!r.ok)throw new Error(result.error||'Não foi possível salvar.');
  onSaved(action==='schedule'?'Vencimento salvo. O caixa permanece igual.':action==='reverse'?'Baixa desfeita. A saída foi arquivada e a conta voltou a ficar pendente.':mode==='existing'?'Pagamento vinculado à saída existente, sem criar outra saída.':'Pagamento confirmado. A saída foi registrada uma única vez no caixa.');
 }catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.');}finally{setBusy(false);}}
 return <form className="bank-panel bank-payable-form" onSubmit={e=>{e.preventDefault();void submit(new FormData(e.currentTarget));}}><div className="bank-panel-title"><div><p className="bank-eyebrow">{s?.plate||p.title} · {p.scope==='PESSOAL'?'Pessoal':payableLabels[p.kind]}</p><h2>{action==='schedule'?'Definir vencimento':action==='reverse'?'Desfazer baixa':'Confirmar pagamento'}</h2><p>{s?name(s):p.scope==='PESSOAL'?payablePeople[p.person||'AMBOS']:'Loja'}</p></div><strong>{currency(Number(p.amount_cents))}</strong></div>
 <fieldset disabled={busy}><div className="bank-form-grid">
 {action==='schedule'?<><label>Vencimento<input name="due_date" required={!p.stock_id} type="date" min="2000-01-01" max="2100-12-31" value={due} onChange={e=>setDue(e.target.value)}/><small>Para débitos de veículo, deixe vazio se ainda não souber a data.</small></label><label>Observações<textarea maxLength={2000} rows={3} value={notes} onChange={e=>setNotes(e.target.value)}/></label></>:action==='reverse'?<label>Motivo da correção<textarea required minLength={3} maxLength={1000} rows={3} value={reason} onChange={e=>setReason(e.target.value)}/></label>:<>
 <label>Como registrar no caixa<select value={mode} onChange={e=>{setMode(e.target.value);setExisting('');setConfirmed(false);}}><option value="new">Criar saída para este pagamento</option><option value="existing" disabled={!candidates.length}>Vincular saída já lançada</option></select><small>A vinculação exige mesmo valor, data e forma de pagamento.</small></label>
 {mode==='existing'&&<label>Saída já registrada<select value={existing} required onChange={e=>{setExisting(e.target.value);const entry=candidates.find(x=>x.id===e.target.value);if(entry){setDate(entry.entry_date);setMethod(entry.details.payment_method!);}}}><option value="">Selecione a saída correspondente</option>{candidates.map(e=><option key={e.id} value={e.id}>{day(e.entry_date)} · {e.description} · {currency(Number(e.amount_cents))}</option>)}</select></label>}
 <label>Data do pagamento<input name="paid_at" type="date" required min={s?.entry_date||'2000-01-01'} max={brazilDay()} value={date} disabled={mode==='existing'} onChange={e=>setDate(e.target.value)}/></label>
 <label>Forma de pagamento<select value={method} disabled={mode==='existing'} onChange={e=>setMethod(e.target.value)}>{payableMethods.map(m=><option value={m} key={m}>{methods[m]}</option>)}</select></label>
 <label>Comprovante (opcional)<input type="file" accept=".jpg,.jpeg,.png,.pdf" onChange={e=>{setFile(e.target.files?.[0]||null);setFileId(crypto.randomUUID());setReceipt(null);}}/><small>JPG, PNG ou PDF de até 10 MB. Acesso reservado ao proprietário.</small></label>
 </>}
 </div>
 {action==='pay'&&<><p className="bank-note">A baixa registra um pagamento que você já realizou. O sistema não transfere dinheiro. {p.stock_id?'O valor fica vinculado à placa e não será somado novamente ao custo do carro.':p.scope==='PESSOAL'?'A saída será registrada no pessoal, separada das despesas da loja.':'A saída será registrada nas despesas da loja.'}</p><label className="bank-checkbox"><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Confirmei que o pagamento de {currency(Number(p.amount_cents))} foi realizado.</label></>}
 {action==='reverse'&&<p className="bank-note">A saída vinculada será arquivada e sairá dos totais realizados. A conta voltará a ficar pendente; o motivo, a baixa anterior e os comprovantes permanecerão no histórico.</p>}
 <div className="bank-actions"><button type="button" onClick={onCancel}>Cancelar</button><button className="bank-primary" disabled={busy||action==='pay'&&(!confirmed||mode==='existing'&&!existing)}>{busy?'Salvando…':action==='schedule'?'SALVAR VENCIMENTO':action==='reverse'?'CONFIRMAR CORREÇÃO':`CONFIRMAR BAIXA · ${currency(Number(p.amount_cents))}`}</button></div></fieldset>{error&&<p className="bank-error" role="alert">{error}</p>}</form>;
}
const viewLabels:Record<AgendaView,string>={attention:'Prioridades · atrasadas e próximos 7 dias',overdue:'Em atraso',today:'Vencem hoje',week:'Próximos 7 dias',month:'Vencimentos do mês',day:'Uma data específica',all:'Todas as contas ativas',paid:'Pagas no mês',archived:'Arquivadas'};
const titleOf=(p:Payable,s?:StockRow)=>p.stock_id?`${payableLabels[p.kind]} · ${s?.plate||'Veículo'}`:p.title||'Conta';
const areaOf=(p:Payable)=>p.scope==='PESSOAL'?`Pessoal · ${payablePeople[p.person||'AMBOS']}`:p.stock_id?'Loja · débito de veículo':'Loja';
export default function BankPayables({initial}:{initial:PayablesData}){
 const today=brazilDay(),[data,setData]=useState(initial),[month,setMonth]=useState(today.slice(0,7)),[search,setSearch]=useState(''),[scope,setScope]=useState('all'),[person,setPerson]=useState('all'),[view,setView]=useState<AgendaView>('attention'),[selectedDay,setSelectedDay]=useState(today),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[form,setForm]=useState<{id:string;action:'schedule'|'pay'|'reverse'}|null>(null),[expense,setExpense]=useState<string|null>(null),[archive,setArchive]=useState<Payable|null>(null),[history,setHistory]=useState<{id:string;rows:PayableHistory[];files:PayableFile[]}|null>(null);
 const formRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(form||expense!==null||archive)formRef.current?.scrollIntoView({behavior:'smooth',block:'start'});},[form,expense,archive]);
 const stocks=new Map(data.stock.map(s=>[s.id,s])),stockOf=(p:Payable)=>p.stock_id?stocks.get(p.stock_id):undefined;
 const scoped=data.rows.filter(p=>(scope==='all'||scope==='LOJA'&&p.scope!=='PESSOAL'||scope==='PESSOAL'&&p.scope==='PESSOAL'||scope==='trade'&&!!p.stock_id)&&(scope!=='PESSOAL'||person==='all'||p.person===person));
 const stats=agendaStats(scoped,data.stock,month,today),allStats=agendaStats(data.rows,data.stock,month,today),legacy=payableStats(data.rows,data.stock,month,today),cash=adminStats(data.entries,month),selected=form&&data.rows.find(p=>p.id===form.id),editBill=expense&&data.rows.find(p=>p.id===expense);
 const list=scoped.filter(p=>agendaMatches(p,stockOf(p),view,month,selectedDay,today)&&(!search||`${titleOf(p,stockOf(p))} ${name(stockOf(p))} ${p.bank} ${p.notes} ${areaOf(p)}`.toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR')))).sort((a,b)=>(view==='paid'?(b.paid_at||'').localeCompare(a.paid_at||''):(a.due_date||'9999').localeCompare(b.due_date||'9999'))||titleOf(a,stockOf(a)).localeCompare(titleOf(b,stockOf(b))));
 function closeForms(){setForm(null);setExpense(null);setArchive(null);setHistory(null);}
 async function refresh(message=''){setBusy(true);setError('');try{const r=await fetch(bankPath('/api/payables')),result=await r.json() as PayablesData&{error?:string};if(!r.ok||!Array.isArray(result.rows))throw new Error(result.error||'Não foi possível atualizar.');setData(result);closeForms();if(message)setNotice(message);}catch(e){setError(e instanceof Error?e.message:'Não foi possível atualizar.');}finally{setBusy(false);}}
 async function showHistory(p:Payable){setBusy(true);setError('');try{const r=await fetch(bankPath('/api/payables?id='+p.id)),result=await r.json() as {history:PayableHistory[];files:PayableFile[];error?:string};if(!r.ok)throw new Error(result.error||'Não foi possível abrir o histórico.');closeForms();setHistory({id:p.id,rows:result.history,files:result.files});}catch(e){setError(e instanceof Error?e.message:'Não foi possível abrir.');}finally{setBusy(false);}}
 async function toggleArchive(p:Payable){setBusy(true);setError('');try{const r=await fetch(bankPath('/api/payables'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'archive',id:p.id,expected_updated_at:p.updated_at,active:!p.active})}),result=await r.json() as {error?:string};if(!r.ok)throw new Error(result.error||'Não foi possível atualizar a conta.');await refresh(p.active?'Conta arquivada. Os outros meses permanecem cadastrados.':'Conta restaurada na agenda.');}catch(e){setError(e instanceof Error?e.message:'Não foi possível atualizar.');}finally{setBusy(false);}}
 function openForm(p:Payable,action:'schedule'|'pay'|'reverse'){closeForms();setForm({id:p.id,action});}
 const cards=[{key:'overdue' as const,label:'EM ATRASO',tone:'red',hint:'Vencimento anterior a hoje'},{key:'today' as const,label:'VENCEM HOJE',tone:'gold',hint:day(today)},{key:'week' as const,label:'PRÓXIMOS 7 DIAS',tone:'navy',hint:`Até ${day(addPayableDays(today,7))}`},{key:'month' as const,label:'A PAGAR NO MÊS',tone:'green',hint:month.split('-').reverse().join('/')}];
 return <><div className="bank-heading"><div><p className="bank-eyebrow">ADMINISTRATIVO · AGENDA DE PAGAMENTOS</p><h1>Contas a pagar</h1><p>{new Date(today+'T12:00:00Z').toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long',year:'numeric',timeZone:'America/Sao_Paulo'})} · Veja o que precisa pagar, dia a dia.</p></div><span className="bank-pill gold">Acesso do proprietário</span></div>
 <div className="bank-actions"><a href={bankPath('/administrativo')}>← Administrativo</a><a href={bankPath('/administrativo/contas-a-receber')}>Contas a receber</a><button type="button" className="bank-primary" disabled={busy} onClick={()=>{closeForms();setExpense('new');}}>+ Cadastrar conta</button><button type="button" disabled={busy} onClick={()=>void refresh()}>Atualizar lista</button></div>
 <div className="bank-agenda-tabs" role="group" aria-label="Área das contas">{[['all','Todas'],['LOJA','Loja'],['PESSOAL','Pessoal · Bruno e Gisela'],['trade','Débitos de veículos']].map(([value,label])=><button type="button" aria-pressed={scope===value} className={scope===value?'bank-agenda-selected':''} key={value} onClick={()=>setScope(value)}>{label}</button>)}</div>
 {scope==='PESSOAL'&&<label className="bank-agenda-person">Mostrar contas de<select value={person} onChange={e=>setPerson(e.target.value)}><option value="all">Bruno e Gisela · todas</option>{Object.entries(payablePeople).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
 <div className="bank-kpis bank-payable-kpis">{cards.map(c=><button type="button" className={'bank-kpi bank-agenda-card '+c.tone} key={c.key} aria-pressed={view===c.key} onClick={()=>setView(c.key)}><span>{c.label}</span><strong>{currency(stats[c.key].amount)}</strong><small>{stats[c.key].count} conta(s) · {c.hint}</small></button>)}</div>
 {stats.overdue.count>0&&<div className="bank-payable-warning bank-agenda-alert" role="status"><strong>Atenção: {stats.overdue.count} conta(s) em atraso · {currency(stats.overdue.amount)}</strong><button type="button" onClick={()=>setView('overdue')}>Ver contas atrasadas</button></div>}
 <section className="bank-panel"><div className="bank-panel-title"><div><h2>Agenda dos próximos dias</h2><p>Clique em um dia para ver as contas. Valores conforme a área selecionada.</p></div></div><div className="bank-agenda-days">{Array.from({length:8},(_,i)=>addPayableDays(today,i)).map((date,i)=>{const rows=scoped.filter(p=>agendaMatches(p,stockOf(p),'day',month,date,today)&&payableState(p,stockOf(p),today)!=='Origem prevista');return <button type="button" className={view==='day'&&selectedDay===date?'bank-agenda-selected':''} key={date} onClick={()=>{setSelectedDay(date);setView('day');}}><small>{i===0?'HOJE':new Date(date+'T12:00:00Z').toLocaleDateString('pt-BR',{weekday:'short',timeZone:'America/Sao_Paulo'})}</small><strong>{day(date).slice(0,5)}</strong><span>{rows.length} conta(s)</span><b>{currency(rows.reduce((n,p)=>n+Number(p.amount_cents),0))}</b></button>;})}</div></section>
 {notice&&<p className="bank-note" role="status">{notice}</p>}{error&&<p className="bank-error" role="alert">{error}</p>}
 <div ref={formRef} className="bank-agenda-form-anchor">{expense!==null&&<BankExpenseForm key={expense} bill={editBill||undefined} defaultScope={scope==='PESSOAL'?'PESSOAL':'LOJA'} onCancel={()=>setExpense(null)} onSaved={message=>void refresh(message)}/>}{selected&&form&&<PayableForm key={selected.id+form.action+selected.updated_at} p={selected} s={stockOf(selected)} data={data} action={form.action} onCancel={()=>setForm(null)} onSaved={message=>void refresh(message)}/>}
 {archive&&<section className="bank-panel"><h2>{archive.active?'Arquivar':'Restaurar'} · {titleOf(archive)}</h2><p>{archive.active?'Este vencimento sairá da agenda ativa. Nenhum pagamento será registrado e os outros meses permanecerão cadastrados.':'Este vencimento voltará à agenda de contas pendentes.'}</p><div className="bank-actions"><button type="button" onClick={()=>setArchive(null)}>Cancelar</button><button type="button" disabled={busy} className="bank-primary" onClick={()=>void toggleArchive(archive)}>{busy?'Salvando…':archive.active?'CONFIRMAR ARQUIVAMENTO':'RESTAURAR CONTA'}</button></div></section>}</div>
 {history&&<section className="bank-panel"><div className="bank-panel-title"><h2>Histórico · {titleOf(data.rows.find(p=>p.id===history.id)!,stocks.get(data.rows.find(p=>p.id===history.id)?.stock_id||''))}</h2><button onClick={()=>setHistory(null)}>Fechar histórico</button></div><p>Alterações, baixas e comprovantes anteriores são preservados.</p><ol className="bank-payable-history">{history.rows.map(h=><li key={h.id}><strong>{h.next.action==='BAIXA_DESFEITA'?'Correção de baixa':!h.previous?'Conta registrada':h.previous.active!==h.next.active?(h.next.active?'Conta restaurada':'Conta arquivada'):h.previous.status!==h.next.status?(h.next.status==='PAGO'?'Pagamento confirmado':'Conta reaberta'):h.previous.amount_cents!==h.next.amount_cents?'Valor atualizado':'Vencimento / dados atualizados'}</strong><small>{new Date(h.created_at).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}</small>{h.next.reason&&<p>{h.next.reason}</p>}{h.next.amount_cents!==undefined&&<p>{currency(Number(h.next.amount_cents))} · {h.next.status==='PAGO'?`Pago em ${day(h.next.paid_at||null)} · ${methods[h.next.method||'']||'—'}`:`Vencimento: ${day(h.next.due_date||null)}`}</p>}</li>)}</ol><h3>Comprovantes anexados</h3>{history.files.length?history.files.map(f=><p key={f.id}><a href={bankPath('/api/payables/files/'+f.id)}>Baixar comprovante · {new Date(f.created_at).toLocaleString('pt-BR')}</a></p>):<p>Nenhum comprovante anexado.</p>}</section>}
 <section className="bank-panel"><div className="bank-panel-title"><div><h2>{viewLabels[view]}</h2><p>{list.length} conta(s) · por ordem de vencimento</p></div><label>Mês de referência<input type="month" min="2000-01" max="2100-12" value={month} onChange={e=>{if(e.target.value){setMonth(e.target.value);setView('month');}}}/></label></div><div className="bank-filters"><input aria-label="Buscar conta" placeholder="Buscar nome, pessoa, carro ou placa" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Mostrar contas" value={view} onChange={e=>setView(e.target.value as AgendaView)}>{Object.entries(viewLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>{view==='day'&&<input aria-label="Dia da agenda" type="date" min="2000-01-01" max="2100-12-31" value={selectedDay} onChange={e=>setSelectedDay(e.target.value)}/>}</div>
 <div className="bank-table bank-admin-sheet"><table><thead><tr><th>Vencimento</th><th>Conta / identificação</th><th>Valor</th><th>Situação</th><th>Pagamento</th><th>Ações</th></tr></thead><tbody>{list.map(p=>{const s=stockOf(p),state=payableState(p,s,today),canPay=p.active&&(!p.stock_id||s?.active&&s.status!=='PREVISTO');return <tr key={p.id} className={state==='Vencido'?'bank-agenda-overdue':state==='Vence hoje'?'bank-agenda-today':''}><td><strong className="bank-agenda-date">{day(p.due_date)}</strong>{state==='Vencido'&&<small>Pagamento em atraso</small>}{p.series_id&&<small>Mensal · {p.series_index}/{p.series_count}</small>}</td><td><strong>{titleOf(p,s)}</strong><small>{areaOf(p)}</small>{s&&<small>{name(s)}</small>}{p.bank&&<small>{p.bank}</small>}{p.notes&&<small>{p.notes}</small>}</td><td><strong>{currency(Number(p.amount_cents))}</strong></td><td><span className={'bank-pill '+(state==='Pago'?'green':state==='Vencido'?'red':'gold')}>{state}</span></td><td>{p.status==='PAGO'?<>{day(p.paid_at)}<small>{methods[p.method||'']}</small>{p.receipt_id&&<a href={bankPath('/api/payables/files/'+p.receipt_id)}>Comprovante</a>}</>:'Ainda não pago'}</td><td><div className="bank-admin-row-actions">{p.active&&p.status==='PENDENTE'&&<button disabled={busy} onClick={()=>{if(p.stock_id)openForm(p,'schedule');else{closeForms();setExpense(p.id);}}}>{p.stock_id?'Definir vencimento':'Editar conta'}</button>}{p.status==='PENDENTE'&&p.active&&<button disabled={busy||!canPay} onClick={()=>openForm(p,'pay')}>Confirmar pagamento</button>}{p.active&&p.status==='PAGO'&&<button disabled={busy} onClick={()=>openForm(p,'reverse')}>Desfazer baixa</button>}{!p.stock_id&&p.status==='PENDENTE'&&<button disabled={busy} onClick={()=>{closeForms();setArchive(p);}}>{p.active?'Arquivar':'Restaurar'}</button>}<button disabled={busy} onClick={()=>void showHistory(p)}>Histórico</button></div></td></tr>;})}{!list.length&&<tr><td colSpan={6}><div className="bank-empty">Nenhuma conta neste filtro. Use “Cadastrar conta” para lançar contas da loja ou pessoais, ou selecione “Todas as contas ativas” para ver outros vencimentos.</div></td></tr>}</tbody></table></div>{allStats.noDate>0&&<p className="bank-payable-warning">{allStats.noDate} débito(s) de veículo sem vencimento. Defina as datas para aparecerem na agenda do dia.</p>}{legacy.planned>0&&<p className="bank-note">{legacy.planned} débito(s) de origem prevista: o pagamento será liberado quando a venda de origem estiver realizada.</p>}</section>
 <section className="bank-panel"><div className="bank-panel-title"><div><h2>Resumo do mês · loja e pessoal separados</h2><p>Referência {month.split('-').reverse().join('/')} · considera todas as contas, independentemente do filtro acima.</p></div></div><div className="bank-mini"><article><span>Entradas realizadas · loja</span><strong>{currency(cash.income)}</strong></article><article><span>Saídas realizadas · loja</span><strong>{currency(cash.expenses)}</strong></article><article><span>Saldo dos lançamentos · loja</span><strong>{currency(cash.balance)}</strong></article><article><span>A pagar no mês · loja</span><strong>{currency(allStats.store)}</strong></article><article><span>Saídas realizadas · pessoal</span><strong>{currency(cash.personal)}</strong></article><article><span>A pagar no mês · pessoal</span><strong>{currency(allStats.personal)}</strong></article></div><p className="bank-note">Cadastrar contas não altera o caixa. Somente pagamentos confirmados entram nas saídas realizadas. Este resumo usa os registros do sistema e não representa o saldo da conta bancária.</p>{cash.missing>0&&<p className="bank-error">Resumo parcial: {cash.missing} lançamento(s) realizado(s) sem valor.</p>}</section></>;
}
