'use client';
import {useState} from 'react';
import {bankPath,brazilDay,currency} from '@/lib/icom-bank/model';
import {adminStats} from '@/lib/icom-bank/administrative';
import {payableExisting,payableLabels,payableMethods,payableState,payableStats,type Payable,type PayablesData,type PayableFile,type PayableHistory} from '@/lib/icom-bank/payables';
import type {StockRow} from '@/lib/icom-bank/stock';
const day=(value:string|null)=>value?value.split('-').reverse().join('/'):'Não definido';
const methods:Record<string,string>={PIX:'Pix',DINHEIRO:'Dinheiro',CARTAO:'Cartão',TRANSFERENCIA:'Transferência',BOLETO:'Boleto'};
const name=(s:StockRow|undefined)=>s?[s.vehicle.brand,s.vehicle.model,s.vehicle.version,s.vehicle.year].filter(Boolean).join(' '):'Veículo';
function PayableForm({p,s,data,action,onCancel,onSaved}:{p:Payable;s:StockRow;data:PayablesData;action:'schedule'|'pay'|'reverse';onCancel:()=>void;onSaved:(message:string)=>void}){
 const [due,setDue]=useState(p.due_date||''),[notes,setNotes]=useState(p.notes),[date,setDate]=useState(brazilDay()),[method,setMethod]=useState('PIX'),[confirmed,setConfirmed]=useState(false),[reason,setReason]=useState(''),[existing,setExisting]=useState(''),[mode,setMode]=useState('new'),[file,setFile]=useState<File|null>(null),[receipt,setReceipt]=useState<string|null>(null),[fileId,setFileId]=useState(''),[requestId]=useState(()=>crypto.randomUUID()),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const candidates=payableExisting(p,s,data.entries,data.rows);
 async function submit(values:FormData){setBusy(true);setError('');try{
  let receiptId=receipt;
  if(action==='pay'&&file&&!receiptId){const form=new FormData();form.set('id',fileId);form.set('bill',p.id);form.set('file',file);const r=await fetch(bankPath('/api/payables/files'),{method:'POST',body:form}),result=await r.json() as {id?:string;error?:string};if(!r.ok||!result.id)throw new Error(result.error||'Não foi possível anexar o comprovante.');receiptId=result.id;setReceipt(receiptId);}
  const body={id:p.id,expected_updated_at:p.updated_at,action,due_date:String(values.get('due_date')||'')||null,notes,paid_at:mode==='existing'?date:String(values.get('paid_at')||date),method,confirmed,reason,receipt_id:receiptId,request_id:requestId,existing_id:mode==='existing'?existing:null};
  const r=await fetch(bankPath('/api/payables'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),result=await r.json() as {error?:string};if(!r.ok)throw new Error(result.error||'Não foi possível salvar.');
  onSaved(action==='schedule'?'Vencimento salvo. O caixa permanece igual.':action==='reverse'?'Baixa desfeita. A saída foi arquivada e a conta voltou a ficar pendente.':mode==='existing'?'Pagamento vinculado à saída existente, sem criar outra saída.':'Pagamento confirmado. A saída foi registrada uma única vez no caixa.');
 }catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.');}finally{setBusy(false);}}
 return <form className="bank-panel bank-payable-form" onSubmit={e=>{e.preventDefault();void submit(new FormData(e.currentTarget));}}><div className="bank-panel-title"><div><p className="bank-eyebrow">{s.plate} · {payableLabels[p.kind]}</p><h2>{action==='schedule'?'Definir vencimento':action==='reverse'?'Desfazer baixa':'Confirmar pagamento'}</h2><p>{name(s)}</p></div><strong>{currency(Number(p.amount_cents))}</strong></div>
 <fieldset disabled={busy}><div className="bank-form-grid">
 {action==='schedule'?<><label>Vencimento<input name="due_date" type="date" min="2000-01-01" max="2100-12-31" value={due} onChange={e=>setDue(e.target.value)}/><small>Deixe vazio se ainda não souber a data.</small></label><label>Observações<textarea maxLength={2000} rows={3} value={notes} onChange={e=>setNotes(e.target.value)}/></label></>:action==='reverse'?<label>Motivo da correção<textarea required minLength={3} maxLength={1000} rows={3} value={reason} onChange={e=>setReason(e.target.value)}/></label>:<>
 <label>Como registrar no caixa<select value={mode} onChange={e=>{setMode(e.target.value);setExisting('');setConfirmed(false);}}><option value="new">Criar saída para este pagamento</option><option value="existing" disabled={!candidates.length}>Vincular saída já lançada</option></select><small>A vinculação exige mesmo valor, data e forma de pagamento.</small></label>
 {mode==='existing'&&<label>Saída já registrada<select value={existing} required onChange={e=>{setExisting(e.target.value);const entry=candidates.find(x=>x.id===e.target.value);if(entry){setDate(entry.entry_date);setMethod(entry.details.payment_method!);}}}><option value="">Selecione a saída correspondente</option>{candidates.map(e=><option key={e.id} value={e.id}>{day(e.entry_date)} · {e.description} · {currency(Number(e.amount_cents))}</option>)}</select></label>}
 <label>Data do pagamento<input name="paid_at" type="date" required min={s.entry_date} max={brazilDay()} value={date} disabled={mode==='existing'} onChange={e=>setDate(e.target.value)}/></label>
 <label>Forma de pagamento<select value={method} disabled={mode==='existing'} onChange={e=>setMethod(e.target.value)}>{payableMethods.map(m=><option value={m} key={m}>{methods[m]}</option>)}</select></label>
 <label>Comprovante (opcional)<input type="file" accept=".jpg,.jpeg,.png,.pdf" onChange={e=>{setFile(e.target.files?.[0]||null);setFileId(crypto.randomUUID());setReceipt(null);}}/><small>JPG, PNG ou PDF de até 10 MB. Acesso reservado ao proprietário.</small></label>
 </>}
 </div>
 {action==='pay'&&<><p className="bank-note">A baixa registra um pagamento que você já realizou. O sistema não transfere dinheiro. O valor fica vinculado à placa e não será somado novamente ao custo de aquisição ou preparação do carro.</p><label className="bank-checkbox"><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Confirmei que o pagamento de {currency(Number(p.amount_cents))} foi realizado.</label></>}
 {action==='reverse'&&<p className="bank-note">A saída vinculada será arquivada e sairá dos totais realizados. A conta voltará a ficar pendente; o motivo, a baixa anterior e os comprovantes permanecerão no histórico.</p>}
 <div className="bank-actions"><button type="button" onClick={onCancel}>Cancelar</button><button className="bank-primary" disabled={busy||action==='pay'&&(!confirmed||mode==='existing'&&!existing)}>{busy?'Salvando…':action==='schedule'?'SALVAR VENCIMENTO':action==='reverse'?'CONFIRMAR CORREÇÃO':`CONFIRMAR BAIXA · ${currency(Number(p.amount_cents))}`}</button></div></fieldset>{error&&<p className="bank-error" role="alert">{error}</p>}</form>;
}
export default function BankPayables({initial}:{initial:PayablesData}){
 const [data,setData]=useState(initial),[month,setMonth]=useState(brazilDay().slice(0,7)),[search,setSearch]=useState(''),[filter,setFilter]=useState('pending'),[dueFilter,setDueFilter]=useState('all'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[form,setForm]=useState<{id:string;action:'schedule'|'pay'|'reverse'}|null>(null),[history,setHistory]=useState<{id:string;rows:PayableHistory[];files:PayableFile[]}|null>(null);
 const stocks=new Map(data.stock.map(s=>[s.id,s])),stats=payableStats(data.rows,data.stock,month),cash=adminStats(data.entries,month),selected=form&&data.rows.find(p=>p.id===form.id),vehicle=selected&&stocks.get(selected.stock_id);
 const list=data.rows.filter(p=>{const s=stocks.get(p.stock_id),state=payableState(p,s);return (filter==='all'||filter==='pending'&&p.active&&p.status==='PENDENTE'||filter==='paid'&&state==='Pago'||filter==='overdue'&&state==='Vencido'||filter==='archived'&&state==='Arquivado')&&(filter==='archived'||p.active)&&(!search||`${s?.plate||''} ${name(s)} ${payableLabels[p.kind]} ${p.bank}`.toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR')))&&(dueFilter==='all'||p.due_date?.startsWith(month));}).sort((a,b)=>(a.due_date||'9999').localeCompare(b.due_date||'9999')||a.kind.localeCompare(b.kind));
 async function refresh(message=''){setBusy(true);setError('');try{const r=await fetch(bankPath('/api/payables')),result=await r.json() as PayablesData&{error?:string};if(!r.ok||!Array.isArray(result.rows))throw new Error(result.error||'Não foi possível atualizar.');setData(result);setForm(null);setHistory(null);if(message)setNotice(message);}catch(e){setError(e instanceof Error?e.message:'Não foi possível atualizar.');}finally{setBusy(false);}}
 async function showHistory(p:Payable){setBusy(true);setError('');try{const r=await fetch(bankPath('/api/payables?id='+p.id)),result=await r.json() as {history:PayableHistory[];files:PayableFile[];error?:string};if(!r.ok)throw new Error(result.error||'Não foi possível abrir o histórico.');setHistory({id:p.id,rows:result.history,files:result.files});setForm(null);}catch(e){setError(e instanceof Error?e.message:'Não foi possível abrir.');}finally{setBusy(false);}}
 return <><div className="bank-heading"><div><p className="bank-eyebrow">ADMINISTRATIVO · DÉBITOS DAS TROCAS</p><h1>Contas a pagar</h1><p>Organize os vencimentos e confirme as saídas já realizadas.</p></div><span className="bank-pill gold">Acesso do proprietário</span></div>
 <div className="bank-actions"><a href={bankPath('/administrativo')}>← Administrativo</a><a href={bankPath('/veiculos')}>Ver carros recebidos</a><button type="button" disabled={busy} onClick={()=>void refresh()}>Atualizar lista</button></div>
 <div className="bank-kpis bank-payable-kpis"><article className="bank-kpi gold"><span>TOTAL PENDENTE</span><strong>{currency(stats.pending)}</strong><small>Débitos de trocas realizadas</small></article><article className="bank-kpi red"><span>VENCIDO</span><strong>{currency(stats.overdue)}</strong><small>Contas com vencimento anterior a hoje</small></article><article className="bank-kpi navy"><span>A PAGAR NO MÊS</span><strong>{currency(stats.dueMonth)}</strong><small>Somente contas com vencimento definido</small></article><article className="bank-kpi green"><span>PAGO NO MÊS</span><strong>{currency(stats.paidMonth)}</strong><small>Pela data do pagamento</small></article></div>
 <section className="bank-panel"><div className="bank-panel-title"><div><h2>Caixa e vencimentos do mês</h2><p>Os débitos pendentes ficam separados das saídas já confirmadas.</p></div><label>Mês de referência<input type="month" min="2000-01" max="2100-12" value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value);}}/></label></div><div className="bank-mini"><article><span>Entradas realizadas · loja</span><strong>{currency(cash.income)}</strong></article><article><span>Saídas realizadas · loja</span><strong>{currency(cash.expenses)}</strong></article><article><span>Saldo dos lançamentos · loja</span><strong>{currency(cash.balance)}</strong></article></div><p className="bank-note">Os pagamentos destas contas já entram nas saídas acima. Ainda pendente neste mês: <strong>{currency(stats.dueMonth)}</strong>. Saldo após esses débitos: <strong>{currency(cash.balance-stats.dueMonth)}</strong>. Esta projeção usa apenas os lançamentos cadastrados e os débitos das trocas com vencimento no mês; não inclui saldo inicial bancário, novas entradas ou outras obrigações.</p>{stats.noDate>0&&<p className="bank-payable-warning">{stats.noDate} conta(s) sem vencimento: defina a data para incluí-las na projeção mensal.</p>}{stats.planned>0&&<p className="bank-note">{stats.planned} débito(s) de venda prevista: a baixa será liberada quando a venda de origem estiver realizada.</p>}{cash.missing>0&&<p className="bank-error">Saldo parcial: há {cash.missing} lançamento(s) realizado(s) sem valor.</p>}</section>
 {notice&&<p className="bank-note" role="status">{notice}</p>}{error&&<p className="bank-error" role="alert">{error}</p>}
 {selected&&vehicle&&form&&<PayableForm key={selected.id+form.action+selected.updated_at} p={selected} s={vehicle} data={data} action={form.action} onCancel={()=>setForm(null)} onSaved={message=>void refresh(message)}/>}
 {history&&<section className="bank-panel"><div className="bank-panel-title"><h2>Histórico · {payableLabels[data.rows.find(p=>p.id===history.id)!.kind]}</h2><button onClick={()=>setHistory(null)}>Fechar histórico</button></div><p>Alterações e baixas anteriores são preservadas.</p><ol className="bank-payable-history">{history.rows.map(h=><li key={h.id}><strong>{h.next.action==='BAIXA_DESFEITA'?'Correção de baixa':!h.previous?'Débito registrado':h.previous.status!==h.next.status?(h.next.status==='PAGO'?'Pagamento confirmado':'Conta reaberta'):h.previous.amount_cents!==h.next.amount_cents?'Valor atualizado na origem':'Vencimento / dados atualizados'}</strong><small>{new Date(h.created_at).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}</small>{h.next.reason&&<p>{h.next.reason}</p>}{h.next.amount_cents!==undefined&&<p>{currency(Number(h.next.amount_cents))} · {h.next.status==='PAGO'?`Pago em ${day(h.next.paid_at||null)} · ${methods[h.next.method||'']||'—'}`:`Vencimento: ${day(h.next.due_date||null)}`}</p>}</li>)}</ol><h3>Comprovantes anexados</h3>{history.files.length?history.files.map(f=><p key={f.id}><a href={bankPath('/api/payables/files/'+f.id)}>Baixar comprovante · {new Date(f.created_at).toLocaleString('pt-BR')}</a></p>):<p>Nenhum comprovante anexado.</p>}</section>}
 <section className="bank-panel"><div className="bank-panel-title"><div><h2>Débitos vinculados aos veículos</h2><p>{list.length} conta(s) neste filtro</p></div></div><div className="bank-filters"><input aria-label="Buscar conta por carro ou placa" placeholder="Buscar carro, placa ou banco" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Situação das contas" value={filter} onChange={e=>setFilter(e.target.value)}><option value="pending">Pendentes</option><option value="overdue">Vencidas</option><option value="paid">Pagas</option><option value="all">Todas as ativas</option><option value="archived">Arquivadas na origem</option></select><select aria-label="Período de vencimento" value={dueFilter} onChange={e=>setDueFilter(e.target.value)}><option value="all">Todos os vencimentos</option><option value="month">Vencimentos no mês selecionado</option></select></div>
 <div className="bank-table bank-admin-sheet"><table><thead><tr><th>Veículo / placa</th><th>Débito</th><th>Valor</th><th>Vencimento</th><th>Situação</th><th>Pagamento</th><th>Ações</th></tr></thead><tbody>{list.map(p=>{const s=stocks.get(p.stock_id),state=payableState(p,s),canPay=p.active&&s?.active&&s.status!=='PREVISTO';return <tr key={p.id}><td><strong>{s?.plate}</strong><small>{name(s)}</small></td><td>{payableLabels[p.kind]}<small>{p.bank||'—'}</small></td><td><strong>{currency(Number(p.amount_cents))}</strong></td><td>{day(p.due_date)}{p.notes&&<small>{p.notes}</small>}</td><td><span className={'bank-pill '+(state==='Pago'?'green':state==='Vencido'?'red':'gold')}>{state}</span></td><td>{p.status==='PAGO'?<>{day(p.paid_at)}<small>{methods[p.method||'']}</small>{p.receipt_id&&<a href={bankPath('/api/payables/files/'+p.receipt_id)}>Comprovante</a>}</>:'—'}</td><td><div className="bank-admin-row-actions">{p.active&&p.status==='PENDENTE'&&<button disabled={busy} onClick={()=>{setForm({id:p.id,action:'schedule'});setHistory(null);}}>Definir vencimento</button>}{p.status==='PENDENTE'&&<button disabled={busy||!canPay} onClick={()=>{setForm({id:p.id,action:'pay'});setHistory(null);}}>Confirmar pagamento</button>}{p.active&&p.status==='PAGO'&&<button disabled={busy} onClick={()=>{setForm({id:p.id,action:'reverse'});setHistory(null);}}>Desfazer baixa</button>}<button disabled={busy} onClick={()=>void showHistory(p)}>Histórico</button></div></td></tr>;})}{!list.length&&<tr><td colSpan={7}><div className="bank-empty">Nenhuma conta neste filtro. Os débitos são criados ao salvar uma venda com troca, incluindo IPVA, multas ou quitação.</div></td></tr>}</tbody></table></div><p className="bank-note">Valores e banco vêm da venda de origem. Se precisar corrigir um débito pago, desfaça a baixa primeiro. As saídas vinculadas ficam protegidas contra edição e restauração independente, evitando duplicidade no caixa.</p></section></>;
}
