'use client';
import {useEffect,useState,useRef,type FormEvent} from 'react';
import {bankPath,brazilDay,currency} from '@/lib/icom-bank/model';
import {adminMoneyInput,adminMoneyText} from '@/lib/icom-bank/administrative';
import {dailyCash,withdrawalInput,type DailyCashData,type CashCheck} from '@/lib/icom-bank/daily-cash';
import {saleCash} from '@/lib/icom-bank/cash';
import {realDate} from '@/lib/icom-bank/contracts';
import BankFinancialNavigation from './BankFinancialNavigation';

const dateLabel=(d:string)=>d.split('-').reverse().join('/');
const timestamp=(d:string)=>new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',dateStyle:'short',timeStyle:'short'}).format(new Date(d));
const signedMoney=(v:string)=>(v.trim().startsWith('-')?-1:1)*adminMoneyInput(v.trim().replace(/^-/,'').trim());
const signedText=(c:number)=>(c<0?'-':'')+adminMoneyText(Math.abs(c));
export default function BankDailyCash({initial}:{initial:DailyCashData}){
 const [data,setData]=useState(initial),[date,setDate]=useState(initial.date),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[observed,setObserved]=useState(''),[notes,setNotes]=useState(''),[confirmed,setConfirmed]=useState(false),[withdrawal,setWithdrawal]=useState(false);
 const checkId=useRef(''),withdrawalId=useRef('');
 useEffect(()=>{const c=new AbortController();const reload=()=>{void fetch(bankPath('/api/daily-cash?date='+encodeURIComponent(data.date)),{cache:'no-store',signal:c.signal}).then(async r=>{const v=await r.json() as DailyCashData&{error?:string};if(!r.ok)throw new Error(v.error||'Não foi possível atualizar o caixa.');return v;}).then(v=>{setData(v);setConfirmed(false);checkId.current='';}).catch(e=>{if(!c.signal.aborted)setError(e.message);});};window.addEventListener('icom-bank-ledger-changed',reload);return()=>{c.abort();window.removeEventListener('icom-bank-ledger-changed',reload);};},[data.date]);
 const metrics=dailyCash(data.context.entries,data.date),latest=data.history.find(h=>h.check_date===data.date);
 let observedCents:number|null=null;try{if(observed.trim())observedCents=signedMoney(observed);}catch{/* Show validation on save. */}
 const diff=observedCents===null?null:observedCents-metrics.gross;
 const month=data.date.slice(0,7),outflows=data.context.entries.filter(e=>e.active&&e.status==='REALIZADO'&&e.entry_date.startsWith(month)&&['Retirada / Pix','Devolução ao investidor'].includes(e.category));
 async function refresh(day:string){const response=await fetch(bankPath('/api/daily-cash?date='+encodeURIComponent(day)),{cache:'no-store'}),payload=await response.json() as DailyCashData&{error?:string};if(!response.ok)throw new Error(payload.error||'Não foi possível atualizar o caixa.');setData(payload);setDate(payload.date);}
 async function load(){setBusy(true);setError('');setNotice('');try{await refresh(date);setObserved('');setNotes('');setConfirmed(false);checkId.current='';}catch(e){setError(e instanceof Error?e.message:'Não foi possível atualizar.');}finally{setBusy(false);}}
 async function saveCheck(e:FormEvent){e.preventDefault();setBusy(true);setError('');setNotice('');try{
  if(!confirmed)throw new Error('Confirme que conferiu o saldo de todas as contas e o dinheiro.');
  if(observedCents===null)throw new Error('Informe o saldo total conferido.');
  if(diff!==0&&notes.trim().length<5)throw new Error('Explique a diferença na observação.');
  checkId.current||=crypto.randomUUID();const r=await fetch(bankPath('/api/daily-cash'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'check',id:checkId.current,date:data.date,revision:data.context.revision,observed_cents:observedCents,notes})}),p=await r.json() as {row?:CashCheck;error?:string};
  if(!r.ok||!p.row)throw new Error(p.error||'Não foi possível salvar.');setData(old=>({...old,history:[p.row!,...old.history.filter(h=>h.id!==p.row!.id)]}));setNotice('Conferência salva no histórico. Ela não altera o saldo nem cria entradas ou saídas.');checkId.current='';setConfirmed(false);
 }catch(err){setError(err instanceof Error?err.message:'Não foi possível salvar.');}finally{setBusy(false);}}
 return <>
  <div className="bank-heading"><div><p className="bank-eyebrow">CONFERÊNCIA E MOVIMENTAÇÕES</p><h1>Caixa do dia</h1><p>Confira o dinheiro e registre retiradas já realizadas.</p></div><a className="bank-primary" href={bankPath('/administrativo')}>Voltar ao Administrativo</a></div>
  <BankFinancialNavigation active="cash"/>
  <div className="bank-daily-toolbar"><form onSubmit={e=>{e.preventDefault();void load();}}><label>Dia da conferência<input type="date" value={date} required min="2000-01-01" max={brazilDay()} disabled={busy} onChange={e=>setDate(e.target.value)}/></label><button disabled={busy}>Conferir / atualizar</button></form><button className="bank-withdrawal-action" disabled={busy} onClick={()=>{setWithdrawal(!withdrawal);setError('');}}>↗ {withdrawal?'Fechar retirada':'Registrar retirada / Pix'}</button></div>
  {date!==data.date&&<p className="bank-payable-warning">Clique em “Conferir / atualizar” para carregar a data escolhida antes de salvar.</p>}
  {error&&<p className="bank-error" role="alert">{error}</p>}{notice&&<p className="bank-note" role="status">{notice}</p>}
  {withdrawal&&<Withdrawal date={data.date} data={data} busy={busy} setBusy={setBusy} requestIdRef={withdrawalId} onError={setError} onSaved={async()=>{setWithdrawal(false);setObserved('');setConfirmed(false);checkId.current='';setNotice('Saída registrada uma única vez. Confira o saldo atualizado abaixo.');await refresh(data.date);}}/>}
  <div className="bank-kpis bank-daily-kpis"><article className="bank-kpi navy"><span>SALDO LIVRE DA LOJA</span><strong>{currency(metrics.available)}</strong><small>Acumulado até {dateLabel(data.date)}</small></article><article className="bank-kpi gold"><span>RESERVADO A INVESTIDORES</span><strong>{currency(metrics.investor)}</strong><small>Este dinheiro não está livre para contas</small></article><article className="bank-kpi green"><span>ENTRADAS DO DIA</span><strong>{currency(metrics.income)}</strong><small>Somente dinheiro recebido</small></article><article className="bank-kpi red"><span>SAÍDAS DO DIA</span><strong>{currency(metrics.expenses+metrics.personal)}</strong><small>Loja, devoluções e despesas pessoais</small></article></div>
  <div className="bank-daily-layout"><section className="bank-panel"><p className="bank-eyebrow">01 · CONFIRA OS REGISTROS</p><h2>Movimento de {dateLabel(data.date)}</h2><dl className="bank-daily-breakdown">
   <div><dt>Saldo total no início do dia</dt><dd>{currency(metrics.opening_gross)}</dd></div><div><dt>+ Entradas recebidas</dt><dd>{currency(metrics.income)}</dd></div><div><dt>− Saídas da loja e devoluções</dt><dd>{currency(metrics.expenses)}</dd></div><div><dt>− Saídas pessoais</dt><dd>{currency(metrics.personal)}</dd></div><div className="total"><dt>Saldo total registrado</dt><dd>{currency(metrics.gross)}</dd></div>
   <div><dt>Reserva de investidores</dt><dd>{currency(metrics.investor)}</dd></div><div><dt>Capital de repasses</dt><dd>{currency(metrics.capital)}</dd></div><div><dt>Custos e débitos reservados</dt><dd>{currency(metrics.costs)}</dd></div><div><dt>Vendas a conferir</dt><dd>{currency(metrics.review)}</dd></div><div className="free"><dt>Livre para a loja, após reservas e ajustes</dt><dd>{currency(metrics.available)}</dd></div>
  </dl><p className="bank-note">Livre no início do dia: {currency(metrics.opening_available)}. Além das entradas e saídas, a liberação de reservas e os ajustes de prejuízo podem alterar o saldo livre. Carros em estoque e valores previstos não entram como dinheiro.</p></section>
  <form className="bank-panel bank-daily-check" onSubmit={saveCheck}><p className="bank-eyebrow">02 · COMPARE COM O DINHEIRO REAL</p><h2>Conferir saldo</h2><fieldset disabled={busy}>
   <p>Some os saldos das contas usadas neste controle e o dinheiro em mãos, incluindo o valor dos investidores. Informe o total no fim deste dia.</p>
   <label>Saldo total conferido (R$)<input required inputMode="decimal" placeholder="0,00" value={observed} onChange={e=>{setObserved(e.target.value);setConfirmed(false);checkId.current='';}} onBlur={()=>{try{setObserved(signedText(signedMoney(observed)));}catch{/* Keep the value for correction. */}}}/><small>Pode ser negativo se houver saldo devedor. O sistema não consulta seu banco.</small></label>
   <div className={'bank-daily-comparison '+(diff===null?'':diff===0?'matched':'different')} role="status"><span>{diff===null?'INFORME O SALDO PARA COMPARAR':diff===0?'SALDOS CONFEREM':'DIFERENÇA A CONFERIR'}</span><strong>{diff===null?'—':currency(diff)}</strong><small>{diff===null?'Saldo conferido menos saldo total registrado':diff===0?'O total confere com os registros':diff>0?'Há mais dinheiro do que o registrado':'Há menos dinheiro do que o registrado'}</small></div>
   {observedCents!==null&&<p>Aplicando as mesmas reservas e ajustes, o saldo livre conferido seria <strong>{currency(observedCents+metrics.available-metrics.gross)}</strong>.</p>}
   <label>Observação / contas conferidas<textarea rows={3} maxLength={2000} required={diff!==null&&diff!==0} value={notes} onChange={e=>{setNotes(e.target.value);checkId.current='';}} placeholder="Ex.: Santander, Itaú e dinheiro. Se houver diferença, explique o que precisa conferir."/></label>
   <label className="bank-checkbox"><input type="checkbox" checked={confirmed} required onChange={e=>setConfirmed(e.target.checked)}/> Conferi todas as contas e o dinheiro deste dia.</label><button className="bank-primary" disabled={busy||!confirmed||observedCents===null||date!==data.date}>{busy?'Salvando…':'SALVAR CONFERÊNCIA'}</button>
  </fieldset><p className="bank-note">Salvar guarda uma fotografia do caixa. Nenhum valor é ajustado automaticamente. Corrija os lançamentos na origem e faça uma nova conferência, se necessário.</p></form></div>
  {latest&&<p className={latest.ledger_revision===data.context.revision?'bank-note':'bank-payable-warning'}>Última conferência deste dia: {timestamp(latest.created_at)} · {latest.actor_name}. {latest.ledger_revision!==data.context.revision?'Os registros mudaram depois. Confira o saldo novamente.':'Os registros continuam iguais à conferência salva.'}</p>}
  <section className="bank-panel"><h2>Histórico de conferências · {month.split('-').reverse().join('/')}</h2><p>Cada conferência preserva seus valores. Para ver meses anteriores, selecione uma data daquele mês.</p><div className="bank-table"><table><thead><tr>{['Dia / registro','Saldo total registrado','Saldo conferido','Diferença','Livre da loja','Responsável / observação'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{data.history.map(h=><tr key={h.id}><td>{dateLabel(h.check_date)}<small>{timestamp(h.created_at)}</small></td><td>{currency(h.metrics.gross)}</td><td>{currency(h.observed_cents)}</td><td><span className={'bank-pill '+(h.difference_cents===0?'green':'red')}>{currency(h.difference_cents)}</span></td><td>{currency(h.metrics.available)}</td><td>{h.actor_name}<small>{h.notes||'Sem observação'}</small></td></tr>)}{!data.history.length&&<tr><td colSpan={6} className="bank-empty">Nenhuma conferência salva neste mês.</td></tr>}</tbody></table></div></section>
  <section className="bank-panel"><h2>Retiradas e Pix registrados · {month.split('-').reverse().join('/')}</h2><p>São saídas já realizadas. Elas também aparecem no Administrativo, onde podem ser corrigidas ou arquivadas.</p><div className="bank-table"><table><thead><tr>{['Data','Destinatário','Tipo','Valor','Motivo'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{outflows.map(e=><tr key={e.id}><td>{dateLabel(e.entry_date)}</td><td>{e.description}</td><td>{e.category==='Devolução ao investidor'?'Investidor':e.scope==='PESSOAL'?'Pessoal':'Loja'}</td><td>{currency(Number(e.amount_cents))}</td><td>{e.details.notes}</td></tr>)}{!outflows.length&&<tr><td colSpan={5} className="bank-empty">Nenhuma retirada ou Pix registrado neste mês.</td></tr>}</tbody></table></div></section>
 </>;
}
function Withdrawal({date,data,busy,setBusy,requestIdRef,onError,onSaved}:{date:string;data:DailyCashData;busy:boolean;setBusy:(v:boolean)=>void;requestIdRef:{current:string};onError:(v:string)=>void;onSaved:()=>Promise<void>}){
 const [day,setDay]=useState(date),[recipient,setRecipient]=useState(''),[reason,setReason]=useState(''),[amount,setAmount]=useState(''),[method,setMethod]=useState('PIX'),[purpose,setPurpose]=useState('LOJA'),[saleId,setSaleId]=useState(''),[confirmed,setConfirmed]=useState(false);
 const effectiveDay=realDate(day)?day:date,cash=dailyCash(data.context.entries,effectiveDay),sales=data.context.entries.filter(e=>e.active&&e.status==='REALIZADO'&&e.kind==='VENDA'&&e.entry_date<=effectiveDay&&e.details.sale_owner==='INVESTIDOR');
 const selected=sales.find(s=>s.id===saleId),reserve=selected?saleCash(selected,data.context.entries,day).investor:0;
 let cents=0;try{cents=adminMoneyInput(amount);}catch{/* Validate on submit. */}
 const change=()=>{requestIdRef.current='';setConfirmed(false);};
 async function save(e:FormEvent){e.preventDefault();setBusy(true);onError('');let saved=false;try{
  requestIdRef.current||=crypto.randomUUID();const body={action:'withdrawal',id:requestIdRef.current,date:day,recipient,reason,method,purpose,sale_id:saleId,amount_cents:adminMoneyInput(amount),confirmed};withdrawalInput(body);
  const r=await fetch(bankPath('/api/daily-cash'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),p=await r.json() as {row?:unknown;error?:string};if(!r.ok||!p.row)throw new Error(p.error||'Não foi possível registrar.');saved=true;requestIdRef.current='';await onSaved();
 }catch(err){onError(saved?'A saída foi salva, mas não foi possível atualizar o saldo. Clique em Conferir / atualizar; não registre novamente.':err instanceof Error?err.message:'Não foi possível registrar.');}finally{setBusy(false);}}
 return <form className="bank-panel bank-withdrawal-form" onSubmit={save}><p className="bank-eyebrow">REGISTRE A SAÍDA REALIZADA</p><h2>Retirada / Pix para outra pessoa</h2><p>Informe o destinatário e o motivo. Este registro dá baixa no caixa; o pagamento é feito por vocês no banco. Movimentações entre contas da própria loja não são retiradas do saldo total.</p><fieldset disabled={busy}><div className="bank-form-grid">
  <label>Data da saída<input type="date" required min="2000-01-01" max={brazilDay()} value={day} onChange={e=>{change();setDay(e.target.value);setSaleId('');}}/></label><label>Tipo de saída<select value={purpose} onChange={e=>{change();setPurpose(e.target.value);setSaleId('');}}><option value="LOJA">Retirada / pagamento da loja</option><option value="PESSOAL">Retirada pessoal · Bruno / Gisela</option><option value="INVESTIDOR">Devolução de dinheiro ao investidor</option></select></label>
  {purpose==='INVESTIDOR'&&<label className="bank-grid-wide">Venda vinculada<select required value={saleId} onChange={e=>{change();setSaleId(e.target.value);const s=sales.find(x=>x.id===e.target.value);setRecipient(s?.details.investor_name||'');}}><option value="">Selecione a venda do investidor</option>{sales.map(s=><option key={s.id} value={s.id}>{s.details.investor_name} · {s.details.vehicle} · {s.details.plate} · {dateLabel(s.entry_date)}</option>)}</select><small>Reserva desta venda: {currency(reserve)}. A devolução reduz a reserva, preservando o lucro já livre para a loja.</small></label>}
  <label>Destinatário<input required maxLength={110} value={recipient} placeholder="Nome de quem recebeu" onChange={e=>{change();setRecipient(e.target.value);}}/></label><label>Forma da saída<select value={method} onChange={e=>{change();setMethod(e.target.value);}}><option value="PIX">Pix</option><option value="TRANSFERENCIA">Transferência bancária</option><option value="DINHEIRO">Dinheiro</option></select></label><label>Valor da saída (R$)<input required inputMode="decimal" placeholder="0,00" value={amount} onChange={e=>{change();setAmount(e.target.value);}} onBlur={()=>{try{setAmount(adminMoneyText(adminMoneyInput(amount)));}catch{/* Keep for correction. */}}}/></label><label>Motivo<input required maxLength={1200} value={reason} placeholder="Ex.: retirada para Bruno ou pagamento ao fornecedor" onChange={e=>{change();setReason(e.target.value);}}/></label>
 </div>{purpose!=='INVESTIDOR'&&cents>cash.available&&<p className="bank-payable-warning">O valor supera o saldo livre de {currency(cash.available)}. Se a saída já aconteceu, registre para que o controle mostre o saldo real, inclusive negativo.</p>}
 <label className="bank-checkbox"><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> Confirmo que esta saída já foi realizada e ainda não está lançada em Contas a pagar ou no Administrativo.</label><button className="bank-primary" disabled={busy||!confirmed}>{busy?'Registrando…':'REGISTRAR SAÍDA · '+currency(cents)}</button></fieldset></form>;
}
