import {bankMenu,canBank,type BankRole} from './model.ts';

export const manualTopics=['menu','cliente','contrato','investidor','fornecedor','conta_pagar','pagar_conta','conta_receber','receber_conta','despesa_loja','despesa_pessoal','venda','parcela','comprovante','veiculo','relatorio','funcionario','configuracoes','conferencia','retirada','whatsapp','patrimonio','renda_pessoal','conta_bancaria','aluguel'] as const;
export type ManualTopic=typeof manualTopics[number];
const extraViews={contas_bancarias:['administrativo','Contas bancárias'],conta_bancaria_form:['administrativo','Cadastrar conta bancária'],imovel_form:['administrativo','Cadastro do imóvel'],alugueis:['administrativo','Aluguéis a receber'],receber_aluguel_form:['administrativo','Confirmar aluguel recebido'],patrimonio:['administrativo','Administrativo pessoal'],patrimonio_form:['administrativo','Patrimônio / renda pessoal'],cliente_novo:['clientes','Novo cliente'],cliente_ficha:['clientes','Ficha do cliente'],contrato_veiculo:['clientes','Novo contrato · Veículo da venda'],contrato_condicoes:['clientes','Novo contrato · Condições financeiras'],contrato_revisao:['clientes','Novo contrato · Revisão'],contrato_ficha:['contratos','Contrato e parcelas'],parcela_ficha:['dashboard','Pagamento da parcela'],comprovante_ficha:['comprovantes','Conferir comprovante'],investidores:['administrativo','Investidores da loja'],investidor_form:['administrativo','Novo investidor'],contas_pagar:['administrativo','Contas a pagar'],conta_pagar_form:['administrativo','Cadastrar conta a pagar'],pagar_conta_form:['administrativo','Pagar conta'],contas_receber:['administrativo','Contas a receber'],conta_receber_form:['administrativo','Cadastrar conta a receber'],receber_conta_form:['administrativo','Confirmar recebimento'],conferencia:['administrativo','Caixa do dia'],retirada_form:['administrativo','Retirada / Pix para outra pessoa'],retirada_pessoal_form:['administrativo','Registrar retirada na área pessoal'],whatsapp:['administrativo','WhatsApp ICOM Bank'],lancamento_form:['administrativo','Novo lançamento'],despesa_loja_form:['administrativo','Custo / despesa da loja'],despesa_pessoal_form:['administrativo','Despesa pessoal'],venda_form:['administrativo','Venda de veículo']} as const;
export const manualViews={...Object.fromEntries(bankMenu.map(([key,label])=>[key,[key,label]])),...extraViews,nao_identificada:['dashboard','Tela não identificada pelo manual']} as Record<string,readonly [string,string]>;
export type ManualView=keyof typeof extraViews|typeof bankMenu[number][0]|'nao_identificada';
export function manualMenu(role:BankRole){return bankMenu.filter(([key])=>canBank(role,key)).map(([key,label],i)=>({section:key,number:String(i+1).padStart(2,'0'),label}));}
export function manualView(value:unknown,role:BankRole):ManualView{
 return typeof value==='string'&&Object.hasOwn(manualViews,value)&&canBank(role,manualViews[value][0])?value as ManualView:'nao_identificada';
}
export function manualViewFromPath(path:string,role:BankRole):ManualView{
 const clean=path.split(/[?#]/,1)[0].replace(/^\/experiencia-icom(?=\/)/,'').replace(/\/$/,'');
 const tail=clean.replace(/^\/icom-bank\//,'');
 if(!clean.startsWith('/icom-bank/'))return 'nao_identificada';
 const roots:Record<string,ManualView>={'clientes/novo':'cliente_novo','administrativo/contas-bancarias':'contas_bancarias','administrativo/pessoal':'patrimonio','administrativo/investidores':'investidores','administrativo/contas-a-pagar':'contas_pagar','administrativo/contas-a-receber':'contas_receber','administrativo/conferencia-diaria':'conferencia','administrativo/whatsapp':'whatsapp'};
 if(roots[tail])return manualView(roots[tail],role);
 const id='[a-f0-9-]{36}';
 if(new RegExp('^clientes/'+id+'/contrato/novo$','i').test(tail))return manualView('contrato_veiculo',role);
 for(const [section,view] of [['clientes','cliente_ficha'],['contratos','contrato_ficha'],['parcelas','parcela_ficha'],['comprovantes','comprovante_ficha']] as const)if(new RegExp('^'+section+'/'+id+'$','i').test(tail))return manualView(view,role);
 return manualView(tail,role);
}
type Step={text:string;view?:ManualView};
type Recipe={title:string;section:string;steps:Step[];notes?:string[];available?:false};
const step=(text:string,view?:ManualView):Step=>({text,...(view?{view}:{})});
const recipes:Record<Exclude<ManualTopic,'menu'>,Recipe>={
 conta_bancaria:{title:'Cadastrar conta bancária',section:'administrativo',steps:[step('Abra Administrativo pessoal e clique em Minhas contas e saldos.'),step('Clique em Cadastrar conta.','contas_bancarias'),step('Informe Como você chama esta conta?, Qual é o banco? e De quem é a conta?.','conta_bancaria_form'),step('Informe o saldo que já havia antes dos lançamentos, ou zero se já estiver no histórico. Confira e clique em Salvar conta.')],notes:['Saldo inicial não é lucro. Contas são registros internos; o sistema não acessa bancos.']},
 aluguel:{title:'Confirmar aluguel recebido',section:'administrativo',steps:[step('Abra Administrativo pessoal e clique em Aluguéis a receber.','patrimonio'),step('Escolha o mês, localize o aluguel e clique em Receber aluguel.','alugueis'),step('Informe a conta em que caiu, a data e como recebeu.','receber_aluguel_form'),step('Confira o dinheiro no banco, marque a confirmação e clique em Confirmar recebimento.')],notes:['O aluguel previsto não soma saldo. O recebimento soma apenas a renda pessoal e a conta escolhida, sem inflar o lucro da loja.']},
 patrimonio:{title:'Cadastrar patrimônio pessoal',section:'administrativo',steps:[step('Clique em Administrativo e em Administrativo pessoal.'),step('Clique em Cadastrar patrimônio.','patrimonio'),step('Informe nome e escolha a categoria Imóvel / aluguel.','patrimonio_form'),step('Preencha Por quanto você comprou este imóvel?, Quanto vale este imóvel hoje? e Quanto você ainda deve por este imóvel?.','imovel_form'),step('Se alugado, informe aluguel mensal, primeiro vencimento, meses restantes e a conta onde recebe. Se a conta ainda não existir, clique em + Cadastrar conta aqui, preencha banco, nome e de quem é a conta; clique em Cadastrar e usar esta conta, sem sair do imóvel. Pix é a forma padrão. Se financiado, informe parcela, próximo vencimento e quantas parcelas faltam; a conta de saída é escolhida a cada pagamento.'),step('Confira os dados do imóvel e clique em Salvar registro.')],notes:['Juros estimados não viram recebimento. Valorização não é dinheiro no caixa. Parcelas são contas pessoais; aluguéis previstos aguardam confirmação.']},
 renda_pessoal:{title:'Registrar rendimento recebido',section:'administrativo',steps:[step('Clique em Administrativo e em Administrativo pessoal.'),step('Clique em Registrar rendimento.','patrimonio'),step('Informe nome, categoria, data e rendimento líquido recebido; selecione o bem relacionado se houver.','patrimonio_form'),step('Confira e clique em Salvar registro.')],notes:['Este botão registra somente juros, dividendos ou outra renda realmente recebida. Confirme aluguéis em Aluguéis a receber. Devolução do valor aplicado não é rendimento. Retiradas são manuais: use Registrar retirada, selecione a conta, valor e motivo. Aportes e resgates antigos ficam no histórico.']},
 cliente:{title:'Cadastrar cliente manualmente',section:'clientes',steps:[step('No menu à esquerda, clique em Clientes.','dashboard'),step('Na página Clientes, clique em + NOVO CLIENTE.','clientes'),step('Preencha Nome completo e CPF válido no formulário Dados do cliente.','cliente_novo'),step('Informe Telefone / WhatsApp e E-mail, se disponíveis. Perfil interno (opcional) pode ficar Sem classificação.'),step('Confira os dados e clique em SALVAR CLIENTE. Aguarde a ficha abrir; se houver erro, corrija o campo indicado.')],notes:['O cadastro do cliente não cria um contrato automaticamente. Não peça que a pessoa dite o CPF para a IA: ela o preenche no formulário.']},
 contrato:{title:'Cadastrar veículo e contrato manualmente',section:'clientes',steps:[step('Clique em Clientes e use Buscar nome ou CPF para localizar o cliente.'),step('Na linha do cliente, clique em Ver ficha.','clientes'),step('Em Veículos e contratos, clique em + CADASTRAR VEÍCULO E CONTRATO.','cliente_ficha'),step('Em Veículo da venda, selecione marca, modelo / versão e ano; informe a placa e os dados solicitados. Clique em CONTINUAR.','contrato_veiculo'),step('Em Condições financeiras, informe valor do veículo, entrada, quantidade e valor das parcelas, primeiro vencimento e Periodicidade. O valor financiado é calculado pela diferença.','contrato_condicoes'),step('Preencha as taxas manualmente, inclusive zero quando aplicável, e clique em REVISAR PARCELAS.'),step('Em Confira antes de salvar, confira o plano e clique em SALVAR CONTRATO E PARCELAS. Use Voltar para corrigir.','contrato_revisao')],notes:['A IA não define taxas, aprova crédito nem deve salvar o contrato neste modo.']},
 investidor:{title:'Cadastrar investidor manualmente',section:'administrativo',steps:[step('Clique em Administrativo no menu à esquerda.'),step('Clique em Investidores da loja · cadastrar e ver carros →.','administrativo'),step('Em Investidores da loja, clique em + CADASTRAR INVESTIDOR.','investidores'),step('Preencha Nome do investidor, Telefone e E-mail; use Observações se necessário.','investidor_form'),step('Confira e clique em SALVAR INVESTIDOR. Aguarde a mensagem Investidor salvo.')],notes:['O nome fica fixo após o cadastro para preservar vínculos. Os carros aparecem quando vendas e trocas são vinculadas ao investidor.']},
 fornecedor:{title:'Fornecedores: o que está disponível',section:'administrativo',available:false,steps:[],notes:['Não existe cadastro específico de fornecedores nem botão Novo fornecedor no ICOM Bank atual. Não invente esse menu. Para registrar uma obrigação com um fornecedor, use Contas a pagar e informe a empresa no Nome da conta ou nas Observações; isso registra a conta, não cria cadastro de fornecedor. Pergunte se a pessoa quer esse passo a passo e, se sim, consulte conta_pagar.']},
 conta_pagar:{title:'Cadastrar conta a pagar manualmente',section:'administrativo',steps:[step('Clique em Administrativo e no cartão Contas a pagar.'),step('Em Contas a pagar, clique em + Cadastrar conta.','contas_pagar'),step('Em De quem é esta conta?, escolha Loja ou Pessoal · Bruno e Gisela. Preencha Nome da conta e Valor por vencimento (R$).','conta_pagar_form'),step('Escolha Primeiro vencimento e Frequência: Avulsa · uma única conta ou Mensal · repetir os vencimentos. Para mensal, selecione Quantos meses cadastrar?.'),step('Se necessário, complete Observações (opcional); confira e clique em CADASTRAR CONTA ou CADASTRAR seguido da quantidade de VENCIMENTOS.')],notes:['Cadastrar uma conta futura não dá baixa nem desconta o caixa.']},
 pagar_conta:{title:'Dar baixa em conta paga manualmente',section:'administrativo',steps:[step('Clique em Administrativo e no cartão Contas a pagar.'),step('Localize a conta na agenda ou no campo Buscar conta. Na linha correspondente, clique em Pagar conta.','contas_pagar'),step('No formulário Pagar conta, confira o valor. Em Como registrar no caixa, escolha Criar saída para este pagamento, ou Vincular saída já lançada se esse mesmo pagamento já estiver registrado.','pagar_conta_form'),step('Escolha De qual conta saiu o pagamento? e confira Data do pagamento, Forma de pagamento e Comprovante (opcional).'),step('Somente após conferir a saída real no banco, marque Confirmei que o pagamento foi realizado e clique em CONFIRMAR PAGAMENTO, seguido do valor.')],notes:['O sistema registra uma saída que já ocorreu; não executa Pix no banco. Evite descontar o mesmo pagamento duas vezes.']},
 conta_receber:{title:'Cadastrar conta a receber manualmente',section:'administrativo',steps:[step('Clique em Administrativo e no cartão Contas a receber.'),step('Clique em + Cadastrar conta.','contas_receber'),step('Preencha Nome / descrição, Quem paga? e Valor desta conta (R$).','conta_receber_form'),step('Informe Vencimento, o Banco quando aplicável e o nome do pagador, se disponível. Use Observações (opcional) para o contexto.'),step('Confira e clique em SALVAR CONTA.')],notes:['A conta pendente não é entrada no caixa. As parcelas dos contratos são controladas em Parcelas.']},
 receber_conta:{title:'Registrar recebimento manualmente',section:'administrativo',steps:[step('Clique em Administrativo e Contas a receber.'),step('Localize a conta pelo campo Buscar conta a receber. Na linha correspondente, clique em Receber.','contas_receber'),step('Em Como registrar no caixa, escolha Criar entrada para este recebimento ou Vincular entrada já lançada se o mesmo recebimento já foi registrado.','receber_conta_form'),step('Escolha Em qual conta entrou o recebimento? e informe Valor recebido agora (R$), Data do recebimento e Forma do recebimento. Pode ser parcial; o restante continua em aberto.'),step('Após conferir a entrada real no banco, marque Conferi que este valor já foi recebido e clique em CONFIRMAR RECEBIMENTO.')],notes:['Receita prevista e dinheiro já recebido são diferentes.']},
 despesa_loja:{title:'Lançar despesa da loja manualmente',section:'administrativo',steps:[step('Clique em Administrativo e na área Custos da loja.','administrativo'),step('Clique em + NOVO LANÇAMENTO.'),step('Em Área, confira Custo / despesa da loja; em Escopo, selecione Loja.','despesa_loja_form'),step('Preencha Data do lançamento, Descrição, Categoria, Situação e Valor em reais. Marque Realizado / pago ou recebido apenas para a saída que já ocorreu.'),step('Para custo de carro, use Relacionar este custo a um veículo e identifique a placa correta. Use Observações para o contexto.'),step('Confira Forma de pagamento / recebimento e clique em SALVAR LANÇAMENTO.')],notes:['Placas antigas ABC1234 e Mercosul ABC1D23 são aceitas. Para despesa futura, prefira Contas a pagar.']},
 despesa_pessoal:{title:'Lançar despesa pessoal manualmente',section:'administrativo',steps:[step('Clique em Administrativo e na área Despesas pessoais.','administrativo'),step('Clique em + NOVO LANÇAMENTO.'),step('Confira Área como Despesa pessoal e Escopo como Pessoal.','despesa_pessoal_form'),step('Preencha Data do lançamento, Descrição, Categoria, Situação e Valor em reais. Selecione a categoria mais específica.'),step('Confira Contexto do gasto e Classificação do gasto; Viagem (opcional) usa o mesmo nome nos gastos da mesma viagem.'),step('Confira Forma de pagamento / recebimento e clique em SALVAR LANÇAMENTO.')],notes:['Uma despesa da viagem pode pertencer também a Restaurante, sem duplicar o valor.']},
 venda:{title:'Registrar venda manualmente',section:'administrativo',steps:[step('Clique em Administrativo, na área Vendas e em + NOVO LANÇAMENTO.','administrativo'),step('Em Venda de veículo, confira Data da venda, placa, vendedor e Dono do carro vendido. Se for Investidor, selecione o investidor cadastrado.','venda_form'),step('Informe Valor de compra, Custos adicionais do veículo, Custo fixo do vendedor e Valor da venda. Não repita a compra nos custos adicionais.'),step('Em Troca recebida, informe se recebeu carro. Se Sim, complete veículo, placa, valor antes dos débitos, débitos e Quem fica com o carro da troca?.'),step('Em Pagamento da diferença, escolha a forma e Recebimento da diferença. Informe somente o dinheiro realmente recebido.'),step('Confira Como chegamos ao lucro e Como este dinheiro fica separado. Clique em SALVAR LANÇAMENTO quando todos os dados estiverem corretos.')],notes:['Dinheiro do investidor fica reservado, separado do saldo livre da loja. A IA não determina os valores da operação.']},
 parcela:{title:'Enviar pagamento de parcela para análise',section:'dashboard',steps:[step('Abra o contrato pela ficha do cliente ou por Contratos, quando esse menu estiver disponível para seu perfil.'),step('Na lista de parcelas, abra a parcela desejada pelo botão de pagamento disponível.'),step('Em Pagamento da parcela, confira o saldo e os dados Pix. O pagamento é feito fora do sistema.','parcela_ficha'),step('Em Enviar comprovante, confira Valor informado no comprovante (R$), selecione o arquivo JPG, PNG ou PDF e clique em ENVIAR PARA ANÁLISE; aguarde a análise da equipe.')],notes:['Enviar comprovante não dá baixa automaticamente. Para aprovar um comprovante, consulte o roteiro comprovante.']},
 comprovante:{title:'Aprovar comprovante manualmente',section:'comprovantes',steps:[step('Clique em Comprovantes e abra a análise do envio pendente.'),step('Em Conferir comprovante, clique em BAIXAR COMPROVANTE e compare cliente, parcela, valor e documento com a entrada real no banco.','comprovante_ficha'),step('Informe Data em que o pagamento entrou na conta e clique em APROVAR PAGAMENTO.'),step('Confira a revisão e clique em CONFIRMAR RECEBIMENTO somente se realmente recebeu o valor. Para erro no envio, informe Motivo da recusa e use Recusar comprovante.')],notes:['A IA não confirma a entrada no banco pela aparência do comprovante.']},
 veiculo:{title:'Consultar veículos e registrar custo',section:'veiculos',steps:[step('Clique em Veículos.'),step('Escolha Carros recebidos na troca ou Veículos dos contratos, conforme a origem. Use Buscar carro / placa e Filtrar situação.','veiculos'),step('No carro da troca, abra os detalhes. Para despesa de preparação, use + Custo de preparação quando seu perfil permitir.'),step('Confira o veículo e o custo no formulário; só salve após conferir os dados.')],notes:['Não existe botão genérico Novo veículo nessa lista: veículos de contratos são cadastrados na ficha do cliente; carros da troca surgem das vendas do Administrativo.']},
 relatorio:{title:'Consultar relatórios manualmente',section:'relatorios',steps:[step('Clique em Relatórios.'),step('Preencha De e Até e clique em Aplicar período.','relatorios'),step('Confira os totais da carteira, recebimentos e inadimplência. Clique em EXPORTAR CSV para guardar a conferência.')],notes:['Relatórios da carteira não substituem o caixa livre do Administrativo.']},
 funcionario:{title:'Cadastrar e convidar funcionário',section:'funcionarios',steps:[step('Clique em Funcionários.'),step('Em Cadastrar funcionário, preencha Nome, E-mail, Perfil e Situação.','funcionarios'),step('Clique em REVISAR AUTORIZAÇÃO, confira o perfil e clique em CONFIRMAR AUTORIZAÇÃO. Uma nova conta recebe convite por e-mail; uma conta existente usa sua senha ICOM.')],notes:['Não invente senha nem amplie permissões. Os botões de convite e cadastro dependem do perfil autorizado.']},
 configuracoes:{title:'Alterar dados de recebimento manualmente',section:'configuracoes',steps:[step('Clique em Configurações.'),step('Em Chave Pix, confira Tipo da chave e Chave Pix; em Dados da conta, confira Titular, Agência e Conta corrente e dígito.','configuracoes'),step('Preencha os dados diretamente no formulário e use SALVAR DADOS ou SALVAR ALTERAÇÃO, conforme a situação.')],notes:['Não peça que a pessoa dite chave Pix, dados bancários completos, senha ou chave de API para a IA.']},
 conferencia:{title:'Conferir caixa do dia manualmente',section:'administrativo',steps:[step('Clique em Administrativo e no cartão Caixa do dia.'),step('Em Caixa do dia, escolha Dia da conferência e clique em Conferir / atualizar.','conferencia'),step('Compare as movimentações com o banco e o dinheiro físico. Preencha Saldo total conferido (R$) e Observação / contas conferidas.'),step('Marque Conferi todas as contas e o dinheiro deste dia e clique em SALVAR CONFERÊNCIA.')],notes:['Salvar conferência guarda o histórico sem criar um ajuste financeiro.']},
 retirada:{title:'Registrar retirada ou Pix manualmente',section:'administrativo',steps:[step('Clique em Administrativo e Caixa do dia.'),step('Em Caixa do dia, clique em Registrar retirada / Pix.','conferencia'),step('Escolha De qual conta saiu esta retirada? e preencha Data da saída, Tipo de saída, Destinatário, Forma da saída, Valor da saída (R$) e Motivo. Para devolução ao investidor, selecione Venda vinculada.','retirada_form'),step('Após a saída real, confira se ela ainda não foi lançada em outro lugar. Marque a confirmação e clique em REGISTRAR SAÍDA, seguido do valor.')],notes:['Retirada e transferência continuam exclusivamente manuais. A IA apenas explica, nunca prepara nem executa a saída.']},
 whatsapp:{title:'Abrir configuração do WhatsApp',section:'administrativo',steps:[step('Clique em Administrativo.'),step('No cartão WhatsApp ICOM Bank, clique em Conectar e configurar.','administrativo'),step('Confira o número do contato ICOM Bank e os números autorizados; conecte pelo QR Code o celular do número do ICOM Bank.','whatsapp'),step('Envie a despesa a partir de um número autorizado e confira a confirmação e o histórico de mensagens.')],notes:['O número conectado é o do contato ICOM Bank, diferente do número autorizado que envia a despesa.']},
};
export type ManualResult={ok:true;mode:'MANUAL';topic:ManualTopic;title:string;available:boolean;menu:ReturnType<typeof manualMenu>;current_view:{id:ManualView;label:string};steps:Step[];suggested_step:number;notes:string[]};
export function readManual(raw:unknown,view:unknown,role:BankRole):ManualResult{
 if(!raw||typeof raw!=='object'||Array.isArray(raw)||Object.keys(raw).some(k=>k!=='topic')||!manualTopics.includes((raw as {topic:ManualTopic}).topic))throw new Error('Escolha um tópico do manual do ICOM Bank.');
 const topic=(raw as {topic:ManualTopic}).topic,menu=manualMenu(role),current=manualView(view,role);
 let recipe=topic==='menu'?null:recipes[topic];
 if(topic==='retirada'&&['patrimonio','retirada_pessoal_form'].includes(current))recipe={title:'Registrar retirada na área pessoal',section:'administrativo',steps:[step('Em Meu dinheiro pessoal, clique em Registrar retirada.','patrimonio'),step('Escolha De qual conta saiu o dinheiro?, informe Quanto você retirou? e Qual foi o motivo?.','retirada_pessoal_form'),step('Em Essa saída é pessoal ou da loja?, escolha a finalidade. Data de hoje e Pix vêm preenchidos; mude em Data, forma e destinatário (opcional), se necessário.'),step('Confira que o dinheiro já saiu e que a saída ainda não está registrada. Marque a confirmação e clique em Salvar retirada.')],notes:['A conta escolhida terá o saldo descontado uma vez. Não registre uma compra ou conta já lançada. Retiradas continuam exclusivamente manuais; a IA só orienta.']};
 const allowed=!recipe||canBank(role,recipe.section),available=allowed&&recipe?.available!==false;
 const steps=!allowed||!available?[]:recipe?.steps||menu.map(m=>step(`Menu ${m.number} · ${m.label}: abre a área ${m.label}.`));
 const at=steps.findIndex(s=>s.view===current);
 return {ok:true,mode:'MANUAL',topic,title:recipe?.title||'Conhecer os menus',available,menu,current_view:{id:current,label:manualViews[current][1]},steps,suggested_step:at<0?1:at+1,notes:!allowed?['Esta tarefa não está disponível para seu perfil. Não oriente acesso a uma área restrita.']:recipe?.notes||['A numeração corresponde ao menu visível para este perfil. No celular, use Abrir menu para mostrar a navegação.']};
}
export function assistantManualTool(){return {type:'function' as const,name:'consultar_manual_icom',description:'Lê o manual verificado dos menus, botões e formulários reais do ICOM Bank, com a tela atual do usuário. Use SEMPRE para como faço, me ensina, onde clico, ajuda para fazer manualmente e para continuar o passo a passo. Não grava nada, não consulta dados financeiros e não prepara lançamentos. Fornecedor informa que não existe cadastro específico.',parameters:{type:'object',additionalProperties:false,properties:{topic:{type:'string',enum:manualTopics}},required:['topic']}};}
