import {parseRiskProfile,type RiskProfile} from './risk.ts';
import {brazilDay} from './model.ts';
import {vehicleSpec,type VehicleSpec} from './vehicle-catalog.ts';
export type VehicleInput={catalog?:VehicleSpec;brand:string;model:string;plate:string;version:string;manufacture_year:number|null;model_year:number|null;color:string;chassis:string;renavam:string;mileage:number|null;fuel:string;store:string;notes:string};
export type FinanceInput={vehicle_cents:number;down_payment_cents:number;count:number;installment_cents:number;first_due:string;sale_date:string;period:'MENSAL'|'QUINZENAL'|'SEMANAL';interest_bps:number;fine_bps:number;late_interest_bps:number;notes:string;risk_profile?:RiskProfile|null};
export type ContractRow={id:string;customer_id:string;vehicle_id:string;number:string;status:string;principal_cents:number;down_payment_cents:number;total_cents:number;sale_date:string;terms:FinanceInput;created_at:string;updated_at:string};
export type VehicleRow=VehicleInput&{id:string;customer_id:string;details:VehicleInput;created_at:string};
export const validId=(value:string)=>/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(value);
export function moneyInput(value:string){const clean=value.trim();if(!/^\d{1,9}(,\d{1,2})?$/.test(clean))throw new Error('Informe valores em reais, sem ponto de milhar. Exemplo: 1250,50.');const [whole,fraction='']=clean.split(',');return Number(whole)*100+Number(fraction.padEnd(2,'0'));}
export function realDate(value:string){return /^\d{4}-\d{2}-\d{2}$/.test(value)&&Number.isFinite(Date.parse(value+'T12:00:00Z'))&&new Date(value+'T12:00:00Z').toISOString().slice(0,10)===value;}
function text(value:unknown,max=160){const s=typeof value==='string'?value.trim():'';if(s.length>max)throw new Error('Texto acima do tamanho permitido.');return s;}
function integer(value:unknown,min:number,max:number){if(typeof value!=='number'||!Number.isSafeInteger(value)||value<min||value>max)throw new Error('Confira os valores e quantidades informados.');return value;}
export function contractInput(body:Record<string,unknown>,today=brazilDay()){
 const customer_id=text(body.customer_id,36),request_id=text(body.request_id,36);if(!validId(customer_id)||!validId(request_id))throw new Error('Cliente ou identificação da solicitação inválidos.');
 const v=(body.vehicle||{}) as Record<string,unknown>,f=(body.finance||{}) as Record<string,unknown>;
 const optionalNumber=(value:unknown,min:number,max:number)=>value===null||value===undefined?null:integer(value,min,max);
 const vehicle:VehicleInput={brand:text(v.brand),model:text(v.model),plate:text(v.plate,10).replace(/[^a-z0-9]/gi,'').toUpperCase(),version:text(v.version),manufacture_year:optionalNumber(v.manufacture_year,1900,Number(today.slice(0,4))+1),model_year:optionalNumber(v.model_year,1900,Number(today.slice(0,4))+2),color:text(v.color,60),chassis:text(v.chassis,17).toUpperCase(),renavam:text(v.renavam,11),mileage:optionalNumber(v.mileage,0,10000000),fuel:text(v.fuel,40),store:text(v.store),notes:text(v.notes,2000)};
 if(v.catalog){vehicle.catalog=vehicleSpec(v.catalog);vehicle.brand=vehicle.catalog.brand;vehicle.model=vehicle.catalog.model;vehicle.version=vehicle.catalog.version;vehicle.model_year=vehicle.catalog.year;}
 if(vehicle.brand&&vehicle.brand.length<2||vehicle.model&&vehicle.model.length<2||vehicle.plate&&!(/^[A-Z]{3}\d[A-Z0-9]\d{2}$/).test(vehicle.plate)||vehicle.chassis&&!/^[A-HJ-NPR-Z0-9]{17}$/.test(vehicle.chassis)||vehicle.renavam&&!/^\d{9,11}$/.test(vehicle.renavam))throw new Error('Confira marca, modelo, placa, chassi e RENAVAM.');
 const finance:FinanceInput={vehicle_cents:integer(f.vehicle_cents,1,1000000000),down_payment_cents:integer(f.down_payment_cents,0,1000000000),count:integer(f.count,1,120),installment_cents:integer(f.installment_cents,1,1000000000),first_due:text(f.first_due,10),sale_date:text(f.sale_date,10),period:text(f.period,20) as FinanceInput['period'],interest_bps:integer(f.interest_bps??0,0,10000),fine_bps:integer(f.fine_bps??0,0,10000),late_interest_bps:integer(f.late_interest_bps??0,0,10000),risk_profile:parseRiskProfile(f.risk_profile),notes:text(f.notes,2000)};
 if(!realDate(finance.first_due)||!realDate(finance.sale_date)||finance.sale_date>today||finance.first_due<finance.sale_date||!['MENSAL','QUINZENAL','SEMANAL'].includes(finance.period))throw new Error('Confira data da venda, primeiro vencimento e periodicidade.');
 const principal=finance.vehicle_cents-finance.down_payment_cents;if(principal<=0||finance.installment_cents*finance.count<principal)throw new Error('A entrada deve ser menor que o valor do veículo e as parcelas devem cobrir o valor financiado.');
 return {customer_id,request_id,vehicle,finance};
}
export function installmentPlan(finance:FinanceInput){const [year,month,day]=finance.first_due.split('-').map(Number);return Array.from({length:finance.count},(_,index)=>{let date:Date;if(finance.period==='MENSAL'){const start=new Date(Date.UTC(year,month-1+index,1,12));const last=new Date(Date.UTC(start.getUTCFullYear(),start.getUTCMonth()+1,0,12)).getUTCDate();date=new Date(Date.UTC(start.getUTCFullYear(),start.getUTCMonth(),Math.min(day,last),12));}else date=new Date(Date.UTC(year,month-1,day+index*(finance.period==='SEMANAL'?7:15),12));return {number:index+1,due_date:date.toISOString().slice(0,10),original_cents:finance.installment_cents};});}
export const dateLabel=(date:string)=>date?date.split('-').reverse().join('/'):'—';
