import {brazilDay,type BankData,type BankPayment,type BankProfile} from './model.ts';
import {realDate,validId} from './contracts.ts';
export type Staff=BankProfile&{email:string;updated_at:string};
export const confirmed=(p:BankPayment)=>p.status!=='ESTORNADO';
export function reversalInput(body:Record<string,unknown>){const id=String(body.id||''),reason=String(body.reason||'').trim();if(!validId(id)||reason.length<3||reason.length>1000)throw new Error('Informe o pagamento e um motivo entre 3 e 1.000 caracteres.');return {p_id:id,p_reason:reason};}
export function staffInput(body:Record<string,unknown>,actor:BankProfile){const email=String(body.email||'').trim().toLowerCase(),name=String(body.name||'').trim(),role=String(body.role||'');if(!['OWNER','ADMIN'].includes(actor.role)||!['ADMIN','GERENTE','FINANCEIRO','VENDEDOR'].includes(role)||actor.role==='ADMIN'&&role==='ADMIN')throw new Error('Perfil não permitido para sua conta.');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email.length>254||name.length<2||name.length>160||typeof body.active!=='boolean')throw new Error('Confira nome, e-mail e situação do funcionário.');const expected=body.expected_updated_at===null||body.expected_updated_at===undefined?null:String(body.expected_updated_at);if(expected!==null&&!Number.isFinite(Date.parse(expected)))throw new Error('Reabra o cadastro antes de salvar.');return {p_email:email,p_name:name,p_role:role,p_active:body.active,p_expected:expected};}
export function reportPeriod(query:{from?:string;to?:string},today=brazilDay()){const from=query.from||today.slice(0,7)+'-01',to=query.to||today;if(!realDate(from)||!realDate(to)||from>to)throw new Error('Confira as datas inicial e final.');return {from,to};}
export function overdueRows(data:BankData,today=brazilDay()){const active=new Set(data.contracts.filter(c=>c.status==='ATIVO').map(c=>c.id));return data.installments.filter(i=>active.has(i.contract_id)&&i.due_date<today&&!['PAGO','CANCELADO','RENEGOCIADO'].includes(i.status)&&i.updated_cents>i.paid_cents).map(i=>({...i,balance:i.updated_cents-i.paid_cents,days:Math.round((Date.parse(today+'T12:00:00Z')-Date.parse(i.due_date+'T12:00:00Z'))/86400000)})).sort((a,b)=>b.days-a.days);}
export const inBand=(days:number,band:string)=>band==='1-5'?days<=5:band==='6-15'?days>=6&&days<=15:band==='16-30'?days>=16&&days<=30:band==='31+'?days>=31:true;
export function reportStats(data:BankData,from:string,to:string,today=brazilDay()){const sales=data.contracts.filter(c=>c.status!=='CANCELADO'&&c.sale_date>=from&&c.sale_date<=to),payments=data.payments.filter(p=>confirmed(p)&&p.paid_at>=from&&p.paid_at<=to),overdue=overdueRows(data,today),active=new Set(data.contracts.filter(c=>c.status==='ATIVO').map(c=>c.id)),balance=data.installments.filter(i=>active.has(i.contract_id)&&!['CANCELADO','RENEGOCIADO'].includes(i.status)).reduce((n,i)=>n+Math.max(0,i.updated_cents-i.paid_cents),0);return {sales,payments,overdue,balance,received:payments.reduce((n,p)=>n+p.amount_cents,0),financed:sales.reduce((n,c)=>n+c.principal_cents,0)};}
export function csvCell(value:unknown){const text=String(value??''),safe=/^[\s]*[=+@-]/.test(text)||/^[\t\r\n]/.test(text)?"'"+text:text;return '"'+safe.replaceAll('"','""')+'"';}
export const csv=(rows:unknown[][])=>'\uFEFF'+rows.map(row=>row.map(csvCell).join(';')).join('\r\n');
