export type Plan={id:string;name:string;description:string;price_cents:number;cycle_months:number;trial_days:number;enabled:boolean;updated_at:string};
export type Subscriber={id:string;store_name:string;contact_name:string;email:string;phone:string;city:string;plan_id:string|null;price_cents:number;cycle_months:number;status:string;started_at:string;canceled_at:string|null;provider:string;external_subscription_id:string|null;deployment_status:string;notes:string;updated_at:string};
export type Charge={id:string;subscriber_id:string;description:string;amount_cents:number;fee_cents:number|null;due_date:string;status:string;paid_at:string|null;received_at:string|null;refunded_cents:number;refunded_at:string|null;source:string;environment:string;updated_at:string};
export type Cost={id:string;description:string;category:string;amount_cents:number;due_date:string;paid_at:string|null;updated_at:string};
export type PlatformData={plans:Plan[];subscribers:Subscriber[];charges:Charge[];costs:Cost[];settings:{id:number;provider:string;environment:string;grace_days:number;notes:string;updated_at:string};events:{id:string;provider:string;environment:string;kind:string;processed_at:string;outcome:string}[];audit:{id:number;entity:string;action:string;created_at:string}[];integration:{asaas_ready:boolean}};
export const platformKinds=['plans','subscribers','charges','costs','settings'] as const;
export type PlatformKind=typeof platformKinds[number];
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const fail=()=>{throw new Error('Confira os campos do cadastro.');};
function text(v:unknown,min:number,max:number){if(typeof v!=='string'||v.trim().length<min||v.trim().length>max||/[\x00-\x1f]/.test(v))return fail();return v.trim();}
function num(v:unknown,min=0,max=100000000){if(typeof v!=='number'||!Number.isSafeInteger(v)||v<min||v>max)return fail();return v;}
function choice(v:unknown,list:readonly string[]){if(typeof v!=='string'||!list.includes(v))return fail();return v;}
function date(v:unknown,optional=false){if(optional&&(v===null||v===''))return null;const s=text(v,10,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(s)||!Number.isFinite(Date.parse(s+'T12:00:00Z'))||new Date(s+'T12:00:00Z').toISOString().slice(0,10)!==s||s<'2000-01-01'||s>'2100-12-31')return fail();return s;}
export function platformInput(kind:PlatformKind,b:Record<string,unknown>,today:string){
 if(kind==='plans')return {name:text(b.name,2,100),description:text(b.description||'',0,1000),price_cents:num(b.price_cents,1),cycle_months:num(b.cycle_months,1,12)===12?12:b.cycle_months===1?1:fail(),trial_days:num(b.trial_days,0,90),enabled:typeof b.enabled==='boolean'?b.enabled:fail()};
 if(kind==='subscribers'){const started=date(b.started_at)!,status=choice(b.status,['PROSPECTO','TESTE','ATIVO','ATRASADO','CANCELADO']),canceled=date(b.canceled_at,true);const email=text(b.email,3,254).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||started>today||(status==='CANCELADO')!==!!canceled||canceled&&(canceled<started||canceled>today)||b.plan_id&&!uuid.test(String(b.plan_id)))return fail();return {store_name:text(b.store_name,2,160),contact_name:text(b.contact_name,2,160),email,phone:text(b.phone||'',0,30),city:text(b.city||'',0,100),plan_id:b.plan_id||null,price_cents:num(b.price_cents),cycle_months:b.cycle_months===1||b.cycle_months===12?b.cycle_months:fail(),status,started_at:started,canceled_at:canceled,provider:choice(b.provider,['MANUAL','ASAAS','STRIPE','MERCADO_PAGO']),external_subscription_id:b.external_subscription_id?text(b.external_subscription_id,1,120):null,deployment_status:choice(b.deployment_status,['PENDENTE','PREPARANDO','ISOLADO_VALIDADO']),notes:text(b.notes||'',0,2000)};}
 if(kind==='charges'){if(!uuid.test(String(b.subscriber_id)))return fail();const amount=num(b.amount_cents,1),status=choice(b.status,['PENDENTE','CONFIRMADO','RECEBIDO','CANCELADO']),paid=date(b.paid_at,true),received=date(b.received_at,true);if(['CONFIRMADO','RECEBIDO'].includes(status)&&!paid||status==='RECEBIDO'&&!received||status==='CONFIRMADO'&&received||paid&&paid>today||received&&(!paid||received<paid||received>today)||['PENDENTE','CANCELADO'].includes(status)&&(paid||received))return fail();return {subscriber_id:b.subscriber_id,description:text(b.description,2,200),amount_cents:amount,fee_cents:b.fee_cents===null?null:num(b.fee_cents,0,amount),due_date:date(b.due_date),status,paid_at:paid,received_at:received,source:'MANUAL',environment:'PRODUCTION'};}
 if(kind==='costs'){const paid=date(b.paid_at,true);if(paid&&paid>today)return fail();return {description:text(b.description,2,200),category:choice(b.category,['HOSPEDAGEM','IA','WHATSAPP','MARKETING','SUPORTE','IMPOSTOS','OUTROS']),amount_cents:num(b.amount_cents,1),due_date:date(b.due_date),paid_at:paid};}
 return {provider:choice(b.provider,['NAO_CONFIGURADO','ASAAS','STRIPE','MERCADO_PAGO']),environment:choice(b.environment,['PRODUCTION','SANDBOX']),grace_days:num(b.grace_days,0,30),notes:text(b.notes||'',0,2000)};
}
export function platformSummary(d:Pick<PlatformData,'subscribers'|'charges'|'costs'>,month:string,today:string){
 const active=d.subscribers.filter(s=>s.status==='ATIVO'&&s.started_at<=today),mrr=active.reduce((n,s)=>n+s.price_cents/s.cycle_months,0),live=d.charges.filter(c=>c.environment==='PRODUCTION'),pending=live.filter(c=>c.status==='PENDENTE');
 const received=live.filter(c=>c.received_at&&c.received_at<=today&&c.received_at.startsWith(month)&&c.status!=='REVISAO'),refunds=live.filter(c=>c.refunded_at&&c.refunded_at<=today&&c.refunded_at.startsWith(month)),paidCosts=d.costs.filter(c=>c.paid_at&&c.paid_at<=today&&c.paid_at.startsWith(month));
 const gross=received.reduce((n,c)=>n+c.amount_cents,0),fees=received.reduce((n,c)=>n+(c.fee_cents||0),0),refund=refunds.reduce((n,c)=>n+c.refunded_cents,0),cost=paidCosts.reduce((n,c)=>n+c.amount_cents,0),unknownFees=received.filter(c=>c.fee_cents===null).length;
 const cash=live.reduce((n,c)=>n+(c.received_at&&c.received_at<=today&&c.status!=='REVISAO'?c.amount_cents-(c.fee_cents||0):0)-(c.refunded_at&&c.refunded_at<=today?c.refunded_cents:0),0)-d.costs.filter(c=>c.paid_at&&c.paid_at<=today).reduce((n,c)=>n+c.amount_cents,0);
 const atStart=d.subscribers.filter(s=>s.started_at<month+'-01'&&(!s.canceled_at||s.canceled_at>=month+'-01')&&s.price_cents>0&&s.status!=='PROSPECTO').length,canceled=d.subscribers.filter(s=>s.canceled_at?.startsWith(month)&&s.started_at<month+'-01').length;
 return {active:active.length,trials:d.subscribers.filter(s=>s.status==='TESTE').length,prospects:d.subscribers.filter(s=>s.status==='PROSPECTO').length,mrr:Math.round(mrr),arr:Math.round(mrr*12),gross,fees,refund,cost,result:gross-fees-refund-cost,cash,unknownFees,allUnknownFees:live.filter(c=>c.received_at&&c.fee_cents===null).length,pending:pending.reduce((n,c)=>n+c.amount_cents,0),overdue:pending.filter(c=>c.due_date<today).reduce((n,c)=>n+c.amount_cents,0),confirmed:live.filter(c=>c.status==='CONFIRMADO').reduce((n,c)=>n+c.amount_cents,0),churn:atStart?Math.round(canceled/atStart*1000)/10:null,canceled,setupPending:d.subscribers.filter(s=>s.deployment_status!=='ISOLADO_VALIDADO').length};
}
export function platformCsv(rows:Record<string,unknown>[]){if(!rows.length)return '';const keys=Object.keys(rows[0]);const cell=(v:unknown)=>{let s=String(v??'');if(/^[\s]*[=+@-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};return '\ufeff'+[keys.map(cell).join(';'),...rows.map(r=>keys.map(k=>cell(r[k])).join(';'))].join('\r\n');}
