import {redirect} from 'next/navigation';
import {bankPath} from './model';
import {cookies} from 'next/headers';
import {config} from '@/lib/server';
import {canBank,type BankProfile,type BankData} from './model';
export class BankError extends Error{constructor(message:string,public status=403){super(message);}}
export const cookieName='icom-bank-session';
export async function bankQuery<T>(token:string,path:string,method='GET',body?:unknown):Promise<T>{const {url,key}=config();const response=await fetch(`${url}/rest/v1/${path}`,{method,headers:{apikey:key,Authorization:`Bearer ${token}`,'Content-Type':'application/json',Prefer:'return=representation'},body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'});if(!response.ok){if(response.status===409)throw new BankError('CPF já cadastrado.',409);throw new BankError('Não foi possível acessar os dados do ICOM Bank.',response.status===401?401:400);}const text=await response.text();return text?JSON.parse(text):undefined as T;}
export async function bankAuthorize(section='dashboard',explicitToken?:string){const token=explicitToken||(await cookies()).get(cookieName)?.value;if(!token)throw new BankError('Entre no ICOM Bank.',401);const {url,key}=config();const userResponse=await fetch(`${url}/auth/v1/user`,{headers:{apikey:key,Authorization:`Bearer ${token}`},cache:'no-store'});if(!userResponse.ok)throw new BankError('Sua sessão expirou. Entre novamente.',401);const user=await userResponse.json() as {id:string};const [profile]=await bankQuery<BankProfile[]>(token,`icom_bank_user_access?user_id=eq.${encodeURIComponent(user.id)}&active=eq.true&select=user_id,name,role,active`);if(!profile||!canBank(profile.role,section))throw new BankError('Sua conta não possui autorização para esta área do ICOM Bank.');return {token,profile};}
export function bankError(error:unknown){const status=error instanceof BankError?error.status:400;return Response.json({error:error instanceof BankError?error.message:'Não foi possível concluir. Confira os dados e tente novamente.'},{status,headers:{'Cache-Control':'no-store'}});}
export function bankOrigin(req:Request){const origin=req.headers.get('origin');if(!origin||origin!==new URL(req.url).origin&&origin!==process.env.APP_URL)throw new BankError('Origem da solicitação inválida.');}
async function bankAll(token:string,path:string){const clean=path.replace(/&limit=\d+/,'');const rows:unknown[]=[];for(let offset=0;offset<100000;offset+=1000){const batch=await bankQuery<unknown[]>(token,clean+`&limit=1000&offset=${offset}`);rows.push(...batch);if(batch.length<1000)return rows;}throw new BankError('Volume de dados acima do limite desta fase. Solicite um relatório paginado.',400);}
export async function bankData(token:string,role:BankProfile['role']):Promise<BankData>{const paths=['icom_bank_customers?select=id,name,cpf,phone,email,status,assigned_to,created_at&order=created_at.desc&limit=1000','icom_bank_contracts?select=id,customer_id,vehicle_id,number,status,principal_cents,total_cents,sale_date&limit=10000','icom_bank_installments?select=*&limit=10000','icom_bank_payments?select=id,installment_id,amount_cents,paid_at,created_at&order=created_at.desc&limit=10000','icom_bank_payment_proofs?select=id,installment_id,informed_cents,status,created_at&order=created_at.desc&limit=10000','icom_bank_vehicles?select=id,customer_id,brand,model,plate&limit=10000','icom_bank_system_settings?id=eq.1&select=company_name,pix_key,pix_type'];const results=await Promise.all(paths.map((path,i)=>i===0&&role==='FINANCEIRO'?Promise.resolve([]):i===6?bankQuery<unknown[]>(token,path):bankAll(token,path)));return {customers:results[0] as BankData['customers'],contracts:results[1] as BankData['contracts'],installments:results[2] as BankData['installments'],payments:results[3] as BankData['payments'],proofs:results[4] as BankData['proofs'],vehicles:results[5] as BankData['vehicles'],settings:(results[6][0]||null) as BankData['settings']};}

export async function bankPage(section='dashboard'){try{return await bankAuthorize(section);}catch(error){redirect(bankPath(error instanceof BankError&&error.status===403&&section!=='dashboard'?'/dashboard?denied=1':'/login'));}}
