-- Run as an administrative SQL validation transaction. All fixtures are rolled back.
do $$ declare owner_id uuid;other_id uuid;origin_id uuid:=gen_random_uuid();request_id uuid:=gen_random_uuid();expense_id uuid:=gen_random_uuid();file_id uuid:=gen_random_uuid();payload jsonb;r jsonb;s public.icom_bank_stock_vehicles;p public.icom_bank_payables;q public.icom_bank_payables;e public.icom_bank_admin_entries;old_time timestamptz;today date:=(now() at time zone 'America/Sao_Paulo')::date;begin
 select user_id into owner_id from public.icom_bank_user_access where active and role='OWNER' limit 1;
 if owner_id is null then raise exception 'Owner fixture missing';end if;
 begin
  perform set_config('request.jwt.claim.sub',owner_id::text,true);
  payload:=jsonb_build_object('id',origin_id,'kind','VENDA','scope','LOJA','entry_date',today,'description','TESTE CONTAS ROLLBACK','category','Venda','status','PREVISTO','amount_cents',5700000,'details','{"vehicle":"Teste","purchase_cents":8500000,"vehicle_cost_cents":250000,"commission_cents":165000,"sale_cents":10200000,"trade_in":true,"trade_vehicle":"GM Onix","trade_plate":"PAG9Z99","trade_year":2020,"trade_value_cents":5000000,"trade_has_debts":true,"trade_ipva_cents":100000,"trade_fines_cents":50000,"trade_has_payoff":true,"trade_payoff_cents":350000,"trade_payoff_bank":"Safra","payment_method":"PIX"}'::jsonb);
  r:=public.icom_bank_save_admin_entry(payload,null);
  select * into strict s from public.icom_bank_stock_vehicles where origin_entry_id=origin_id;
  if (select count(*) from public.icom_bank_payables where stock_id=s.id)<>3 then raise exception 'Three trade debts not generated';end if;
  select * into strict p from public.icom_bank_payables where stock_id=s.id and kind='IPVA';old_time:=p.updated_at;
  if p.due_date is not null or p.status<>'PENDENTE' then raise exception 'Invented due date/payment';end if;
  begin perform public.icom_bank_pay_trade_debt(p.id,request_id,today,'PIX',null,null,p.updated_at);raise exception 'Planned source paid';exception when raise_exception then if sqlerrm<>'BANK_PAYABLE_INVALID' then raise;end if;end;
  perform public.icom_bank_schedule_payable(p.id,today-1,'Teste',p.updated_at);
  begin perform public.icom_bank_schedule_payable(p.id,today,'Teste',old_time);raise exception 'Stale schedule accepted';exception when raise_exception then if sqlerrm<>'BANK_PAYABLE_CHANGED' then raise;end if;end;
  select * into strict p from public.icom_bank_payables where id=p.id;
  for other_id in select user_id from public.icom_bank_user_access where active and role<>'OWNER' loop
   perform set_config('request.jwt.claim.sub',other_id::text,true);
   execute 'set local role authenticated';
   if exists(select 1 from public.icom_bank_payables) or exists(select 1 from public.icom_bank_payable_files) or exists(select 1 from public.icom_bank_payable_history) then raise exception 'Other role read private obligations';end if;
   begin perform public.icom_bank_schedule_payable(p.id,today,'',p.updated_at);raise exception 'Other role scheduled debt';exception when insufficient_privilege then null;end;
   begin perform public.icom_bank_pay_trade_debt(p.id,request_id,today,'PIX',null,null,p.updated_at);raise exception 'Other role paid debt';exception when insufficient_privilege then null;end;
   begin perform public.icom_bank_reverse_payable(p.id,'Teste',p.updated_at);raise exception 'Other role reversed debt';exception when insufficient_privilege then null;end;
   begin perform public.icom_bank_reserve_payable_file(file_id,p.id,'application/pdf',10,repeat('a',64));raise exception 'Other role reserved file';exception when insufficient_privilege then null;end;
   execute 'reset role';
  end loop;
  perform set_config('request.jwt.claim.sub',owner_id::text,true);
  r:=public.icom_bank_save_admin_entry(payload||'{"status":"REALIZADO"}',(r->>'updated_at')::timestamptz);
  select * into strict s from public.icom_bank_stock_vehicles where id=s.id;
  begin perform public.icom_bank_pay_trade_debt(p.id,request_id,today+1,'PIX',null,null,p.updated_at);raise exception 'Future paid date accepted';exception when raise_exception then if sqlerrm<>'BANK_PAYABLE_INVALID' then raise;end if;end;
  begin perform public.icom_bank_pay_trade_debt(p.id,request_id,today,'PIX',file_id,null,p.updated_at);raise exception 'Unknown receipt accepted';exception when raise_exception then if sqlerrm<>'BANK_PAYABLE_FILE' then raise;end if;end;
  perform public.icom_bank_reserve_payable_file(file_id,p.id,'application/pdf',10,repeat('a',64));
  perform public.icom_bank_reserve_payable_file(file_id,p.id,'application/pdf',10,repeat('a',64));
  begin perform public.icom_bank_submit_payable_file(file_id);raise exception 'Missing upload accepted';exception when raise_exception then if sqlerrm<>'BANK_PAYABLE_FILE' then raise;end if;end;
  perform public.icom_bank_pay_trade_debt(p.id,request_id,today,'PIX',null,null,p.updated_at);
  perform public.icom_bank_pay_trade_debt(p.id,request_id,today,'PIX',null,null,p.updated_at);
  select * into strict p from public.icom_bank_payables where id=p.id;
  select * into strict e from public.icom_bank_admin_entries where id=request_id;
  if e.amount_cents<>100000 or e.details ? 'stock_id' or not e.active or p.status<>'PAGO' or (select count(*) from public.icom_bank_admin_history where entry_id=request_id)<>1 then raise exception 'Wrong cash/prep accounting or duplicate retry';end if;
  if (select purchase_cents from public.icom_bank_stock_vehicles where id=s.id)<>5000000 then raise exception 'Gross acquisition cost increased';end if;
  begin perform public.icom_bank_pay_trade_debt(p.id,gen_random_uuid(),today,'PIX',null,null,p.updated_at);raise exception 'Second payment accepted';exception when raise_exception then if sqlerrm<>'BANK_PAYABLE_CLOSED' then raise;end if;end;
  begin perform public.icom_bank_archive_admin_entry(e.id,false,e.updated_at);raise exception 'Linked cash independently archived';exception when raise_exception then if sqlerrm<>'BANK_PAYABLE_LEDGER_LOCKED' then raise;end if;end;
  begin perform public.icom_bank_save_admin_entry(to_jsonb(e)||'{"amount_cents":999}',e.updated_at);raise exception 'Linked cash edited';exception when raise_exception then if sqlerrm<>'BANK_PAYABLE_LEDGER_LOCKED' then raise;end if;end;
  begin perform public.icom_bank_archive_admin_entry(origin_id,false,(r->>'updated_at')::timestamptz);raise exception 'Paid origin archived';exception when raise_exception then if sqlerrm<>'BANK_PAYABLE_SOURCE_LOCKED' then raise;end if;end;
  begin perform public.icom_bank_save_admin_entry(payload||jsonb_build_object('status','REALIZADO','details',(payload->'details')||'{"trade_ipva_cents":200000}'),(r->>'updated_at')::timestamptz);raise exception 'Paid source amount changed';exception when raise_exception then if sqlerrm<>'BANK_PAYABLE_SOURCE_LOCKED' then raise;end if;end;
  for q in select * from public.icom_bank_payables where stock_id=s.id and status='PENDENTE' loop perform public.icom_bank_pay_trade_debt(q.id,gen_random_uuid(),today,'BOLETO',null,null,q.updated_at);end loop;
  if (select status from public.icom_bank_stock_vehicles where id=s.id)<>'EM_PREPARACAO' then raise exception 'Settled obligations did not release preparation';end if;
  perform public.icom_bank_reverse_payable(p.id,'Correção teste',p.updated_at);
  perform public.icom_bank_reverse_payable(p.id,'Correção teste',p.updated_at);
  select * into strict p from public.icom_bank_payables where id=p.id;
  select * into strict e from public.icom_bank_admin_entries where id=request_id;
  if e.active or p.status<>'PENDENTE' or p.ledger_entry_id is not null or (select status from public.icom_bank_stock_vehicles where id=s.id)<>'AGUARDANDO_QUITACAO' then raise exception 'Reversal inconsistent';end if;
  begin perform public.icom_bank_archive_admin_entry(e.id,true,e.updated_at);raise exception 'Reversed cash restored independently';exception when raise_exception then if sqlerrm<>'BANK_PAYABLE_LEDGER_LOCKED' then raise;end if;end;
  perform public.icom_bank_save_admin_entry(jsonb_build_object('id',expense_id,'kind','CUSTO','scope','LOJA','entry_date',today,'description','Saída existente teste','category','Débitos','status','REALIZADO','amount_cents',100000,'details','{"payment_method":"PIX"}'::jsonb),null);
  perform public.icom_bank_pay_trade_debt(p.id,gen_random_uuid(),today,'PIX',null,expense_id,p.updated_at);
  select * into strict p from public.icom_bank_payables where id=p.id;
  if p.ledger_entry_id<>expense_id or (select count(*) from icom_bank_internal.payable_ledger_links where payable_id=p.id)<>2 then raise exception 'Existing cash not linked or history lost';end if;
  if exists(select 1 from public.icom_bank_audit_logs where entity_id=p.id and details<>'{"module":"CONTAS_A_PAGAR"}'::jsonb) then raise exception 'Financial snapshot leaked to general audit';end if;
  raise exception using errcode='P0002',message='ROLLBACK_PAYABLE_VALIDATION';
 exception when no_data_found then if sqlerrm<>'ROLLBACK_PAYABLE_VALIDATION' then raise;end if;end;
 if exists(select 1 from public.icom_bank_admin_entries where id in(origin_id,request_id,expense_id)) or exists(select 1 from public.icom_bank_payable_files where id=file_id) then raise exception 'Payable test fixture persisted';end if;
end $$;
