begin;
do $$ declare v_owner uuid;v_other uuid;v_customer uuid:=gen_random_uuid();v_vehicle uuid:=gen_random_uuid();v_contract uuid:=gen_random_uuid();v_i uuid:=gen_random_uuid();v_i2 uuid:=gen_random_uuid();begin
 select user_id into v_owner from public.icom_bank_user_access where role='OWNER' and active limit 1;
 select id into v_other from auth.users u where id<>v_owner and not exists(select 1 from public.icom_bank_user_access a where a.user_id=u.id) limit 1;
 if v_owner is null or v_other is null then raise exception 'Missing test identities';end if;
 perform set_config('test.owner',v_owner::text,true);perform set_config('test.other',v_other::text,true);perform set_config('test.installment',v_i::text,true);perform set_config('test.installment2',v_i2::text,true);perform set_config('test.contract',v_contract::text,true);perform set_config('test.proof',gen_random_uuid()::text,true);
 perform set_config('request.jwt.claim.sub',v_owner::text,true);
 insert into public.icom_bank_user_access(user_id,name,role) values(v_other,'Teste isolado de comprovantes','VENDEDOR');
 insert into public.icom_bank_customers(id,name,cpf,created_by,assigned_to) values(v_customer,'TESTE TRANSACIONAL COMPROVANTES','99999999998',v_owner,v_other);
 insert into public.icom_bank_vehicles(id,customer_id,brand,model,plate) values(v_vehicle,v_customer,'Teste','Teste','TEST123');
 insert into public.icom_bank_contracts(id,customer_id,vehicle_id,number,seller_id,principal_cents,total_cents,sale_date) values(v_contract,v_customer,v_vehicle,'TEST-'||v_contract::text,v_other,20000,20000,(now() at time zone 'America/Sao_Paulo')::date-10);
 insert into public.icom_bank_installments(id,contract_id,number,due_date,original_cents,updated_cents) values(v_i,v_contract,1,current_date,10000,10000),(v_i2,v_contract,2,current_date+30,10000,10000);
end $$;
set local role authenticated;
do $$ declare p jsonb;begin
 perform set_config('request.jwt.claim.sub',current_setting('test.other'),true);
 p:=public.icom_bank_reserve_proof(current_setting('test.proof')::uuid,current_setting('test.installment')::uuid,10000,'application/pdf',9,repeat('a',64));
 if p->>'status'<>'ARQUIVO_PENDENTE' then raise exception 'Reservation missing';end if;
 perform set_config('test.path',p->>'object_path',true);
 perform public.icom_bank_reserve_proof(current_setting('test.proof')::uuid,current_setting('test.installment')::uuid,10000,'application/pdf',9,repeat('a',64));
 begin perform public.icom_bank_submit_proof(current_setting('test.proof')::uuid);raise exception 'Missing file accepted';exception when raise_exception then if SQLERRM<>'BANK_PROOF_MISSING' then raise;end if;end;
 begin perform public.icom_bank_reserve_proof(gen_random_uuid(),current_setting('test.installment')::uuid,10000,'application/pdf',9,repeat('a',64));raise exception 'Duplicate pending accepted';exception when raise_exception then if SQLERRM<>'BANK_PROOF_PENDING' then raise;end if;end;
 begin perform public.icom_bank_reserve_proof(current_setting('test.proof')::uuid,current_setting('test.installment')::uuid,10000,'application/pdf',9,repeat('b',64));raise exception 'Changed retry accepted';exception when raise_exception then if SQLERRM<>'BANK_PROOF_CHANGED' then raise;end if;end;
 begin perform public.icom_bank_review_proof(current_setting('test.proof')::uuid,'APROVADO',current_date);raise exception 'Seller approved';exception when raise_exception then if SQLERRM<>'BANK_FORBIDDEN' then raise;end if;end;
 -- Metadata-only fixture, not a binary upload. Entire transaction rolls back.
 insert into storage.objects(bucket_id,name,metadata) values('icom-bank-documents',current_setting('test.path'),'{"size":9,"mimetype":"application/pdf"}');
 begin insert into storage.objects(bucket_id,name,metadata) values('icom-bank-documents','unreserved/test.pdf','{}');raise exception 'Unreserved upload accepted';exception when insufficient_privilege then null;end;
 perform public.icom_bank_submit_proof(current_setting('test.proof')::uuid);
 perform public.icom_bank_submit_proof(current_setting('test.proof')::uuid);
 if exists(select 1 from public.icom_bank_payments where installment_id=current_setting('test.installment')::uuid) then raise exception 'Upload counted as payment';end if;
 if (select status from public.icom_bank_installments where id=current_setting('test.installment')::uuid)<>'COMPROVANTE_ENVIADO' then raise exception 'Submission status missing';end if;
 begin update storage.objects set metadata='{}' where name=current_setting('test.path') and bucket_id='icom-bank-documents';if found then raise exception 'Proof was overwritten';end if;exception when insufficient_privilege then null;end;
 begin update public.icom_bank_installments set status='PAGO' where id=current_setting('test.installment')::uuid;raise exception 'Direct financial mutation accepted';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claim.sub',current_setting('test.owner'),true);
 begin perform public.icom_bank_review_proof(current_setting('test.proof')::uuid,'RECUSADO',null,'');raise exception 'Empty rejection accepted';exception when raise_exception then if SQLERRM<>'BANK_PROOF_REASON' then raise;end if;end;
 perform public.icom_bank_review_proof(current_setting('test.proof')::uuid,'RECUSADO',null,'Arquivo ilegível');
 perform public.icom_bank_review_proof(current_setting('test.proof')::uuid,'RECUSADO',null,'Arquivo ilegível');
 if exists(select 1 from public.icom_bank_payments where installment_id=current_setting('test.installment')::uuid) then raise exception 'Rejection counted as payment';end if;
 perform set_config('test.proof2',gen_random_uuid()::text,true);
 p:=public.icom_bank_reserve_proof(current_setting('test.proof2')::uuid,current_setting('test.installment')::uuid,9000,'application/pdf',9,repeat('a',64));
 insert into storage.objects(bucket_id,name,metadata) values('icom-bank-documents',p->>'object_path','{"size":9,"mimetype":"application/pdf"}');
 perform public.icom_bank_submit_proof(current_setting('test.proof2')::uuid);
 begin perform public.icom_bank_review_proof(current_setting('test.proof2')::uuid,'APROVADO',(now() at time zone 'America/Sao_Paulo')::date);raise exception 'Partial payment marked paid';exception when raise_exception then if SQLERRM<>'BANK_PAYMENT_AMOUNT' then raise;end if;end;
 perform public.icom_bank_review_proof(current_setting('test.proof2')::uuid,'RECUSADO',null,'Valor não corresponde à parcela');
 perform set_config('test.proof3',gen_random_uuid()::text,true);
 p:=public.icom_bank_reserve_proof(current_setting('test.proof3')::uuid,current_setting('test.installment')::uuid,10000,'application/pdf',9,repeat('a',64));
 insert into storage.objects(bucket_id,name,metadata) values('icom-bank-documents',p->>'object_path','{"size":9,"mimetype":"application/pdf"}');
 perform public.icom_bank_submit_proof(current_setting('test.proof3')::uuid);
 begin perform public.icom_bank_review_proof(current_setting('test.proof3')::uuid,'APROVADO',current_date+1);raise exception 'Future payment accepted';exception when raise_exception then if SQLERRM<>'BANK_PAYMENT_DATE' then raise;end if;end;
 perform public.icom_bank_review_proof(current_setting('test.proof3')::uuid,'APROVADO',(now() at time zone 'America/Sao_Paulo')::date);
 perform public.icom_bank_review_proof(current_setting('test.proof3')::uuid,'APROVADO',(now() at time zone 'America/Sao_Paulo')::date);
 if (select count(*) from public.icom_bank_payments where installment_id=current_setting('test.installment')::uuid)<>1 then raise exception 'Duplicate approval';end if;
 if (select status from public.icom_bank_installments where id=current_setting('test.installment')::uuid)<>'PAGO' then raise exception 'Payment not marked';end if;
 if (select status from public.icom_bank_contracts where id=current_setting('test.contract')::uuid)<>'ATIVO' then raise exception 'Contract closed too soon';end if;
 p:=public.icom_bank_reserve_proof(gen_random_uuid(),current_setting('test.installment2')::uuid,10000,'application/pdf',9,repeat('a',64));
 insert into storage.objects(bucket_id,name,metadata) values('icom-bank-documents',p->>'object_path','{"size":9,"mimetype":"application/pdf"}');
 perform public.icom_bank_submit_proof((p->>'id')::uuid);
 perform public.icom_bank_review_proof((p->>'id')::uuid,'APROVADO',(now() at time zone 'America/Sao_Paulo')::date);
 if (select status from public.icom_bank_contracts where id=current_setting('test.contract')::uuid)<>'QUITADO' then raise exception 'Contract not closed';end if;
 if (select count(*) from public.icom_bank_audit_logs where action='PAGAMENTO_CONFIRMADO' and details->>'installment_id' in (current_setting('test.installment'),current_setting('test.installment2')))<>2 then raise exception 'Payment audit missing';end if;
end $$;
reset role;
do $$ begin update public.icom_bank_user_access set active=false where user_id=current_setting('test.other')::uuid;end $$;
set local role authenticated;
do $$ begin perform set_config('request.jwt.claim.sub',current_setting('test.other'),true);if exists(select 1 from public.icom_bank_payment_proofs where id=current_setting('test.proof')::uuid) then raise exception 'Inactive user reads proof';end if;if exists(select 1 from storage.objects where name=current_setting('test.path') and bucket_id='icom-bank-documents') then raise exception 'Inactive user reads file';end if;end $$;
reset role;
set local role anon;
do $$ begin begin perform public.icom_bank_review_proof(current_setting('test.proof')::uuid,'APROVADO',current_date);raise exception 'Anonymous approval accepted';exception when insufficient_privilege then null;end;end $$;
reset role;
rollback;
select 'Proof reserve/upload-policy/submit/reject/approve/idempotency/audit/permissions tests passed; fixtures rolled back' as result;
