begin;
do $$ declare v_owner uuid;v_other uuid;v_own uuid:=gen_random_uuid();v_foreign uuid:=gen_random_uuid();v_cpf text;v_version timestamptz;v_result jsonb;v_request uuid:=gen_random_uuid();v_finance jsonb;v_vehicle jsonb;v_count bigint;begin
 select user_id into v_owner from public.icom_bank_user_access where role='OWNER' and active limit 1;
 select id into v_other from auth.users u where id<>v_owner and not exists(select 1 from public.icom_bank_user_access a where a.user_id=u.id) limit 1;
 if v_owner is null or v_other is null then raise exception 'Test identities missing';end if;
 perform set_config('request.jwt.claim.sub',v_owner::text,true);
 insert into public.icom_bank_user_access(user_id,name,role) values(v_other,'TESTE PERFIL VENDEDOR','VENDEDOR');
 loop v_cpf:=lpad((floor(random()*100000000000)::bigint)::text,11,'0');exit when not exists(select 1 from public.icom_bank_customers where cpf=v_cpf);end loop;
 insert into public.icom_bank_customers(id,name,cpf,assigned_to,created_by,risk_profile) values(v_own,'TESTE TRANSACIONAL PERFIL',v_cpf,v_other,v_owner,'A');
 loop v_cpf:=lpad((floor(random()*100000000000)::bigint)::text,11,'0');exit when not exists(select 1 from public.icom_bank_customers where cpf=v_cpf);end loop;
 insert into public.icom_bank_customers(id,name,cpf,assigned_to,created_by) values(v_foreign,'TESTE PERFIL OUTRO CLIENTE',v_cpf,v_owner,v_owner);
 perform set_config('test.risk.owner',v_owner::text,true);perform set_config('test.risk.other',v_other::text,true);perform set_config('test.risk.own',v_own::text,true);perform set_config('test.risk.foreign',v_foreign::text,true);
 if (select details->>'risk_profile' from public.icom_bank_audit_logs where entity_id=v_own and action='CLIENTE_CRIADO')<>'A' then raise exception 'Initial profile audit missing';end if;
 select updated_at into v_version from public.icom_bank_customers where id=v_own;
 v_result:=public.icom_bank_update_customer_profile(v_own,'B',v_version);
 if v_result->>'risk_profile'<>'B' then raise exception 'Update failed';end if;
 begin perform public.icom_bank_update_customer_profile(v_own,'C',v_version);raise exception 'Stale update accepted';exception when raise_exception then if sqlerrm<>'BANK_PROFILE_CHANGED' then raise;end if;end;
 begin perform public.icom_bank_update_customer_profile(v_own,'Z',(v_result->>'updated_at')::timestamptz);raise exception 'Invalid profile accepted';exception when raise_exception then if sqlerrm<>'BANK_PROFILE_INVALID' then raise;end if;end;
 v_finance:='{"vehicle_cents":1000000,"down_payment_cents":100000,"count":3,"installment_cents":300000,"sale_date":"2026-10-03","first_due":"2028-01-31","period":"MENSAL","interest_bps":350,"fine_bps":200,"late_interest_bps":100,"risk_profile":"B"}'::jsonb;
 v_vehicle:='{"brand":"Teste","model":"Perfil","plate":"PRF9Z91"}'::jsonb;
 perform public.icom_bank_create_contract(v_own,v_request,v_vehicle,v_finance);
 perform set_config('test.risk.contract',v_request::text,true);
 perform public.icom_bank_update_customer_profile(v_own,'D',(v_result->>'updated_at')::timestamptz);
 if (select terms->>'risk_profile' from public.icom_bank_contracts where id=v_request)<>'B' or (select principal_cents from public.icom_bank_contracts where id=v_request)<>900000 or (select sum(original_cents) from public.icom_bank_installments where contract_id=v_request)<>900000 or (select terms->>'interest_bps' from public.icom_bank_contracts where id=v_request)<>'350' then raise exception 'Snapshot or manual amounts changed';end if;
 v_count:=(select count(*) from public.icom_bank_vehicles);
 begin perform public.icom_bank_create_contract(v_own,gen_random_uuid(),v_vehicle||'{"plate":"PRF9Z92"}',v_finance||'{"risk_profile":"Z"}');raise exception 'Invalid contract profile accepted';exception when check_violation then null;end;
 if (select count(*) from public.icom_bank_vehicles)<>v_count then raise exception 'Invalid profile left an orphan vehicle';end if;
 perform public.icom_bank_create_contract(v_own,gen_random_uuid(),v_vehicle||'{"plate":"PRF9Z93"}',v_finance-'risk_profile');
 if (select count(*) from public.icom_bank_audit_logs where entity_id=v_own and action='PERFIL_CLIENTE_ALTERADO')<>2 then raise exception 'Update audit failed';end if;
end $$;
set local role authenticated;
do $$ declare v_customer uuid:=current_setting('test.risk.own')::uuid;v_version timestamptz;v_result jsonb;begin
 perform set_config('request.jwt.claim.sub',current_setting('test.risk.other'),true);
 if exists(select 1 from public.icom_bank_customers where id=current_setting('test.risk.foreign')::uuid) then raise exception 'Seller saw foreign customer';end if;
 select updated_at into v_version from public.icom_bank_customers where id=v_customer;
 v_result:=public.icom_bank_update_customer_profile(v_customer,'C',v_version);
 if v_result->>'risk_profile'<>'C' then raise exception 'Seller own profile update failed';end if;
 begin perform public.icom_bank_update_customer_profile(current_setting('test.risk.foreign')::uuid,'A',now());raise exception 'Seller changed foreign customer';exception when insufficient_privilege then null;end;
 begin update public.icom_bank_customers set risk_profile='A' where id=v_customer;raise exception 'Direct update bypassed auditing';exception when insufficient_privilege then null;end;
 v_result:=public.icom_bank_update_customer_profile(v_customer,null,(v_result->>'updated_at')::timestamptz);
 if v_result->>'risk_profile' is not null then raise exception 'Clearing profile failed';end if;
end $$;
reset role;
update public.icom_bank_user_access set role='FINANCEIRO' where user_id=current_setting('test.risk.other')::uuid;
set local role authenticated;
do $$ begin begin perform public.icom_bank_update_customer_profile(current_setting('test.risk.own')::uuid,'A',now());raise exception 'Finance altered profile';exception when insufficient_privilege then null;end;end $$;
reset role;
update public.icom_bank_user_access set role='VENDEDOR',active=false where user_id=current_setting('test.risk.other')::uuid;
set local role authenticated;
do $$ begin begin perform public.icom_bank_update_customer_profile(current_setting('test.risk.own')::uuid,'A',now());raise exception 'Inactive altered profile';exception when insufficient_privilege then null;end;end $$;
reset role;
set local role anon;
do $$ begin begin perform public.icom_bank_update_customer_profile(gen_random_uuid(),'A',now());raise exception 'Anonymous altered profile';exception when insufficient_privilege then null;end;end $$;
reset role;
rollback;
select 'Manual profile, immutable contract snapshot, manual amounts, audit, stale update, RLS and authorization tests passed; all fixtures rolled back' as result;
