begin;
do $$ declare u uuid;o uuid;c uuid:=gen_random_uuid();v uuid:=gen_random_uuid();k uuid:=gen_random_uuid();i uuid:=gen_random_uuid();v_cpf text;begin
 select user_id into u from public.icom_bank_user_access where role='OWNER' and active limit 1;
 select id into o from auth.users a where id<>u and not exists(select 1 from public.icom_bank_user_access b where b.user_id=a.id) limit 1;
 if u is null or o is null then raise exception 'Test identities missing';end if;
 loop v_cpf:=(floor(random()*90000000000)+10000000000)::bigint::text;exit when not exists(select 1 from public.icom_bank_customers where icom_bank_customers.cpf=v_cpf);end loop;
 perform set_config('test.owner',u::text,true);perform set_config('test.other',o::text,true);perform set_config('test.email',(select email from auth.users where id=o),true);perform set_config('test.owner_email',(select email from auth.users where id=u),true);perform set_config('test.installment',i::text,true);perform set_config('test.contract',k::text,true);perform set_config('request.jwt.claim.sub',u::text,true);
 insert into public.icom_bank_customers(id,name,cpf,created_by,assigned_to) values(c,'TESTE ROLLBACK GESTAO',v_cpf,u,u);
 insert into public.icom_bank_vehicles(id,customer_id,brand,model,plate) values(v,c,'Teste','Gestão','TST1A00');
 insert into public.icom_bank_contracts(id,customer_id,vehicle_id,number,seller_id,principal_cents,total_cents,sale_date) values(k,c,v,'TESTE-'||k::text,u,10000,10000,(now() at time zone 'America/Sao_Paulo')::date-40);
 insert into public.icom_bank_installments(id,contract_id,number,due_date,original_cents,updated_cents) values(i,k,1,(now() at time zone 'America/Sao_Paulo')::date-10,10000,10000);
end $$;
set local role authenticated;
do $$ declare s jsonb;p jsonb;r jsonb;pay uuid;cnt integer;begin
 perform set_config('request.jwt.claim.sub',current_setting('test.owner'),true);
 s:=public.icom_bank_save_staff(current_setting('test.email'),'Equipe teste','FINANCEIRO',true,null);
 if s->>'role'<>'FINANCEIRO' then raise exception 'Staff save failed';end if;
 perform set_config('test.version',s->>'updated_at',true);
 if jsonb_array_length(public.icom_bank_list_staff())<2 then raise exception 'Staff listing failed';end if;
 begin perform public.icom_bank_save_staff(current_setting('test.email'),'Changed','VENDEDOR',true,null);raise exception 'Stale staff overwrite';exception when raise_exception then if SQLERRM<>'BANK_STAFF_CHANGED' then raise;end if;end;
 begin perform public.icom_bank_save_staff(current_setting('test.owner_email'),'Changed','ADMIN',false,null);raise exception 'Self deactivated';exception when raise_exception then if SQLERRM<>'BANK_STAFF_SELF' then raise;end if;end;
 perform set_config('request.jwt.claim.sub',current_setting('test.other'),true);
 begin perform public.icom_bank_list_staff();raise exception 'Finance reads staff';exception when raise_exception then if SQLERRM<>'BANK_FORBIDDEN' then raise;end if;end;
 if not exists(select 1 from jsonb_array_elements(public.icom_bank_collection_contacts()) a where a->>'name'='TESTE ROLLBACK GESTAO' and a->>'cpf_masked' like '***.%') then raise exception 'Collection contacts missing';end if;
 if exists(select 1 from public.icom_bank_customers where name='TESTE ROLLBACK GESTAO') then raise exception 'Finance broad customer access';end if;
 begin perform public.icom_bank_reverse_payment(gen_random_uuid(),'Motivo teste');raise exception 'Finance reversed';exception when raise_exception then if SQLERRM<>'BANK_FORBIDDEN' then raise;end if;end;
 perform set_config('request.jwt.claim.sub',current_setting('test.owner'),true);
 p:=public.icom_bank_reserve_proof(gen_random_uuid(),current_setting('test.installment')::uuid,10000,'application/pdf',9,repeat('a',64));
 insert into storage.objects(bucket_id,name,metadata) values('icom-bank-documents',p->>'object_path','{"size":9,"mimetype":"application/pdf"}');
 perform public.icom_bank_submit_proof((p->>'id')::uuid);r:=public.icom_bank_review_proof((p->>'id')::uuid,'APROVADO',(now() at time zone 'America/Sao_Paulo')::date);pay:=(r->>'payment_id')::uuid;
 if (select status from public.icom_bank_contracts where id=current_setting('test.contract')::uuid)<>'QUITADO' then raise exception 'Contract not settled';end if;
 begin perform public.icom_bank_reverse_payment(pay,'');raise exception 'Empty reason accepted';exception when raise_exception then if SQLERRM<>'BANK_REVERSAL_REASON' then raise;end if;end;
 perform public.icom_bank_reverse_payment(pay,'Teste de estorno sem pagamento real');
 perform public.icom_bank_reverse_payment(pay,'Teste de estorno sem pagamento real');
 if (select status from public.icom_bank_payments where id=pay)<>'ESTORNADO' then raise exception 'Original payment lost';end if;
 if (select status from public.icom_bank_payment_proofs where id=(p->>'id')::uuid)<>'ESTORNADO' then raise exception 'Proof not reversed';end if;
 if (select paid_cents from public.icom_bank_installments where id=current_setting('test.installment')::uuid)<>0 or (select status from public.icom_bank_installments where id=current_setting('test.installment')::uuid)<>'ATRASADO' then raise exception 'Installment not reopened';end if;
 if (select status from public.icom_bank_contracts where id=current_setting('test.contract')::uuid)<>'ATIVO' then raise exception 'Contract not reopened';end if;
 if (select count(*) from public.icom_bank_audit_logs where entity_id=pay and action='PAGAMENTO_ESTORNADO')<>1 then raise exception 'Reversal duplicated audit';end if;
 begin perform public.icom_bank_review_proof((p->>'id')::uuid,'APROVADO',current_date);raise exception 'Reversed proof reapproved';exception when raise_exception then if SQLERRM<>'BANK_PROOF_REVIEWED' then raise;end if;end;
 p:=public.icom_bank_reserve_proof(gen_random_uuid(),current_setting('test.installment')::uuid,10000,'application/pdf',9,repeat('b',64));
 insert into storage.objects(bucket_id,name,metadata) values('icom-bank-documents',p->>'object_path','{"size":9,"mimetype":"application/pdf"}');
 perform public.icom_bank_submit_proof((p->>'id')::uuid);perform public.icom_bank_review_proof((p->>'id')::uuid,'APROVADO',(now() at time zone 'America/Sao_Paulo')::date);
 select count(*) into cnt from public.icom_bank_payments where installment_id=current_setting('test.installment')::uuid;
 if cnt<>2 or (select count(*) from public.icom_bank_payments where installment_id=current_setting('test.installment')::uuid and status='CONFIRMADO')<>1 then raise exception 'Repayment after reversal failed';end if;
 s:=public.icom_bank_save_staff(current_setting('test.email'),'Admin teste','ADMIN',true,current_setting('test.version')::timestamptz);
 perform set_config('request.jwt.claim.sub',current_setting('test.other'),true);
 begin perform public.icom_bank_save_staff(current_setting('test.owner_email'),'Changed','VENDEDOR',false,null);raise exception 'Admin changed owner';exception when raise_exception then if SQLERRM<>'BANK_FORBIDDEN' then raise;end if;end;
 begin perform public.icom_bank_save_staff('new@example.invalid','Teste','ADMIN',true,null);raise exception 'Admin creates admin';exception when raise_exception then if SQLERRM<>'BANK_FORBIDDEN' then raise;end if;end;
 perform set_config('request.jwt.claim.sub',current_setting('test.owner'),true);
 s:=public.icom_bank_save_staff(current_setting('test.email'),'Vendedor teste','VENDEDOR',true,(s->>'updated_at')::timestamptz);
 perform set_config('request.jwt.claim.sub',current_setting('test.other'),true);
 begin perform public.icom_bank_collection_contacts();raise exception 'Seller collection access';exception when raise_exception then if SQLERRM<>'BANK_FORBIDDEN' then raise;end if;end;
 perform set_config('request.jwt.claim.sub',current_setting('test.owner'),true);
 perform public.icom_bank_save_staff(current_setting('test.email'),'Vendedor teste','VENDEDOR',false,(s->>'updated_at')::timestamptz);
 perform set_config('request.jwt.claim.sub',current_setting('test.other'),true);
 if icom_bank_internal.role() is not null then raise exception 'Inactive retains bank role';end if;
end $$;
reset role;
set local role anon;
do $$ begin begin perform public.icom_bank_list_staff();raise exception 'Anonymous staff access';exception when insufficient_privilege then null;end;end $$;
reset role;
rollback;
select 'Reversal/history/reapproval/staff/privacy/concurrency/permission tests passed; all fixtures rolled back' as result;
