'use client';
import {useState} from 'react';
import {appPath} from '@/lib/paths';
export default function Referral({token,received,onReceived}:{token:string;received:boolean;onReceived:()=>void}){
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[cancelled,setCancelled]=useState(false);

 return <section className="referral-card"><h2>Sua indicação</h2>{received?<p className="notice">Obrigado! Sua indicação já foi registrada.</p>:<><p>Se já tiver um contato autorizado, você pode indicar agora ou voltar a este link mais tarde.</p><button className="primary" onClick={()=>setOpen(!open)}>INDICAR ALGUÉM AGORA</button>{open&&<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const fields=new FormData(e.currentTarget);try{const response=await fetch(appPath(`/api/experience/${token}/referral`),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:fields.get('name'),phone:fields.get('phone'),permission:fields.get('permission')==='on'})});const data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error);onReceived();setOpen(false)}catch(e){setError(e instanceof Error?e.message:'Não foi possível registrar.')}finally{setBusy(false)}}}><label>Nome da pessoa<input name="name" required minLength={2} maxLength={120}/></label><label>WhatsApp com DDD<input name="phone" type="tel" inputMode="tel" required maxLength={22} placeholder="(12) 99999-9999"/></label><label className="checkbox"><input name="permission" type="checkbox" required/> A pessoa autorizou compartilhar nome e telefone com a Icom para contato.</label><button className="primary" disabled={busy}>REGISTRAR INDICAÇÃO</button></form>}<p>{cancelled?'Lembrete cancelado.':<button disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const response=await fetch(appPath(`/api/experience/${token}/referral`),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'cancel'})});const data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error);setCancelled(true)}catch(e){setError(e instanceof Error?e.message:'Não foi possível cancelar.')}finally{setBusy(false)}}}>Não quero receber lembrete</button>}</p></>}{error&&<p className="error" role="alert">{error}</p>}</section>;
}

