'use client';
import {useEffect,useRef,useState} from 'react';
import SellerWhatsApp from './SellerWhatsApp';
import {appPath} from '@/lib/paths';
import {answerLabel,type Experience} from '@/lib/experience';
import {feedbackSummary} from '@/lib/feedback';
import {phoneBR,type Connection,type WhatsappStatus} from '@/lib/whatsapp';
import type {AccessProfile} from '@/lib/access';

type Result={token?:string;id?:string;created_at?:string;whatsapp_due_at?:string|null;ok?:boolean;customer_name?:string;customer_phone?:string;whatsapp_status?:WhatsappStatus;message?:string;connection?:Connection};
type Submit=(body:Record<string,unknown>)=>Promise<Result|null>;
const date=(value:string|null|undefined)=>value?new Date(value).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo',dateStyle:'short',timeStyle:'short'}):'—';
const number=(value:number|null)=>value===null?'—':value.toLocaleString('pt-BR',{maximumFractionDigits:1});
export default function SellerPortal({auth,profile,rows,busy,error,onSubmit,onLogout,onReload,connection:initialConnection}:{auth:string;profile:AccessProfile;rows:Experience[];busy:boolean;error:string;onSubmit:Submit;onLogout:()=>void;onReload:()=>void;connection:Connection}) {
 const [tab,setTab]=useState<'feedback'|'register'|'whatsapp'>('feedback'),[query,setQuery]=useState(''),[filter,setFilter]=useState('Todos'),[notice,setNotice]=useState(''),[sendMode,setSendMode]=useState('now');
 const [connection,setConnection]=useState(initialConnection);
 const state=connection;
 const [generated,setGenerated]=useState<Result|null>(null);
 const [clock,setClock]=useState(()=>Date.now());
 useEffect(()=>{const timer=setInterval(()=>setClock(Date.now()),60000);return()=>clearInterval(timer)},[]);
 const request=useRef<{key:string;id:string}|null>(null);
 const summary=feedbackSummary(rows),mean=summary.items.find(i=>i.key==='salesperson_rating')?.mean??null;
 const filtered=rows.filter(r=>(filter==='Todos'||(filter==='Respondidos'?!!r.completed_at:!r.completed_at))&&`${r.customers.name} ${r.vehicles.name} ${r.vehicle_plate||''}`.toLowerCase().includes(query.toLowerCase()));
 function url(token:string){return `${location.origin}${appPath('/experiencia/')}${token}`}
 async function copy(token:string){try{await navigator.clipboard.writeText(url(token));setNotice('Link copiado. Cole na conversa com o cliente.')}catch{setNotice('Selecione e copie o link exibido abaixo.')}}
 function share(token:string,id:string,name:string,phone?:string){const message=`Olá, ${name.split(' ')[0]}! Como foi sua experiência com a Icom? Sua opinião é muito importante para nós. Responda pelo link: ${url(token)}`;let recipient='';try{recipient=phoneBR(phone)}catch{}return <a className="primary" href={`https://wa.me/${recipient}?text=${encodeURIComponent(message)}`} target="_blank" rel="noreferrer" onClick={()=>{void onSubmit({action:'seller_sent',id})}}>ABRIR CONVERSA NO WHATSAPP</a>}
 function delivery(token:string,id:string,name:string,phone:string|undefined,status:WhatsappStatus|undefined){if(status==='accepted')return <p className="seller-notice">Pesquisa encaminhada ao WhatsApp do cliente.</p>;if(status==='sending'||status==='unknown')return <p className="seller-notice">Envio em conferência. Atualize o painel e confira a conversa antes de reenviar.</p>;return <div className="seller-share">{state.connected&&phone?<button className="primary" disabled={busy} onClick={async()=>{const result=await onSubmit({action:'seller_whatsapp',id});if(result){setNotice(result.message||'Atualize para conferir o envio.');setGenerated(current=>current?.id===id?{...current,...result}:current)}}}>ENVIAR AUTOMATICAMENTE</button>:share(token,id,name,phone)}<button onClick={()=>copy(token)}>Copiar link</button></div>}

 return <div className="seller-portal"><header className="seller-header"><div><strong>ICOM <span>VEÍCULOS</span></strong><small>Área do vendedor</small></div><div><span>{profile.name}</span><button onClick={onLogout}>Sair</button></div></header><main>
   <nav className="seller-nav" aria-label="Área do vendedor"><button aria-pressed={tab==='feedback'} className={tab==='feedback'?'primary':''} onClick={()=>setTab('feedback')}>Meus feedbacks</button><button aria-pressed={tab==='register'} className={tab==='register'?'primary':''} onClick={()=>{setTab('register');setGenerated(null)}}>Cadastrar cliente</button><button aria-pressed={tab==='whatsapp'} className={tab==='whatsapp'?'primary':''} onClick={()=>setTab('whatsapp')}>Meu WhatsApp</button></nav>
   {error&&<div className="error" role="alert">{error}<button onClick={onReload}>Tentar novamente</button><button onClick={onLogout}>Entrar novamente</button></div>}
   {notice&&<div className="seller-notice" role="status">{notice}<button aria-label="Fechar aviso" onClick={()=>setNotice('')}>×</button></div>}
   {tab==='whatsapp'?<SellerWhatsApp auth={auth} value={connection} onChange={setConnection}/>:tab==='register'?<section className="panel seller-register"><p className="eyebrow">UMA PESQUISA PARA CADA ATENDIMENTO</p><h1>Cadastrar cliente</h1><p>Preencha os dados do cliente. Com seu WhatsApp conectado, o sistema envia a pesquisa automaticamente.</p><div className="seller-auto"><b>Vendedor: {profile.name}</b><span>Data e hora registradas automaticamente ao gerar o link.</span></div><p className="seller-notice">{state.connected?'WhatsApp conectado. Pronto para enviar pesquisas.':'Conecte seu número na aba Meu WhatsApp para os envios automáticos.'}</p><form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);const values={customer_name:String(f.get('customer_name')||''),customer_phone:String(f.get('customer_phone')||''),vehicle_name:String(f.get('vehicle_name')||''),vehicle_plate:String(f.get('vehicle_plate')||''),scheduled_at:sendMode==='later'?new Date(String(f.get('send_date'))+':00-03:00').toISOString():null};const key=JSON.stringify(values);if(request.current?.key!==key)request.current={key,id:crypto.randomUUID()};const result=await onSubmit({action:'seller_create',...values,request_id:request.current.id});if(result?.token){setGenerated({...result,customer_name:values.customer_name,customer_phone:values.customer_phone});request.current=null;form.reset();setNotice(result.message||'Cliente cadastrado.')}}}><label>Quando enviar a pesquisa?<select value={sendMode} onChange={e=>setSendMode(e.target.value)}><option value="now">Ao cadastrar o cliente</option><option value="later">Agendar data e hora</option></select></label>{sendMode==='later'&&<label>Data e hora do envio · horário de Brasília<input type="datetime-local" name="send_date" required disabled={busy}/></label>}<p>Se o WhatsApp estiver desconectado, a pesquisa aguarda na fila por até 7 dias após o horário do envio. Conecte seu número para liberar o envio.</p><label>Nome do cliente<input name="customer_name" required minLength={2} maxLength={120} placeholder="Ex.: Maria Oliveira" autoComplete="name" disabled={busy}/></label><label>Telefone / WhatsApp do cliente<input name="customer_phone" type="tel" inputMode="tel" autoComplete="tel" required maxLength={22} placeholder="Ex.: (12) 99999-9999" disabled={busy}/></label><label>Carro<input name="vehicle_name" required minLength={2} maxLength={120} placeholder="Ex.: Jeep Compass 2025" disabled={busy}/></label><label>Placa do carro<input name="vehicle_plate" required maxLength={9} placeholder="Ex.: ABC1D23 ou ABC-1234" autoCapitalize="characters" disabled={busy}/></label><button className="primary" disabled={busy}>{busy?'SALVANDO…':sendMode==='later'?'CADASTRAR E AGENDAR':state.connected?'CADASTRAR E ENVIAR PESQUISA':'CADASTRAR E COLOCAR NA FILA'}</button></form>
     {generated?.token&&<section className="seller-generated" aria-label="Link gerado"><h2>{generated.whatsapp_status==='accepted'?'Pesquisa enviada':'Cliente cadastrado'}</h2><p>Gerado em {date(generated.created_at)}</p>{generated.whatsapp_due_at&&<p>Envio programado: {date(generated.whatsapp_due_at)}</p>}<label>Link da pesquisa<input readOnly value={url(generated.token)} onFocus={e=>e.currentTarget.select()}/></label>{generated.whatsapp_due_at&&Date.parse(generated.whatsapp_due_at)>clock?<p>Pesquisa agendada. Mantenha seu WhatsApp conectado.</p>:delivery(generated.token,generated.id!,generated.customer_name||'Cliente',generated.customer_phone,generated.whatsapp_status)}</section>}
   </section>:<><div className="seller-title"><div><p className="eyebrow">SOMENTE OS SEUS ATENDIMENTOS</p><h1>Meus feedbacks</h1><p>Veja o que seus clientes acharam, item por item.</p></div><button onClick={onReload} disabled={busy}>Atualizar</button></div><div className="seller-summary"><article><span>Clientes cadastrados</span><strong>{summary.customers}</strong></article><article><span>Avaliações recebidas</span><strong>{summary.responses}</strong></article><article><span>Seu atendimento</span><strong>{number(mean)} <small>/ 5</small></strong></article></div><div className="seller-search"><input aria-label="Buscar cliente, carro ou placa" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar cliente, carro ou placa"/><select aria-label="Status da pesquisa" value={filter} onChange={e=>setFilter(e.target.value)}>{['Todos','Respondidos','Pendentes'].map(s=><option key={s}>{s}</option>)}</select></div><div className="seller-reviews">{filtered.map(row=>{const answers=row.experience_responses[0]?.answers||{};return <article key={row.id} className="panel seller-review"><div className="panel-heading"><div><h2>{row.customers.name}</h2><p>{row.vehicles.name} · <b>{row.vehicle_plate||'Placa não informada'}</b></p></div><span className={`badge ${row.completed_at?'attention':''}`}>{row.completed_at?'Respondido':'Aguardando resposta'}</span></div><div className="seller-dates"><span>Link gerado: {date(row.created_at)}</span>{row.sent_at&&<span>Compartilhamento iniciado: {date(row.sent_at)}</span>}</div>{row.completed_at?<><div className="seller-score-line"><span>Experiência de compra <b>{String(answers.overall_rating??'—')} / 5</b></span><span>Seu atendimento <b>{String(answers.salesperson_rating??'—')} / 5</b></span></div><details><summary>Ver todos os feedbacks</summary><dl className="seller-answers">{Object.entries(answers).map(([key,value])=><div key={key}><dt>{answerLabel(key)}</dt><dd>{Array.isArray(value)?value.join(', '):String(value)}{key.endsWith('_rating')?' / 5':''}</dd></div>)}</dl><small>Avaliações registradas pelo cliente. Somente leitura.</small></details></>:<><p className="muted">A pesquisa fica vinculada a você. Confira o envio abaixo.</p>{row.whatsapp_due_at&&Date.parse(row.whatsapp_due_at)>clock?<p>Agendada para {date(row.whatsapp_due_at)}. Mantenha seu WhatsApp conectado.</p>:delivery(row.token,row.id,row.customers.name,row.customers.phone,row.whatsapp_status)}</>}</article>})}{!filtered.length&&<section className="panel"><h2>{rows.length?'Nenhum resultado neste filtro.':'Seu primeiro feedback começa aqui.'}</h2><p>Cadastre o cliente com telefone para enviar a pesquisa pelo WhatsApp.</p><button className="primary" onClick={()=>setTab('register')}>CADASTRAR CLIENTE</button></section>}</div></>}
 </main><footer>EXPERIÊNCIA ICOM · Sua opinião nos leva mais longe.</footer></div>
}
