'use client';
import {useState} from 'react';
import {appPath} from '@/lib/paths';
import {SellerAvatar} from './SellerQuality';
async function preparePhoto(file:File):Promise<Blob>{
 if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024)throw new Error('Escolha uma foto JPG, PNG ou WebP de até 10 MB.');
 const bitmap=await createImageBitmap(file);try{const canvas=document.createElement('canvas');canvas.width=canvas.height=320;const context=canvas.getContext('2d');if(!context)throw new Error('Não foi possível preparar a foto.');const size=Math.min(bitmap.width,bitmap.height);context.drawImage(bitmap,(bitmap.width-size)/2,(bitmap.height-size)/2,size,size,0,0,320,320);return await new Promise<Blob>((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('Foto inválida.')),'image/jpeg',0.85));}finally{bitmap.close();}
}
export default function SellerPhoto({auth,name,photo,onSaved}:{auth:string;name:string;photo?:string|null;onSaved:()=>void}){const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');return <section className="panel"><p className="eyebrow">SEU PERFIL</p><h2>Minha foto</h2><SellerAvatar name={name} photo={photo}/><p>Escolha uma foto sua. Ela aparecerá no seu painel e no ranking da equipe.</p><label>Enviar ou trocar minha foto<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);setError('');setMessage('');try{const blob=await preparePhoto(file),form=new FormData();form.append('photo',blob,'foto.jpg');const response=await fetch(appPath('/api/seller/photo'),{method:'POST',headers:{Authorization:`Bearer ${auth}`},body:form});const data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error||'Não foi possível salvar a foto.');setMessage('Foto salva. Ela já aparece no ranking.');onSaved();}catch(error){setError(error instanceof Error?error.message:'Não foi possível enviar a foto.');}finally{setBusy(false);e.target.value='';}}}/></label><small>JPG, PNG ou WebP, até 10 MB. A imagem será recortada ao centro.</small>{busy&&<p role="status">Salvando sua foto…</p>}{error&&<p className="error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}</section>}

