'use client';
import {appPath} from '@/lib/paths';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import Warranty from './Warranty';
import Referral from './Referral';
import GoogleReview from './GoogleReview';
import type {WarrantyConfig,WarrantySession} from '@/lib/warranty';
import {phoneBR} from '@/lib/whatsapp';
import {Answers,questions} from '@/lib/experience';
type PublicData={rating_scale:5|10;warranty:WarrantyConfig;session:WarrantySession|null;referral_received:boolean;name:string;completed:boolean;answers:Answers;settings:{google_review_url:string;intro_text:string;final_text:string;estimated_time:string}};
export function Brand(){return <Link className="brand" href="/experiencia"><strong>ICOM<span>VEÍCULOS</span></strong><i>EXPERIÊNCIA</i></Link>}
export default function Survey({token}:{token?:string}) {
 const [data,setData]=useState<PublicData|null>(null),[answers,setAnswers]=useState<Answers>({}),[step,setStep]=useState(-1),[error,setError]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[warrantyOpen,setWarrantyOpen]=useState(false);
 useEffect(()=>{if(!token)return;let active=true;fetch(appPath(`/api/experience/${token}`)).then(async r=>{const d=await r.json() as PublicData&{error?:string};if(!r.ok)throw new Error(d.error);if(active){setData(d);setAnswers(d.answers);setDone(d.completed);}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[token]);
 const draftTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>{if(!token||done||step<0)return;const persist=()=>{void fetch(appPath(`/api/experience/${token}`),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({answers,complete:false,rating_scale:data?.rating_scale}),keepalive:true})};window.addEventListener("pagehide",persist);return()=>window.removeEventListener("pagehide",persist)},[token,done,step,answers,data?.rating_scale]);
 useEffect(()=>()=>{if(draftTimer.current)clearTimeout(draftTimer.current)},[]);
 const qs=questions(answers),q=qs[step];
 async function save(next:Answers,complete=false){setBusy(true);setError('');try{const r=await fetch(appPath(`/api/experience/${token}`),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({answers:next,complete,rating_scale:data?.rating_scale})});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error);if(complete)setDone(true);return true;}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar. Tente novamente.');return false;}finally{setBusy(false)}}
 async function choose(value:Answers[string]){const next={...answers,[q.key]:value};setAnswers(next);await save(next)}
 const validPhone=()=>{try{phoneBR(String(answers[q.key]||''));return true}catch{return false}};
 const answered=q&&(q.kind!=='phone'||validPhone())&&(q.optional||(answers[q.key]!==undefined&&answers[q.key]!==''&&(!Array.isArray(answers[q.key])||(answers[q.key] as string[]).length>0)));
 return <main className="survey"><header><Brand/><span>FEEDBACK DIRETO À GESTÃO</span></header><section className="survey-card" aria-live="polite">
 {data&&token&&<nav className="customer-tabs" aria-label="Etapas da experiência"><button aria-pressed={warrantyOpen} onClick={()=>setWarrantyOpen(true)}>Garantia do veículo</button><button disabled={!done&&!data.session?.acknowledged_at} aria-pressed={!warrantyOpen} onClick={()=>setWarrantyOpen(false)}>Minha avaliação</button></nav>}
 {error&&<div role="alert" className="error">{error}</div>}
 {warrantyOpen&&data&&token?<Warranty token={token} config={data.warranty} initial={data.session} readOnly={done} onContinue={async session=>{setData(current=>current?{...current,session}:current);setWarrantyOpen(false);if(!done&&session?.acknowledged_at&&await save(answers))setStep(Math.max(0,qs.findIndex(item=>!item.optional&&answers[item.key]===undefined)))}}/>:token&&!data&&!error?<p>Preparando sua experiência…</p>:done?<div className="finish"><div className="check">✓</div><p className="eyebrow">EXPERIÊNCIA REGISTRADA</p><h1>Obrigado, {data?.name}.</h1><p>Sua opinião é muito importante para a Icom.</p><p>{data?.settings.final_text}</p>{data?.settings.google_review_url&&<GoogleReview url={data.settings.google_review_url}/>}{token&&data&&['Sim, indicar agora','Sim, mais tarde'].includes(String(answers.referral_choice))&&<Referral token={token} received={data.referral_received||answers.referral_choice==='Sim, indicar agora'} onReceived={()=>setData(current=>current?{...current,referral_received:true}:current)}/>}<small>Clientes de hoje. Histórias de sempre.</small></div>:step===-1?<><p className="eyebrow">EXPERIÊNCIA ICOM</p><h1>Sua opinião nos<br/><em>leva mais longe.</em></h1><p className="intro">{data?.settings.intro_text||'Sua compra terminou, mas o nosso compromisso com a sua experiência continua. Conte como foi sua jornada com a Icom e nos ajude a melhorar cada detalhe.'}</p><div className="promises"><span>✓ {data?.settings.estimated_time||'Menos de 2 minutos'}</span><span>✓ Resposta confidencial</span><span>✓ Feedback direto à gestão</span></div>{token?<button className="primary" disabled={!data||busy} onClick={()=>setWarrantyOpen(true)}>COMEÇAR PELA GARANTIA</button>:<p className="notice">Para começar, abra o link exclusivo que a Icom enviou para você pelo WhatsApp.</p>}<aside><h3>Nosso compromisso</h3><p>Queremos que cada cliente saia da Icom com a sensação de ter feito um excelente negócio e de ter sido bem cuidado em todas as etapas.</p></aside></>:q?<><div className="step-meta"><span>SUA EXPERIÊNCIA</span><span>{step+1} de {qs.length}</span></div><progress value={step+1} max={qs.length} aria-label="Progresso da pesquisa"/><h2>{q.title}</h2>{q.help&&<p>{q.help}</p>}
 {(q.kind==='rating'||q.kind==='nps')&&<><div className="nps" role="group" aria-label={q.title}>{Array.from({length:11},(_,i)=>i).map(n=><button key={n} disabled={busy} aria-label={`Nota ${n} de 10`} aria-pressed={answers[q.key]===n} className={answers[q.key]===n?'selected':''} onClick={()=>choose(n)}>{n}</button>)}</div><div className="scale-label"><span>{q.kind==='rating'?'Muito ruim':'Não recomendaria'}</span><span>{q.kind==='rating'?'Excelente':'Com certeza recomendaria'}</span></div></>}
 {(q.kind==='options'||q.kind==='multi')&&<div className="options">{q.kind==='multi'&&<small>Você pode escolher mais de uma opção.</small>}{q.options?.map(o=>{const selected=q.kind==='multi'?(answers[q.key] as string[]||[]).includes(o):answers[q.key]===o;return <button disabled={busy} key={o} className={selected?'selected':''} aria-pressed={selected} onClick={()=>choose(q.kind==='multi'?selected?(answers[q.key] as string[]).filter(v=>v!==o):[...(answers[q.key] as string[]||[]),o]:o)}><span>{o}</span><b>{selected?'✓':'○'}</b></button>})}</div>}
 {(q.kind==='phone'||q.key==='referral_name')&&<label>{q.kind==='phone'?'Telefone com DDD':'Nome da pessoa'}<input type={q.kind==='phone'?'tel':'text'} maxLength={q.kind==='phone'?20:120} value={String(answers[q.key]||'')} onChange={e=>setAnswers({...answers,[q.key]:e.target.value})} placeholder={q.kind==='phone'?'(11) 99999-9999':'Nome completo'}/></label>}
 {q.kind==='text'&&q.key!=='referral_name'&&<label>{q.optional?'Comentário opcional':'Seu comentário'}<textarea maxLength={4000} value={String(answers[q.key]||'')} onChange={e=>{const next={...answers,[q.key]:e.target.value};setAnswers(next);if(draftTimer.current)clearTimeout(draftTimer.current);draftTimer.current=setTimeout(()=>{void save(next)},500)}} onBlur={()=>{if(draftTimer.current)clearTimeout(draftTimer.current);void save(answers)}} placeholder="Conte com suas palavras…"/></label>}
 <div className="survey-nav"><button disabled={busy} onClick={()=>setStep(step-1)}>Voltar</button><small>{busy?'Salvando…':'Progresso salvo'}</small><button className="primary" disabled={!answered||busy} onClick={async()=>{if(draftTimer.current)clearTimeout(draftTimer.current);if(await save(answers,step===qs.length-1)&&step<qs.length-1)setStep(step+1)}}>{step===qs.length-1?'CONCLUIR':'AVANÇAR'}</button></div></>:null}</section><footer>ICOM VEÍCULOS <span>Clientes de hoje. Histórias de sempre.</span></footer></main>
}

