'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {Answers,questions} from '@/lib/experience';
type PublicData={name:string;completed:boolean;answers:Answers;settings:{google_review_url:string;intro_text:string;final_text:string;estimated_time:string}};
export function Brand(){return <Link className="brand" href="/experiencia"><strong>ICOM<span>VEÍCULOS</span></strong><i>EXPERIÊNCIA</i></Link>}
export default function Survey({token}:{token?:string}) {
 const [data,setData]=useState<PublicData|null>(null),[answers,setAnswers]=useState<Answers>({}),[step,setStep]=useState(-1),[error,setError]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState(false);
 useEffect(()=>{if(!token)return;let active=true;fetch(`/api/experience/${token}`).then(async r=>{const d=await r.json() as PublicData&{error?:string};if(!r.ok)throw new Error(d.error);if(active){setData(d);setAnswers(d.answers);setDone(d.completed);}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[token]);
 const draftTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>{if(!token||done||step<0)return;const persist=()=>{void fetch(`/api/experience/${token}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({answers,complete:false}),keepalive:true})};window.addEventListener("pagehide",persist);return()=>window.removeEventListener("pagehide",persist)},[token,done,step,answers]);
 useEffect(()=>()=>{if(draftTimer.current)clearTimeout(draftTimer.current)},[]);
 const qs=questions(answers),q=qs[step];
 async function save(next:Answers,complete=false){setBusy(true);setError('');try{const r=await fetch(`/api/experience/${token}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({answers:next,complete})});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error);if(complete)setDone(true);return true;}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar. Tente novamente.');return false;}finally{setBusy(false)}}
 async function choose(value:Answers[string]){const next={...answers,[q.key]:value};setAnswers(next);await save(next)}
 const answered=q&&(q.optional||(answers[q.key]!==undefined&&answers[q.key]!==''&&(!Array.isArray(answers[q.key])||(answers[q.key] as string[]).length>0)));
 return <main className="survey"><header><Brand/><span>FEEDBACK DIRETO À GESTÃO</span></header><section className="survey-card" aria-live="polite">
 {error&&<div role="alert" className="error">{error}</div>}
 {token&&!data&&!error?<p>Preparando sua experiência…</p>:done?<div className="finish"><div className="check">✓</div><p className="eyebrow">EXPERIÊNCIA REGISTRADA</p><h1>Obrigado, {data?.name}.</h1><p>Sua opinião é muito importante para a Icom.</p><p>{data?.settings.final_text}</p>{data?.settings.google_review_url&&<div className="google"><p>Se desejar, você também pode compartilhar sua experiência no Google.</p><a className="primary" href={data.settings.google_review_url} target="_blank" rel="noreferrer">AVALIAR A ICOM NO GOOGLE</a></div>}<small>Clientes de hoje. Histórias de sempre.</small></div>:step===-1?<><p className="eyebrow">EXPERIÊNCIA ICOM</p><h1>Sua opinião nos<br/><em>leva mais longe.</em></h1><p className="intro">{data?.settings.intro_text||'Sua compra terminou, mas o nosso compromisso com a sua experiência continua. Conte como foi sua jornada com a Icom e nos ajude a melhorar cada detalhe.'}</p><div className="promises"><span>✓ {data?.settings.estimated_time||'Menos de 2 minutos'}</span><span>✓ Resposta confidencial</span><span>✓ Feedback direto à gestão</span></div>{token?<button className="primary" disabled={!data||busy} onClick={async()=>{if(await save(answers))setStep(Math.max(0,qs.findIndex(item=>!item.optional&&answers[item.key]===undefined)))}}>COMEÇAR MINHA AVALIAÇÃO</button>:<p className="notice">Para começar, abra o link exclusivo que a Icom enviou para você pelo WhatsApp.</p>}<aside><h3>Nosso compromisso</h3><p>Queremos que cada cliente saia da Icom com a sensação de ter feito um excelente negócio e de ter sido bem cuidado em todas as etapas.</p></aside></>:q?<><div className="step-meta"><span>SUA EXPERIÊNCIA</span><span>{step+1} de {qs.length}</span></div><progress value={step+1} max={qs.length} aria-label="Progresso da pesquisa"/><h2>{q.title}</h2>{q.help&&<p>{q.help}</p>}
 {(q.kind==='rating'||q.kind==='nps')&&<><div className={q.kind==='rating'?'stars':'nps'} role="group" aria-label={q.title}>{Array.from({length:q.kind==='rating'?5:11},(_,i)=>q.kind==='rating'?i+1:i).map(n=><button key={n} disabled={busy} aria-label={`${n} ${q.kind==='rating'?'estrelas':'pontos'}`} aria-pressed={answers[q.key]===n} className={answers[q.key]===n?'selected':''} onClick={()=>choose(n)}>{q.kind==='rating'?<><span>★</span><small>{n}</small></>:n}</button>)}</div><div className="scale-label"><span>{q.kind==='rating'?'Muito ruim':'Não recomendaria'}</span><span>{q.kind==='rating'?'Excelente':'Com certeza recomendaria'}</span></div></>}
 {(q.kind==='options'||q.kind==='multi')&&<div className="options">{q.kind==='multi'&&<small>Você pode escolher mais de uma opção.</small>}{q.options?.map(o=>{const selected=q.kind==='multi'?(answers[q.key] as string[]||[]).includes(o):answers[q.key]===o;return <button disabled={busy} key={o} className={selected?'selected':''} aria-pressed={selected} onClick={()=>choose(q.kind==='multi'?selected?(answers[q.key] as string[]).filter(v=>v!==o):[...(answers[q.key] as string[]||[]),o]:o)}><span>{o}</span><b>{selected?'✓':'○'}</b></button>})}</div>}
 {q.kind==='text'&&<label>{q.optional?'Comentário opcional':'Seu comentário'}<textarea maxLength={4000} value={String(answers[q.key]||'')} onChange={e=>{const next={...answers,[q.key]:e.target.value};setAnswers(next);if(draftTimer.current)clearTimeout(draftTimer.current);draftTimer.current=setTimeout(()=>{void save(next)},500)}} onBlur={()=>{if(draftTimer.current)clearTimeout(draftTimer.current);void save(answers)}} placeholder="Conte com suas palavras…"/></label>}
 <div className="survey-nav"><button disabled={busy} onClick={()=>setStep(step-1)}>Voltar</button><small>{busy?'Salvando…':'Progresso salvo'}</small><button className="primary" disabled={!answered||busy} onClick={async()=>{if(draftTimer.current)clearTimeout(draftTimer.current);if(await save(answers,step===qs.length-1)&&step<qs.length-1)setStep(step+1)}}>{step===qs.length-1?'CONCLUIR':'AVANÇAR'}</button></div></>:null}</section><footer>ICOM VEÍCULOS <span>Clientes de hoje. Histórias de sempre.</span></footer></main>
}
