'use client';
import {useEffect,useRef,useState} from 'react';
import {appPath} from '@/lib/paths';
import {WARRANTY_SOURCE,WARRANTY_PROCON,watchedEnough,type WarrantyConfig,type WarrantySession} from '@/lib/warranty';
export default function Warranty({token,config,initial,readOnly=false,onContinue}:{token:string;config:WarrantyConfig;initial:WarrantySession|null;readOnly?:boolean;onContinue:(session:WarrantySession|null)=>void}){
 const [session,setSession]=useState(initial),[busy,setBusy]=useState(false),[error,setError]=useState(''),[read,setRead]=useState(false),[outcome,setOutcome]=useState<'understood'|'questions'|''>('');
 const video=useRef<HTMLVideoElement>(null),allowed=useRef(initial?.watched_seconds||0),lastPosted=useRef(initial?.watched_seconds||0),pending=useRef(false),flushEnded=useRef(false);
 const content=session||config;const watched=session?.watched_seconds||0;const ready=!content.video_url||watchedEnough(watched,content.video_seconds);
 async function call(body:Record<string,unknown>){const response=await fetch(appPath(`/api/experience/${token}/warranty`),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json() as {session:WarrantySession;watched_seconds:number;error?:string};if(!response.ok)throw new Error(data.error||'Não foi possível registrar. Atualize a página.');return data;}
 async function start(){setBusy(true);setError('');try{const data=await call({action:'start'});setSession(data.session);allowed.current=data.session.watched_seconds;lastPosted.current=data.session.watched_seconds;}catch(e){setError(e instanceof Error?e.message:'Não foi possível iniciar.')}finally{setBusy(false)}}
 async function progress(force=false){const player=video.current;if(!session||!player||readOnly||session.acknowledged_at)return;if(pending.current){if(force&&player.ended)flushEnded.current=true;return;}if(!force&&player.currentTime-lastPosted.current<5)return;pending.current=true;try{const data=await call({action:'progress',session:session.id,position:player.currentTime});setSession(current=>current?{...current,watched_seconds:Number(data.watched_seconds)}:current);lastPosted.current=player.currentTime;setError('');}catch{flushEnded.current=false;player.pause();setError('Não foi possível registrar a reprodução. Atualize a página para continuar de onde parou.');}finally{pending.current=false;if(flushEnded.current){flushEnded.current=false;void progress(true)}}}
 useEffect(()=>{const pause=()=>{if(document.hidden)video.current?.pause()};document.addEventListener('visibilitychange',pause);return()=>document.removeEventListener('visibilitychange',pause)},[]);
 return <section className="warranty-content"><p className="eyebrow">ETAPA OBRIGATÓRIA · INFORMAÇÃO E TRANSPARÊNCIA</p><h1>Garantia do veículo</h1><p>Conheça seus direitos e veja como comunicar um problema à Icom.</p><div className="warranty-law"><b>Código de Defesa do Consumidor</b><p>Lei nº 8.078/1990 · artigos 18, 24, 26 e 50</p>{content.legal_text.split(/\r?\n\r?\n/).map((part,index)=><p key={index}>{part}</p>)}<a href={WARRANTY_SOURCE} target="_blank" rel="noreferrer">Consultar o CDC</a> · <a href={WARRANTY_PROCON} target="_blank" rel="noreferrer">Orientações do Procon-SP</a></div>{content.extra_text&&<aside className="warranty-extra"><h2>Orientações da Icom</h2><p>{content.extra_text}</p></aside>}
 {error&&<p className="error" role="alert">{error}</p>}
 {content.video_url?<section className="warranty-video"><h2>Como funciona a garantia</h2><p>Assista à explicação completa antes de confirmar esta etapa.</p>{!session&&!readOnly?<button className="primary" disabled={busy} onClick={start}>{busy?'PREPARANDO…':'INICIAR VÍDEO'}</button>:<video ref={video} src={content.video_url} controls playsInline preload="metadata" controlsList="nodownload noplaybackrate" onLoadedMetadata={e=>{e.currentTarget.currentTime=readOnly?0:Math.min(watched,e.currentTarget.duration)}} onTimeUpdate={e=>{const player=e.currentTarget;if(!player.seeking&&player.currentTime<=allowed.current+1)allowed.current=Math.max(allowed.current,player.currentTime);void progress()}} onSeeking={e=>{if(!readOnly&&e.currentTarget.currentTime>allowed.current+1)e.currentTarget.currentTime=allowed.current}} onRateChange={e=>{if(!readOnly&&e.currentTarget.playbackRate!==1)e.currentTarget.playbackRate=1}} onPause={()=>{void progress(true)}} onEnded={()=>{void progress(true)}} onError={()=>setError('Não foi possível abrir o vídeo. Entre em contato com a Icom para receber as orientações.')}/>}{session&&!readOnly&&<><progress value={Math.min(watched,content.video_seconds)} max={content.video_seconds} aria-label="Progresso registrado do vídeo"/><small>{Math.min(100,Math.floor(100*watched/content.video_seconds))}% da reprodução registrado{ready?' · etapa liberada':''}</small></>}</section>:<p className="notice">A explicação por vídeo será disponibilizada pela Icom. Nesta versão, sua confirmação registra a leitura das orientações acima; não registra um vídeo assistido.</p>}
 {readOnly||session?.acknowledged_at?<><p className="notice">{session?.acknowledged_at?`Confirmação registrada em ${new Date(session.acknowledged_at).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}. ${session.outcome==='questions'?'Você solicitou esclarecimentos.':'Você declarou ter compreendido as orientações.'}`:'Orientações disponíveis para consulta.'}</p><button className="primary" onClick={()=>onContinue(session)}>VOLTAR À AVALIAÇÃO</button></>:<form onSubmit={async e=>{e.preventDefault();if(!ready||!read||!outcome)return;setBusy(true);setError('');try{const active=session||(await call({action:'start'})).session;const result=await call({action:'ack',session:active.id,outcome});setSession(result.session);onContinue(result.session)}catch(e){setError(e instanceof Error?e.message:'Não foi possível confirmar.')}finally{setBusy(false)}}}><label className="checkbox"><input type="checkbox" checked={read} onChange={e=>setRead(e.target.checked)} disabled={!ready||busy}/> Li as orientações sobre a garantia e, quando disponível, assisti ao vídeo completo.</label><fieldset disabled={!ready||busy}><legend>Como você se sente sobre as orientações?</legend><label className="checkbox"><input type="radio" name="understanding" checked={outcome==='understood'} onChange={()=>setOutcome('understood')}/> Entendi as orientações.</label><label className="checkbox"><input type="radio" name="understanding" checked={outcome==='questions'} onChange={()=>setOutcome('questions')}/> Tenho dúvidas e gostaria de esclarecimentos da Icom.</label></fieldset><small>Esta confirmação não altera nem reduz seus direitos.</small><button className="primary warranty-confirm" disabled={!ready||!read||!outcome||busy}>{busy?'REGISTRANDO…':'CONFIRMAR E CONTINUAR'}</button></form>}
 </section>;
}
