import {notFound} from 'next/navigation';
import {bankPage,bankQuery} from '@/lib/icom-bank/server';
import {bankPath,canBank,currency,installmentStatus,type BankInstallment,type BankContract} from '@/lib/icom-bank/model';
import {validId,dateLabel} from '@/lib/icom-bank/contracts';
import type {BankSettings} from '@/lib/icom-bank/settings';
import type {PaymentProof} from '@/lib/icom-bank/proofs';
import BankProofUpload from '@/components/icom-bank/BankProofUpload';
import BankPixCopy from '@/components/icom-bank/BankPixCopy';
export default async function Page({params}:{params:Promise<{id:string}>}){const {token,profile}=await bankPage('dashboard'),{id}=await params;if(!validId(id))notFound();const [i]=await bankQuery<BankInstallment[]>(token,`icom_bank_installments?id=eq.${id}&select=*`);if(!i)notFound();const [[c],proofs,[settings]]=await Promise.all([bankQuery<BankContract[]>(token,`icom_bank_contracts?id=eq.${i.contract_id}&select=id,number,status`),bankQuery<PaymentProof[]>(token,`icom_bank_payment_proofs?installment_id=eq.${id}&status=in.(COMPROVANTE_ENVIADO,APROVADO,RECUSADO)&select=id,status,informed_cents,rejection_reason,created_at&order=created_at.desc&limit=100`),bankQuery<BankSettings[]>(token,'icom_bank_system_settings?id=eq.1&select=pix_key,pix_type,account_holder,agency,account_number')]);const pending=proofs.some(p=>p.status==='COMPROVANTE_ENVIADO'),closed=c?.status!=='ATIVO'||['PAGO','CANCELADO','RENEGOCIADO'].includes(i.status),balance=Math.max(0,i.updated_cents-i.paid_cents);return <><div className="bank-heading"><div><p className="bank-eyebrow">{c?.number} · PARCELA {i.number}</p><h1>Pagamento da parcela</h1><p>Vencimento: {dateLabel(i.due_date)} · {installmentStatus(i).replaceAll('_',' ')}</p></div><a href={bankPath(canBank(profile.role,'contratos')?'/contratos/'+i.contract_id:'/parcelas')}>Voltar</a></div><div className="bank-kpis"><article className="bank-kpi"><span>VALOR DA PARCELA</span><strong>{currency(i.updated_cents)}</strong></article><article className="bank-kpi green"><span>PAGO E CONFIRMADO</span><strong>{currency(i.paid_cents)}</strong></article><article className="bank-kpi navy"><span>SALDO A RECEBER</span><strong>{currency(balance)}</strong></article></div>{!closed&&<section className="bank-panel bank-form"><h2>Dados para pagamento por Pix</h2>{settings?.pix_key?<><dl className="bank-detail"><div><dt>Chave {settings.pix_type}</dt><dd>{settings.pix_key}</dd></div><div><dt>Titular</dt><dd>{settings.account_holder||'—'}</dd></div><div><dt>Agência / conta</dt><dd>{settings.agency||'—'} / {settings.account_number||'—'}</dd></div></dl><BankPixCopy value={settings.pix_key}/></>:<p>A chave Pix ainda não foi cadastrada pela administração.</p>}</section>}{!closed&&!pending?<BankProofUpload id={id} balance={balance}/>:pending?<p className="bank-note">Comprovante enviado. Aguardando análise da equipe. O saldo permanece em aberto até a confirmação.</p>:null}<section className="bank-panel"><h2>Histórico dos comprovantes</h2>{!proofs.length&&<p>Nenhum comprovante enviado.</p>}{proofs.map(p=><article className="bank-activity" key={p.id}><strong>{p.status.replaceAll('_',' ')} · {currency(p.informed_cents)}</strong>{p.rejection_reason&&<p>Motivo: {p.rejection_reason}</p>}<a href={bankPath('/api/proofs/'+p.id+'/file')}>Baixar comprovante</a>{canBank(profile.role,'comprovantes')&&<a href={bankPath('/comprovantes/'+p.id)}>Ver análise</a>}</article>)}</section></>;}
