import {randomUUID} from 'node:crypto';
import {config,db,type Profile} from './server';
import {sellerFilter} from './access';
import {phoneBR,sellerInstance,type SellerInstance} from './whatsapp';
import {seal,unseal} from './secret-box';
import {createInstance,listInstances,ownedInstance,UAZAPI_URL} from './uazapi';
type Stored={salesperson_id:string;phone:string;status:string;token_cipher:string|null;instance_id:string|null;claim_id:string;updated_at:string};
const secret=()=>process.env.ICOM_WHATSAPP_ENCRYPTION_KEY||config().key;
export async function providerStatus(){const rows=await db<{updated_at:string}[]>('experience_whatsapp_provider?id=eq.1&select=updated_at');return {configured:!!rows.length,url:UAZAPI_URL,updated_at:rows[0]?.updated_at}}
async function adminToken(){const [row]=await db<{token_cipher:string}[]>('experience_whatsapp_provider?id=eq.1&select=token_cipher');if(!row)throw new Error('A gestão precisa configurar a chave administrativa do WhatsApp.');return unseal(row.token_cipher,secret(),'provider')}
export async function configureProvider(user:Profile,raw:unknown){if(!['owner','admin'].includes(user.role))throw new Error('Acesso não autorizado.');const token=String(raw??'').trim();if(token.length<8||token.length>2000||/\s/.test(token))throw new Error('Informe a chave administrativa da Uazapi.');await listInstances(token);const cipher=seal(token,secret(),'provider');const [existing]=await db<{id:number}[]>('experience_whatsapp_provider?id=eq.1&select=id');await db(existing?'experience_whatsapp_provider?id=eq.1':'experience_whatsapp_provider',existing?'PATCH':'POST',{id:1,token_cipher:cipher,updated_at:new Date().toISOString()});}
export async function storedInstance(seller:string):Promise<SellerInstance|null>{const [row]=await db<Stored[]>(`experience_whatsapp_instances?salesperson_id=eq.${encodeURIComponent(seller)}`);if(row){if(row.status!=='ready'||!row.token_cipher)return null;return {url:UAZAPI_URL,token:unseal(row.token_cipher,secret(),seller),phone:phoneBR(row.phone)}}return sellerInstance(seller,process.env.ICOM_WHATSAPP_SELLERS)}
export async function provision(user:Profile,raw:unknown){if(user.role!=='seller')throw new Error('Acesso não autorizado.');sellerFilter(user);const seller=user.salesperson_id!,phone=phoneBR(raw);const token=await adminToken();const [row]=await db<Stored[]>(`experience_whatsapp_instances?salesperson_id=eq.${seller}`);if(row&&row.phone!==phone)throw new Error('Este login já está vinculado a outro número. Contate a gestão.');if(row?.status==='ready')return;
 const matches=(await listInstances(token)).map(value=>ownedInstance(value,seller)).filter(Boolean);
 if(matches.length>1)throw new Error('Mais de uma instância encontrada para este vendedor. Contate a gestão.');
 if(matches[0]){if(!row)throw new Error('Instância existente sem vínculo local. Contate a gestão.');await db(`experience_whatsapp_instances?salesperson_id=eq.${seller}`,'PATCH',{status:'ready',instance_id:matches[0].id,token_cipher:seal(matches[0].token,secret(),seller),updated_at:new Date().toISOString()});return;}
 if(row&&row.status==='creating'&&Date.now()-Date.parse(row.updated_at)>120000){await db(`experience_whatsapp_instances?salesperson_id=eq.${seller}&status=eq.creating`,'PATCH',{status:'unknown'});throw new Error('Criação em conferência na Uazapi. Contate a gestão antes de tentar novamente.');}
 const claim=randomUUID();const acquired=await db<boolean>('rpc/experience_whatsapp_instance_claim','POST',{p_user:user.id,p_phone:phone,p_claim:claim});if(!acquired)throw new Error('A conexão está em preparação ou conferência. Aguarde e atualize; não foi criada outra instância.');
 const result=await createInstance(token,seller);await db(`experience_whatsapp_instances?salesperson_id=eq.${seller}&claim_id=eq.${claim}&status=eq.creating`,'PATCH',{status:result.status,...(result.instance?{instance_id:result.instance.id,token_cipher:seal(result.instance.token,secret(),seller)}:{}),updated_at:new Date().toISOString()});if(!result.instance)throw new Error(result.status==='failed'?'A Uazapi recusou a criação. A gestão deve verificar a chave e o limite de instâncias.':'Não foi possível confirmar a criação. Atualize antes de tentar novamente.');
}
