import { supabase } from './supabase-client.js';
const grid=document.querySelector('#market-grid');const status=document.querySelector('#market-status');const search=document.querySelector('#market-search');const chapter=document.querySelector('#market-chapter');const dialog=document.querySelector('#business-dialog');let businesses=[];
const safe=(value)=>String(value||'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const safeUrl=(value)=>{try{const url=new URL(value);return ['http:','https:','mailto:'].includes(url.protocol)?url.href:'';}catch{return '';}};
function render(){const term=search.value.trim().toLocaleLowerCase('pt-BR');const chosen=chapter.value;const rows=businesses.filter(x=>(!chosen||x.chapter_id===chosen)&&(!term||`${x.name} ${x.segment} ${x.short_description} ${x.description} ${x.adh_chapters?.city}`.toLocaleLowerCase('pt-BR').includes(term)));grid.innerHTML='';status.textContent=rows.length?`${rows.length} empresa${rows.length===1?'':'s'} encontrada${rows.length===1?'':'s'}.`:'Nenhuma empresa encontrada.';rows.forEach(item=>{const card=document.createElement('article');card.className='market-card';card.innerHTML='<img class="market-cover"/><div class="market-card-body"><img class="market-logo"/><small></small><h2></h2><p></p><button>Conhecer empresa →</button></div>';card.querySelector('.market-cover').src=item.cover_url||item.logo_url||'assets/capitulo-taubate-oficial.png';card.querySelector('.market-logo').src=item.logo_url||'assets/logo-adhonep-expansao.png';card.querySelector('small').textContent=`${item.segment} • ${item.adh_chapters?.city||''}`;card.querySelector('h2').textContent=item.name;card.querySelector('p').textContent=item.short_description||item.description;card.querySelector('button').onclick=()=>openDetail(item);grid.append(card);});}
function action(label,url){const href=safeUrl(url);return href?`<a href="${safe(href)}" target="_blank" rel="noreferrer">${safe(label)} ↗</a>`:'';}
function openDetail(x){const detail=document.querySelector('#business-detail');const whatsapp=x.whatsapp?`https://wa.me/${x.whatsapp.replace(/\D/g,'')}`:'';const cover=safeUrl(x.cover_url||x.logo_url)||safe(x.cover_url||x.logo_url);const logo=safeUrl(x.logo_url)||safe(x.logo_url);const video=safeUrl(x.video_url);detail.innerHTML=`<article class="business-full"><img class="detail-cover" src="${safe(cover)}" alt=""><img class="detail-logo" src="${safe(logo)}" alt=""><span class="chapter">${safe(x.segment)} • CAPÍTULO ${safe(x.adh_chapters?.city).toUpperCase()}</span><h2>${safe(x.name)}</h2><p>${safe(x.description)}</p>${video?`<video controls preload="metadata" playsinline src="${safe(video)}"></video>`:''}<div class="detail-actions">${action('WhatsApp',whatsapp)}${action('Site',x.website_url)}${action('Instagram',x.instagram_url)}${action('Facebook',x.facebook_url)}${action('LinkedIn',x.linkedin_url)}${action('E-mail',x.contact_email?`mailto:${x.contact_email}`:'')}</div></article>`;dialog.showModal();}
dialog.querySelector('.dialog-close').onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog)dialog.close();};search.oninput=render;chapter.onchange=render;
const [{data:chapterRows},{data:businessRows,error}]=await Promise.all([supabase.from('adh_chapters').select('id,name,city').eq('active',true).order('city'),supabase.from('adh_businesses').select('*,adh_chapters(name,city,state)').eq('status','active').order('featured',{ascending:false}).order('name')]);
if(error){status.textContent='Não foi possível carregar as empresas agora.';}else{businesses=businessRows||[];chapter.innerHTML+=[...(chapterRows||[])].map(x=>`<option value="${x.id}">${x.name}</option>`).join('');render();}
