[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[redirects]]
  from = "/patrocinadores"
  to = "/patrocinadores.html"
  status = 200

[[redirects]]
  from = "/membros"
  to = "/membros.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200
