-- Register an anonymous visit generated by a valid member affiliation link.
-- The function exposes no profile or contact data and returns only the tracking code.
create or replace function public.adh_track_affiliate_visit(
  p_referral_code text,
  p_offer_id uuid
)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_affiliate_id uuid;
  v_affiliation_id uuid;
  v_business_id uuid;
  v_tracking_code text;
begin
  if p_referral_code is null or length(trim(p_referral_code)) < 6 or p_offer_id is null then
    return null;
  end if;

  select p.id
    into v_affiliate_id
    from public.adh_profiles p
   where p.referral_code = trim(p_referral_code);

  if v_affiliate_id is null then return null; end if;

  select a.id, o.business_id
    into v_affiliation_id, v_business_id
    from public.adh_affiliations a
    join public.adh_affiliate_offers o on o.id = a.offer_id
   where a.offer_id = p_offer_id
     and a.affiliate_id = v_affiliate_id
     and a.status = 'active'
     and o.active
   limit 1;

  if v_affiliation_id is null then return null; end if;

  insert into public.adh_referrals (
    referrer_id, business_id, offer_id, affiliation_id, status
  ) values (
    v_affiliate_id, v_business_id, p_offer_id, v_affiliation_id, 'clicked'
  )
  returning tracking_code into v_tracking_code;

  return v_tracking_code;
end;
$$;

revoke all on function public.adh_track_affiliate_visit(text, uuid) from public;
grant execute on function public.adh_track_affiliate_visit(text, uuid) to anon, authenticated;
