import test from 'node:test';
import assert from 'node:assert/strict';
import {feedbackSummary} from '../lib/feedback.ts';
import {assertManagement,scopeRows,sellerFilter,type AccessProfile} from '../lib/access.ts';
import {analytics,alertRule,assertEditable,category,questions,relationArray,sanitizeAnswers,validToken, type Experience} from '../lib/experience.ts';
test('PostgREST one-to-one relations normalize missing, object and array values',()=>{assert.deepEqual(relationArray(null),[]);assert.deepEqual(relationArray(undefined),[]);const response={answers:{nps_score:10}};assert.deepEqual(relationArray(response),[response]);assert.deepEqual(relationArray([response]),[response])});
test('NPS classification boundaries',()=>{assert.deepEqual([0,6,7,8,9,10].map(category),['detractor','detractor','passive','passive','promoter','promoter'])});
test('NPS formula and empty dataset',()=>{const rows=[10,9,7,5].map(n=>({experience_responses:[{nps_score:n,answers:{},nps_category:category(n)}],experience_alerts:[]})) as unknown as Experience[];assert.equal(analytics(rows).nps,25);assert.equal(analytics([]).nps,null)});
test('critical alert for low score even with promoter NPS',()=>{for(const field of ['overall_rating','salesperson_rating','transparency_rating','delivery_rating','store_cleanliness_rating','vehicle_cleanliness_rating','manager_rating','owner_rating'])for(const score of [1,2])assert.equal(alertRule({nps_score:10,[field]:score}).level,'critical')});
test('cleanliness and discovery answers are validated and preserved',()=>{assert.deepEqual(sanitizeAnswers({store_cleanliness_rating:4,vehicle_cleanliness_rating:5,discovery_source:'Instagram'}),{store_cleanliness_rating:4,vehicle_cleanliness_rating:5,discovery_source:'Instagram'});assert.throws(()=>sanitizeAnswers({store_cleanliness_rating:0}));assert.throws(()=>sanitizeAnswers({vehicle_cleanliness_rating:6}));assert.throws(()=>sanitizeAnswers({discovery_source:'Unknown'}))});
test('other discovery source is conditional and leadership comment needs contact',()=>{assert.ok(questions({discovery_source:'Outro'}).some(q=>q.key==='discovery_source_other'&&!q.optional));assert.equal(sanitizeAnswers({discovery_source:'Google / pesquisa na internet',discovery_source_other:'obsolete'}).discovery_source_other,undefined);assert.ok(!questions({leadership_contact:'Não tive contato'}).some(q=>q.key==='leadership_feedback'))});
test('old responses without cleanliness ratings keep empty averages',()=>{const rows=[{experience_responses:[{nps_score:10,answers:{}}],experience_alerts:[]}] as unknown as Experience[];assert.equal(analytics(rows).mean('store_cleanliness_rating'),null);assert.equal(analytics(rows).mean('vehicle_cleanliness_rating'),null)});
test('documentation low rating alerts regardless of NPS',()=>assert.equal(alertRule({nps_score:10,documentation_experience:'Um pouco complicado'}).level,'critical'));
test('passive attention, detractor and requested contact critical',()=>{assert.equal(alertRule({nps_score:8}).level,'attention');assert.equal(alertRule({nps_score:6}).level,'critical');assert.equal(alertRule({nps_score:10,contact_requested:true}).level,'critical');assert.equal(alertRule({nps_score:10}).level,'none')});
test('secure UUID v4 token validation',()=>{assert.equal(validToken('123'),false);assert.equal(validToken('not-a-token'),false);assert.equal(validToken(crypto.randomUUID()),true)});
test('conditional leadership and NPS questions',()=>{const a=questions({nps_score:5,leadership_contact:'Sim, com ambos'}).map(q=>q.key);assert.ok(a.includes('manager_rating'));assert.ok(a.includes('owner_rating'));assert.ok(a.includes('contact_requested'));assert.ok(!questions({nps_score:10,leadership_contact:'Não tive contato'}).some(q=>q.key==='manager_rating'))});
test('final validation rejects incomplete and unknown options',()=>{assert.throws(()=>sanitizeAnswers({},true));assert.throws(()=>sanitizeAnswers({overall_rating:6}));assert.throws(()=>sanitizeAnswers({leadership_contact:'invalid'}))});
test('discard obsolete branch data',()=>{const clean=sanitizeAnswers({nps_score:10,problem_areas:['Prazo'],leadership_contact:'Não tive contato',manager_rating:2});assert.equal(clean.manager_rating,undefined);assert.equal(clean.problem_areas,undefined)});
test('completed or archived surveys cannot be answered again',()=>{assert.throws(()=>assertEditable({completed_at:new Date().toISOString(),status:'respondida'}),/já foi registrada/);assert.throws(()=>assertEditable({completed_at:null,status:'arquivada'}));assert.doesNotThrow(()=>assertEditable({completed_at:null,status:'iniciada'}))});
test('draft responses do not affect NPS',()=>{const rows=[{experience_responses:[{nps_score:null,answers:{overall_rating:5}}],experience_alerts:[]}] as unknown as Experience[];assert.equal(analytics(rows).nps,null);assert.equal(analytics(rows).count,0)});
test('grouped feedback separates clients, experiences, completed ratings and item denominators',()=>{
 const rows=[
 {customer_id:'same',created_at:'2026-10-01',completed_at:'2026-10-02',experience_responses:[{nps_score:10,answers:{salesperson_rating:5,vehicle_cleanliness_rating:4}}],experience_alerts:[]},
 {customer_id:'same',created_at:'2026-10-03',completed_at:'2026-10-04',experience_responses:[{nps_score:6,answers:{salesperson_rating:3}}],experience_alerts:[]},
 {customer_id:'other',created_at:'2026-10-05',completed_at:null,experience_responses:[{nps_score:null,answers:{salesperson_rating:1}}],experience_alerts:[]},
 ] as unknown as Experience[];
 const summary=feedbackSummary(rows),seller=summary.items.find(i=>i.key==='salesperson_rating')!,vehicle=summary.items.find(i=>i.key==='vehicle_cleanliness_rating')!;
 assert.equal(summary.customers,2);assert.equal(summary.experiences,3);assert.equal(summary.responses,2);assert.equal(summary.responseRate,67);assert.equal(seller.mean,4);assert.equal(seller.satisfaction,50);assert.equal(vehicle.mean,4);assert.equal(vehicle.count,1);assert.equal(vehicle.satisfaction,100);assert.equal(summary.stats.nps,0);assert.deepEqual(summary.months,['2026-10']);assert.equal(seller.distribution.find(d=>d.score===5)?.percent,50);
});
test('empty grouped feedback shows no fabricated zero rating or satisfaction',()=>{const summary=feedbackSummary([]);assert.equal(summary.responseRate,null);for(const item of summary.items){assert.equal(item.mean,null);assert.equal(item.satisfaction,null);assert.equal(item.count,0)}});
test('seller authorization filters at database boundary and fails closed without link',()=>{
 const seller={id:'user',name:'Seller',role:'seller',salesperson_id:'12345678-1234-4234-8234-123456789abc',leadership_access:false} as AccessProfile;
 assert.equal(sellerFilter(seller),'&salesperson_id=eq.12345678-1234-4234-8234-123456789abc');assert.throws(()=>sellerFilter({...seller,salesperson_id:null}));assert.throws(()=>assertManagement(seller));assert.equal(sellerFilter({...seller,role:'owner',salesperson_id:null}),'');assert.doesNotThrow(()=>assertManagement({...seller,role:'owner'}));
});
test('seller sees only own feedback with leadership and internal alert treatment removed',()=>{
 const seller={id:'user',name:'Seller',role:'seller',salesperson_id:'12345678-1234-4234-8234-123456789abc',leadership_access:true} as AccessProfile;
 const rows=[{id:'own-experience',salesperson_id:'12345678-1234-4234-8234-123456789abc',experience_responses:[{answers:{salesperson_rating:5,manager_rating:1,leadership_feedback:'private'}}],experience_alerts:[{alert_reason:'private',resolution_notes:'internal'}]},{id:'other-experience',salesperson_id:'other',experience_responses:[],experience_alerts:[]}] as unknown as Experience[];
 const scoped=scopeRows(seller,rows);assert.equal(scoped.length,1);assert.equal(scoped[0].id,'own-experience');assert.deepEqual(scoped[0].experience_responses[0].answers,{salesperson_rating:5});assert.deepEqual(scoped[0].experience_alerts,[]);assert.equal(rows[0].experience_responses[0].answers.manager_rating,1);
 assert.equal(scopeRows({...seller,role:'owner'},rows).length,2);assert.equal(scopeRows({...seller,role:'owner'},rows)[0].experience_responses[0].answers.manager_rating,1);
});
