import {test} from 'node:test';
import assert from 'node:assert/strict';
import {investorInput,investorMatches,type BankInvestor} from '../lib/icom-bank/investors.ts';
import {bundledCatalog} from '../lib/icom-bank/fipe-server.ts';
import {adminInput} from '../lib/icom-bank/administrative.ts';
const id='aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa';
test('Investor registry normalizes names and preserves optional contacts',()=>{const p=investorInput({id,name:' Eric   Mauro ',email:'eric@example.com',phone:'11999999999',notes:' Parceiro ',expected_updated_at:null});assert.equal(p.name,'Eric Mauro');assert.equal(p.notes,'Parceiro');assert.equal(p.expected_updated_at,null);});
test('Investor registry rejects malformed id, contact, timestamp and oversized text',()=>{for(const changes of [{id:'fake'},{name:'A'},{email:'bad'},{expected_updated_at:'never'},{phone:'1'.repeat(31)},{notes:'x'.repeat(2001)},{name:42}])assert.throws(()=>investorInput({id,name:'Eric Mauro',...changes}));});
test('Investor relationship uses registered ID and only falls back to names for legacy rows',()=>{const i={id,name:'Eric Mauro'} as BankInvestor;assert.equal(investorMatches(i,{investor_id:id,investor_name:'Snapshot'}),true);assert.equal(investorMatches(i,{investor_id:'bbbbbbbb-bbbb-4bbb-bbbb-bbbbbbbbbbbb',investor_name:'Eric Mauro'}),false);assert.equal(investorMatches(i,{trade_investor_name:' eric mauro '},true),true);assert.equal(investorMatches(i,{investor_name:'Different'}),false);});
test('All bundled brands and Chevrolet versions remain usable without network',()=>{const brands=bundledCatalog();assert.ok(brands.length>=100);const gm=brands.find(x=>x.name==='GM - Chevrolet');assert.ok(gm);const versions=bundledCatalog(gm.code);assert.ok(versions.some(x=>/onix/i.test(x.name)));assert.ok(versions.some(x=>/astra/i.test(x.name)));assert.deepEqual(bundledCatalog('invalid'),[]);});
test('Sale retains investor IDs and clears stale ownership fields for store/no trade',()=>{const raw={id,expected_updated_at:null,kind:'VENDA',scope:'LOJA',entry_date:'2026-10-06',description:'Venda teste',category:'Venda',status:'REALIZADO',amount_cents:100000,details:{vehicle:'Onix',purchase_cents:0,vehicle_cost_cents:0,commission_cents:165000,sale_cents:100000,sale_owner:'INVESTIDOR',investor_name:'Eric Mauro',investor_id:id,trade_in:false,payment_method:'PIX'}};assert.equal(adminInput(raw).details.investor_id,id);assert.throws(()=>adminInput({...raw,details:{...raw.details,investor_id:'x'}}));const store=adminInput({...raw,details:{...raw.details,sale_owner:'LOJA',trade_investor_id:id,trade_investor_name:'Eric Mauro'}});assert.equal(store.details.investor_id,undefined);assert.equal(store.details.trade_investor_id,undefined);});

