import {test} from 'node:test';
import assert from 'node:assert/strict';
import {cashPosition,saleCash,type CashEntry} from '../lib/icom-bank/cash.ts';
import {adminInput,saleProfit,type AdminEntry} from '../lib/icom-bank/administrative.ts';
const id='aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa',stamp='2026-10-06T12:00:00Z';
const sale=(details:AdminEntry['details']={},amount=5000000):CashEntry=>({id,kind:'VENDA',scope:'LOJA',entry_date:'2026-10-06',description:'Venda exemplo',category:'',status:'REALIZADO',amount_cents:amount,active:true,created_at:stamp,updated_at:stamp,details:{vehicle:'Exemplo',purchase_cents:9000000,vehicle_cost_cents:100000,commission_cents:165000,sale_cents:10000000,sale_owner:'INVESTIDOR',investor_name:'Investidor A',trade_in:true,trade_has_debts:false,trade_value_cents:5000000,trade_destination:'INVESTIDOR',trade_investor_name:'Investidor A',...details}});
const out=(amount:number,part='CUSTOS'):CashEntry=>({...sale(),id:crypto.randomUUID(),kind:'CUSTO',amount_cents:amount,details:{sale_cost_id:id,settlement_part:part as 'CUSTOS'}});
test('Investor example: 50k cash splits into 42650 investor and 7350 net store profit; profit unchanged',()=>{const e=sale(),c=cashPosition([e]);assert.equal(saleProfit(e),735000);assert.equal(c.investor,4265000);assert.equal(c.costs,0);assert.equal(c.available,735000);assert.equal(c.gross,5000000);});
test('Partial collection holds investor capital first; planned receipt is not money',()=>{const e=sale({},3000000);assert.equal(cashPosition([e]).available,0);const later:CashEntry={...e,id:crypto.randomUUID(),kind:'ENTRADA',amount_cents:2000000,entry_date:'2026-11-01',cash_source_id:id};assert.equal(cashPosition([e,later],'2026-10-31').available,0);assert.equal(cashPosition([e,later]).available,735000);assert.equal(cashPosition([e,{...later,status:'PREVISTO'}]).available,0);assert.equal(cashPosition([e,{...later,active:false}]).available,0);});
test('Different investor receives trade: do not credit its car against original investor capital',()=>{const e=sale({trade_investor_name:'Investidor B'});const c=cashPosition([e]);assert.equal(c.investor,5000000);assert.equal(c.available,0);});
test('Trade stays at store: investor principal is still held, no fictional liquid profit',()=>{const e=sale({trade_destination:'LOJA'});assert.equal(cashPosition([e]).available,0);});
test('Store owned sale keeps actual collected cash; trade is not cash',()=>{const e=sale({sale_owner:'LOJA',trade_destination:'LOJA'});const c=cashPosition([e]);assert.equal(c.investor,0);assert.equal(c.available,5000000);});
test('Missing legacy owner or destination holds proceeds until explicitly reviewed',()=>{for(const d of [{sale_owner:undefined},{trade_destination:undefined},{trade_in:undefined}]){const e=sale(d);const c=cashPosition([e]);assert.equal(c.review,5000000);assert.equal(c.available,0);assert.equal(c.reviewCount,1);}});
test('Repasse 30k to31k releases only1k; zero seller commission is explicit',()=>{const e=sale({sale_owner:'LOJA',sale_mode:'REPASSE',trade_in:false,purchase_cents:3000000,sale_cents:3100000,vehicle_cost_cents:0,commission_cents:0},3100000),c=cashPosition([e]);assert.equal(c.capital,3000000);assert.equal(c.available,100000);assert.equal(saleProfit(e),100000);});
test('Repasse loss is debited only after actual full collection',()=>{const e=sale({sale_owner:'LOJA',sale_mode:'REPASSE',trade_in:false,purchase_cents:3000000,sale_cents:2900000,vehicle_cost_cents:0,commission_cents:0},2900000);assert.equal(cashPosition([e]).available,-100000);assert.equal(cashPosition([{...e,amount_cents:1000000}]).available,0);assert.equal(cashPosition([{...e,status:'PREVISTO'}]).available,0);});
test('Linked costs consume reserve and cash together, without double-deducting profit',()=>{const e=sale(),payment=out(265000);const before=cashPosition([e]),after=cashPosition([e,payment]);assert.equal(after.costs,0);assert.equal(after.available,before.available);assert.equal(after.gross,4735000);assert.equal(cashPosition([e,{...payment,active:false}]).available,before.available);});
test('Investor capital returned reduces gross cash and reserve while store available stays unchanged',()=>{const e=sale(),payment=out(4000000,'INVESTIDOR');const after=cashPosition([e,payment]);assert.equal(after.investor,265000);assert.equal(after.available,735000);assert.equal(after.gross,1000000);});
test('Linked stock preparation costs are counted once even if paid before sale',()=>{const e=sale({stock_id:'bbbbbbbb-bbbb-4bbb-bbbb-bbbbbbbbbbbb'}),payment:CashEntry={...out(100000),cash_cost_source_id:id,cash_cost_part:'CUSTOS',entry_date:'2026-09-30',details:{stock_id:e.details.stock_id}};const c=cashPosition([e,payment]);assert.equal(c.investor,4165000);assert.equal(c.costs,0);assert.equal(c.available,735000);});
test('Trade debt paid for same investor reduces return without deducting store profit again',()=>{const e=sale({trade_has_debts:true,trade_has_payoff:false,trade_ipva_cents:500000,trade_fines_cents:0},5500000);const c=cashPosition([e]);assert.equal(c.investor,4765000);assert.equal(c.costs,0);assert.equal(c.available,735000);const debt:CashEntry={...out(500000),details:{},cash_cost_source_id:id,cash_cost_part:'DEBITOS'};assert.equal(cashPosition([e,debt]).available,735000);assert.equal(cashPosition([e,debt]).investor,4265000);assert.equal(cashPosition([e,debt]).costs,0);});
test('Other months, personal/general expenses and archived rows affect cumulative cash correctly',()=>{const e=sale(),general:CashEntry={...out(100000),entry_date:'2026-09-01',details:{}},personal:CashEntry={...out(50000),kind:'PESSOAL',scope:'PESSOAL',details:{}};assert.equal(cashPosition([e,general,personal]).available,585000);assert.equal(cashPosition([e,{...general,active:false},personal]).available,685000);});
test('Typed ownership validates investor names, destination and repasse prerequisites',()=>{const e=sale();const body={...e,expected_updated_at:null,details:{...e.details,plate:'ABC1D23',trade_vehicle:'Troca',trade_plate:'XYZ1A23',trade_year:2020,payment_method:'PIX'}};assert.equal(adminInput(body).details.sale_owner,'INVESTIDOR');for(const d of [{investor_name:''},{trade_destination:undefined},{trade_investor_name:''},{sale_mode:'REPASSE'}])assert.throws(()=>adminInput({...body,details:{...body.details,...d}}));});
test('Untrusted input cannot create decorated receipt link',()=>{const e=sale();const p=adminInput({...e,kind:'ENTRADA',details:{cash_source_id:id},expected_updated_at:null});assert.deepEqual(p.details,{});});
test('No future sale or payment creates available cash; cumulative cutoff is respected',()=>{const e=sale();assert.equal(cashPosition([e],'2026-10-05').available,0);assert.equal(saleCash({...e,active:false},[e]).received,0);});
test('Trade resold by store forwards its capital to original investor operation once',()=>{const e=sale({trade_destination:'REPASSE'}),child:CashEntry={...sale({sale_owner:'LOJA',sale_mode:'REPASSE',trade_in:false,purchase_cents:5000000,sale_cents:5100000,vehicle_cost_cents:0,commission_cents:0},5100000),id:crypto.randomUUID(),cash_stock_origin_id:id};const c=cashPosition([e,child]);assert.equal(c.investor,9265000);assert.equal(c.capital,0);assert.equal(c.costs,0);assert.equal(c.available,835000);assert.equal(saleCash(child,[e,child]).available,100000);});
test('Partial resale capital remains held for original investor; no profit released early',()=>{const e=sale({trade_destination:'REPASSE'}),child:CashEntry={...sale({sale_owner:'LOJA',sale_mode:'REPASSE',trade_in:false,purchase_cents:5000000,sale_cents:5100000,vehicle_cost_cents:0,commission_cents:0},2000000),id:crypto.randomUUID(),cash_stock_origin_id:id};const c=cashPosition([e,child]);assert.equal(c.investor,7000000);assert.equal(c.capital,0);assert.equal(c.available,0);});
test('Loss caused by costs is counted once before and after costs are actually paid',()=>{const e=sale({sale_owner:'LOJA',sale_mode:'REPASSE',trade_in:false,purchase_cents:3000000,sale_cents:3100000,vehicle_cost_cents:200000,commission_cents:0},3100000);const paid=out(200000);assert.equal(cashPosition([e]).available,-100000);assert.equal(cashPosition([e,paid]).available,-100000);assert.equal(cashPosition([e,{...paid,amount_cents:100000}]).available,-100000);assert.equal(cashPosition([e,paid]).loss,-100000);});

test('Bruno example: 72000 collected minus 14150 net profit leaves 57850 for same investor',()=>{
 const e=sale({sale_cents:10200000,purchase_cents:8600000,vehicle_cost_cents:20000,trade_value_cents:3000000},7200000);
 const c=cashPosition([e]);assert.equal(c.available,1415000);assert.equal(c.investor,5785000);assert.equal(c.costs,0);
 const returned=out(5785000,'INVESTIDOR'),after=cashPosition([e,returned]);assert.equal(after.investor,0);assert.equal(after.gross,1415000);assert.equal(after.available,1415000);
});
test('Investor costs and trade debt paid separately reduce amount returned, not net profit',()=>{
 const e=sale({trade_has_debts:true,trade_ipva_cents:500000},5500000),cost=out(265000),debt:CashEntry={...out(500000),details:{},cash_cost_source_id:id,cash_cost_part:'DEBITOS'};
 const c=cashPosition([e,cost,debt]);assert.equal(c.investor,4000000);assert.equal(c.costs,0);assert.equal(c.available,735000);
 assert.equal(cashPosition([e,cost,debt,out(4000000,'INVESTIDOR')]).available,735000);
});
test('Registered investor IDs determine trade ownership; legacy names are fallback',()=>{
 const a=crypto.randomUUID(),b=crypto.randomUUID();assert.equal(cashPosition([sale({investor_id:a,trade_investor_id:b})]).available,0);
 assert.equal(cashPosition([sale({investor_id:a,trade_investor_id:a,trade_investor_name:'Display label'})]).available,735000);
});
test('An unpaid trade debt for a store-retained car remains reserved separately',()=>{
 const e=sale({trade_destination:'LOJA',trade_has_debts:true,trade_ipva_cents:500000},5500000),c=cashPosition([e]);assert.equal(c.costs,500000);assert.equal(c.investor,5000000);assert.equal(c.available,0);
});
test('Investor loss is debited once when fully collected and remains after return',()=>{
 const e=sale({purchase_cents:10000000},5000000);assert.equal(cashPosition([e]).available,-265000);assert.equal(cashPosition([e,out(5000000,'INVESTIDOR')]).available,-265000);
});
